### ISSUE TITLE
[overall] repetition - possibly tweak "Learning Outcomes" & "Ideas for Assessment" ?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#100]
Overall there seems to be a too much repetition within each Unit page. That is, the introductions, learning outcomes, teaching ideas, homework ideas, and ideas for assessment are too repetitive.

I'm not sure what to do about that?

Maybe not have "Learning Outcomes" at the Unit level, since they are the same as the Learning Outcomes under the Topics? (and wording them differently I think is potentially more confusing)

The "Ideas for Assessment" are too much like Learning Outcomes. (ref https://github.com/w3c/wai-curricula/issues/76 ) Maybe these can be eliminated? If not, it seems they should be more like assignments somewhat like the Homework Ideas. I defer to others with more experience and training in formal education! <-- Howard, Estella, Kris Anne, Brent, etc!

Note: I do think you've done a good job at getting rid of the previous repetition of the resources!

**Comment by daniel-montalvo** [comment]
Agree.

I had tried to work on this by eliminating learning outcomes (those at a unit level) since I didn't think they add too much, especially after we have a dedicated topics with sections under such topics.

@nitedog and I decided not to carry on with this approach, but we could give it another try.

**Comment by daniel-montalvo** [comment]
Addressed. Now the former "Ideas for Assessment" have been replaced with "Ideas to Assess Knowledge", and look like suggested activities to check if students have indeed acquired the knowledge in the learning outcomes.
