### ISSUE TITLE
[Unit 4] W3C accessibility standards - only mentioning 4 main ones?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#101]
Does Unit 4 just cover WCAG, ATAG, UAAG, ARIA? Note there are other standards listed in https://www.w3.org/WAI/standards-guidelines/ 

If yes, how do we address that in the text? In [preview 96](https://deploy-preview-96--wai-curricula.netlify.com/curricula/1-4/), I tried "the 4 main W3C accessibility standards" -- but that's not clear or smooth.

**Comment by daniel-montalvo** [comment]
I have worked on this unit with only these four in mind, which might be also questionable as to whether or not we should constrain this unit to these four. I guess this is a good balance between providing a little bit mor details (as it was one of the first conclusions on EOWG meetings early in April) but not too much.

@yatil suggested "main standards" without the "four" which seems good to me.
Anyway, I will seek for @nitedog 's input as well.

**Comment by yatil** [comment]
[Brain is storming]

TBH, thinking about it some more, ARIA is not really a good fit for this as it is really technical. Maybe we want to concentrate this Unit to the XXAG standards only and then write “the three core accessibility standards”?

**Comment by shawna-slh** [comment]
We do need to mention ARIA and make sure students generally understand what it is.

I have had people ask, "Should we be using ARIA or WCAG?" ! :-/

**Comment by daniel-montalvo** [comment]
Something like "The three core accessibility standards and the WAI-ARIA specification"

**Comment by shawna-slh** [comment]
/me looks at it in context... maybe just avoid it all together! :-)

Maybe change:
> Define the scope of the 4 main W3C accessibility standards: Web Content Accessibility Guidelines (WCAG), ...

to:
> Define the scope of the W3C accessibility standards Web Content Accessibility Guidelines (WCAG), ...

And maybe change:
>Identify the scope of each of the 4 main W3C accessibility standards and explain some of their guidelines and success criteria

to:
>Identify the scope of WCAG, ATAG, UAAG, and ARIA, and explain some of their guidelines and success criteria

**Comment by yatil** [comment]
I think always listing the standards is a mouth/eye full :-)

Talking and writing about standards has never been easy.

**Comment by nitedog** [comment]
I agree with @slhenry's suggestion. For the first instance, when the acronyms need to be expanded, can use a list to make it easier to read. No need for "the 4" or "the 3 core" denotations IMO.

**Comment by daniel-montalvo** [comment]
Closing this with the two commits above. Feel free to reopen if necessary.

**Comment by yatil** [comment]
Great work, @daniel-montalvo!
