### ISSUE TITLE
[Unit 4] Topic: First Checks for Web Accessibility – title

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#102]
When I said I wasn't sure about "Easy Checks" fitting in this Unit, Daniel said it was a way to make an otherwise somewhat boring Unit more interactive and experiential. That resonated with me! :-)

I think you want to make that even stronger. Maybe title this topic something along the lines of:

* Exploring Principles and Standards Implementation

* Hand-on Experience of Principles and Standards in Practice

* Real Examples of Web Accessibility Principles and Standards

**Comment by daniel-montalvo** [comment]
I think this needs @nitedog  's input as well. Will add this to the todo list and discuss with him since it is part of a more general approach.

**Comment by nitedog** [comment]
I like "Hand-on Experience of Principles and Standards in Practice". Maybe shorter too:

> Hands-on Experience of Standards in Practice

**Comment by daniel-montalvo** [comment]
title changed as can be seen at https://deploy-preview-72--wai-curricula.netlify.com/curricula/1-4/#topic-hands-on-experience-of-standards-in-practice
