### ISSUE TITLE
[Unit 4][low] Teaching Resources - Standards Harmonization

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#104]
I'm inclined not to include this resource because:
* it's sorely outdated (revision from long ago was never finished)
* it doesn’t directly relate to any of the learning outcomes or teaching ideas.

I do not feel strongly, though -- so OK leaving if others do feel strongly.

**Comment by daniel-montalvo** [comment]
For topic "Standards and Guidelines", Norah says:

> It feels like something is missing between the first and second links. Standards should be more thoroughly discussed before moving to the process that is used to develop the standards:
>
> ...
>
> Perhaps, add a second resource such as Why Standards Harmonization is Essential to Web Accessibility - 

There is one place in which we could mention that resource. Worth discussing, I guess.

**Comment by daniel-montalvo** [comment]
We will differed to @nitedog 's input on this one.

**Comment by nitedog** [comment]
I think this is a good suggestion. No need to add a lot, just a bullet, resource, and associated learning outcome. Depending on the context, instructors may decide to spend more or less time on this point (like for any point).
