### ISSUE TITLE
Overall Title 

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#112]
current:
> Web Accessibility Curricula

see [6 September EOWG teleconference](https://www.w3.org/2019/09/06-eo-minutes.html)

maybe something like:
> Web Accessibility Curricula Framework

**Comment by nitedog** [comment]
I think that is really heavy and unclear. As far as I understand, there is no uniform way of defining curricula, and what we have would qualify as a curriculum. There are curricula that are more generic, and some more specific. If needed, maybe we can consider a sub-title. Something like:

> Web Accessibility Curricula: Framework for Building Your Courses

**Comment by daniel-montalvo** [comment]
Changed to:

> Curricula on Web Accessibility: A Framework to Build Your Own Courses 

https://deploy-preview-114--wai-curricula.netlify.com/curricula/
