### ISSUE TITLE
[Ideas for Assessment]: Unit 1

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#115]
When we spoke about "Idea for Assessment" as a title, I had no good ideas for how to replace it. But there is something kind of off about this. For one, assessment is thought to be like a test and this does not seem to be that.  Also, how does it translate. Here are some brainstorms
- Test your skills
- Student activities
- Demonstrate knowledge
- Demonstrate student understanding
- What have students learned?
- Applied skills and learning

**Comment by daniel-montalvo** [comment]
Closing this. It is changed now to "Ideas to Assess Knoledge"
