### ISSUE TITLE
In that document sometimes not convenient to use lists.

### ISSUE THREAD

**Issue by Inclusive-it** [w3c/wai-curricula#121]
This includes burning using navigation keys. Most likely defect provokes again the structure of the table. It is lists some of the elements in the headings "Structure". There three list one is one ite, second one item, third is six items. In firefox when you use hot key "l" to move through lists nvda says @list of one item, list of one item, list of 6 items "when tester goes to this lists. Because of this, the testers are sometimes confused. Selector of list - #main> ul: nth-child (7)

**Comment by daniel-montalvo** [comment]
Thanks for your comments.

We are currently using nested lists, this is why NVDA says "list of 1 item" in the first two items (modules and units).

With nested lists we tried to convey the overall structure of the curricula. The first level is "modules". The second level is "units". The rest of the items we mention in these lists are within the "unit" pages and this is why they are in the third nesting level.

Would it be easier for you if we stop using nested lists?

Thanks.

**Comment by daniel-montalvo** [comment]
Stopped using nested lists. Closing. Feel free to come back if there are new issues.
