### ISSUE TITLE
Content propositions

### ISSUE THREAD

**Issue by Inclusive-it** [w3c/wai-curricula#122]
Given that this document is draft and the proposed structure can be difficult to change more or less measurable. 
The advantage is that the themes are developed for a specific target audience: developers, designers, content makers and others. 
Some the testers are believed that the decomposition rate of the levels: basic, intermediate, advanced inappropriate. 
The base level should be a separate training course with the requirements of the target audience. 
Go to the next training only after passing this basic course. 
And then share courses offered on topics (threads are formed for each target audience), for example:
- the availability of sites; 
- the availability of office documents (text, spreadsheets, presentations); 
- the availability of other documents (PDF, MathML ...) 
- the availability of separate applications for different platforms, each separately, including mobile some other courses of specialization (eg computer games) 
Thus a potential student will be able to choose exactly what he needs at the mome

**Comment by daniel-montalvo** [comment]
Hello,

Thanks for your input.

I need a bit more clarification on this issues.

* The module "Introduction to Web Accessibility" is considered to be in a basic level. This module is for all the roles outlined in this page: Developer, Designer, Author, Manager, and Tester. This is the only module for that level.
* The rest of the outlined modules are considered either intermediate or advanced, not basic. Each of them applies to a specific audience.

Don't you agree with this classification?

Could you please elaborate on what specifics do you miss under the intermediate / advance levels?

Thanks.

**Comment by daniel-montalvo** [comment]
Hi:

We have made more changes, clarifying the scope of what we have and what is yet to come. We developed "Introduction to web Accessibility", and the rest of the outline is a plan we have for the future, that might be changed.

We have also added a caption and a summary for that table.

Closing this issue, feel free to reopen if you want to provide further input.
