### ISSUE TITLE
Proposals for Unit 1: What is Web Accessibility

### ISSUE THREAD

**Issue by gernus** [w3c/wai-curricula#123]
May show some examples of barriers at the beginning by comparisons as a very first introduction: e.g.
- Image (simulation of cataract) vs. alternative text
- Unstructured text vs. structured text
- Unstructured form vs. structured form
- Very complex language vs. simple language

May also show examples of barriers that are barriers for everyone but not for Screenreader or AT users.

Computers and the Web are in a way assistive technologies themselves. Pointing out the benefits of computers, the Web, etc. for people with disabilities is essential. The access to the Digital Life can massively improve the quality of life and independent living of people with disabilities. E.g. Online Banking, Online Shopping, eGovernment, etc. making career with the help of computers

May also enhance the user stories: Why is the Web important for them? Does the Web improve their quality of live?

Students may ask people with disabilities about the benefits of Computers, the Web, etc.

Students should examine their Digital Live and their most important use cases

**Comment by daniel-montalvo** [comment]
> May show some examples of barriers at the beginning by comparisons as a very first introduction: e.g.
> 
> * Image (simulation of cataract) vs. alternative text
> * Unstructured text vs. structured text
> * Unstructured form vs. structured form
> * Very complex language vs. simple language
> May also show examples of barriers that are barriers for everyone but not for Screenreader or AT users.

I think we can condense these thoughts in the introduction of the first topic as follows:

> -Introduce real stories of how people with disabilities interact with web pages and applications. If you can, invite people with disabilities to demonstrate assistive technologies and adaptive strategies they use. Include time for students to ask questions. If you cannot bring real people, refer to [Web Accessibility Perspectives Videos](/perspective-videos/) and [How People with Disabilities Use the Web](/people-use-web/).
> +Introduce real stories of how people with disabilities interact with web pages and applications. If you can, invite people with disabilities to demonstrate assistive technologies and adaptive strategies they use. Include time for students to ask questions. If you cannot bring real people, refer to [Web Accessibility Perspectives Videos](/perspective-videos/) and [How People with Disabilities Use the Web](/people-use-web/). Mention examples like structured versus unstructured text and complex versus simple language, as potential barriers for everybody.

> Computers and the Web are in a way assistive technologies themselves. Pointing out the benefits of computers, the Web, etc. for people with disabilities is essential. The access to the Digital Life can massively improve the quality of life and independent living of people with disabilities. E.g. Online Banking, Online Shopping, eGovernment, etc. making career with the help of computers
> 
> May also enhance the user stories: Why is the Web important for them? Does the Web improve their quality of live?

These are added in two of the teaching ideas:
> -* Point out how design features can enable or disable people by teaching the social model of disability. Refer to Introduction to Web Accessibility page, [Accessibility in Context section](/fundamentals/accessibility-intro/#context).
> +* Point out how design features can enhance people's quality of life by teaching the social model of disability. Refer to Introduction to Web Accessibility page, [Accessibility in Context section](/fundamentals/accessibility-intro/#context).
>-* Invite expert users with disabilities to show the assistive technologies and adaptive strategies they use when interacting with websites and applications. Ask these users to explain  some accessibility features and barriers.
> +* Invite expert users with disabilities to show the assistive technologies and adaptive strategies they use when interacting with online banking, online shopping or eGovernment. Ask these users to explain  how technology and the Web benefits them.


> Students may ask people with disabilities about the benefits of Computers, the Web, etc.
> 
> Students should examine their Digital Live and their most important use cases

I will emphasize this more in this idea for assessment:

> -* Presentation &mdash; Students present a particular type of disability or an assistive technology they are interested in. Assess students' capacity to reflect on the innovation, potential, and broader benefits of accessibility features.
> +* Presentation &mdash; Students present digital life and most important use cases for a particular type of disability they are interested in. Assess students' capacity to reflect on the innovation, potential, and broader benefits of accessibility features.


Would these additions help?
