### ISSUE TITLE
Proposals for Unit 2: People and Digital Technology

### ISSUE THREAD

**Issue by gernus** [w3c/wai-curricula#124]
- Students also should examine operating systems regarding built-in assistive technology functionality: Screenreaders, Magnifiers, virtual keyboard, keyboard mouse, sticky keys, visual warning, ... they should try these features.
- What about the accessibility features of web browsers? Students should do some research
- Do people with disabilities always use the latest technology (e.g. latest Screenreader, latest browser, latest operating system)? Students should do some research
- Optional: some words on accessibility frameworks like User Interface Automation of Windows or Accessibility Framework on OS X;  the relation between assistive technology, accessibility frameworks and operating system

**Comment by daniel-montalvo** [comment]
> * Students also should examine operating systems regarding built-in assistive technology functionality: Screenreaders, Magnifiers, virtual keyboard, keyboard mouse, sticky keys, visual warning, ... they should try these features.
> * What about the accessibility features of web browsers? Students should do some research

I think the following teaching idea reflects what you are expressing above:

> * Encourage students to try some adaptive strategies following expert advice by exploring different settings in web browsers and operating systems.

We can make it more explicit:

> * Encourage students to explore built in accessibility settings in web browsers and operating systems following expert advice.

Would it address your concern?

> * Do people with disabilities always use the latest technology (e.g. latest Screenreader, latest browser, latest operating system)? Students should do some research

We could add these thoughts to the following idea for assessment. It currently says:

> Interview — Students contact a person with a disability and interview them about what accessibility features and barriers they encounter when trying to access digital content or applications. Assess students’ capacity to identify such features and barriers and link them to the knowledge they acquired.

And it can say:

> * Interview &mdash; Students contact a person with a disability and interview them about what accessibility features and barriers they encounter when trying to access digital content or applications, as well as how up-to-date they are with technology. Assess students' capacity to identify such features and barriers and link them to the knowledge they acquired.

Would this help?

> * Optional: some words on accessibility frameworks like User Interface Automation of Windows or Accessibility Framework on OS X;  the relation between assistive technology, accessibility frameworks and operating system

We plan to develop more curricula addressing specific audiences: developers, designers, testers, managers...
I think this thought would fit well in a curriculum for developers, so I definitely take this into account for future work.

**Comment by gernus** [comment]
> - Encourage students to explore built in accessibility settings in web browsers and operating systems following expert advice.

It's perect

**Comment by gernus** [comment]
> - Interview — Students contact a person with a disability and interview them about what accessibility features and barriers they encounter when trying to access digital content or applications, as well as how up-to-date they are with technology. Assess students' capacity to identify such features and barriers and link them to the knowledge they acquired.

It's perfect

**Comment by gernus** [comment]
> - Optional: some words on accessibility frameworks like User Interface Automation of Windows or Accessibility Framework on OS X; the relation between assistive technology, accessibility frameworks and operating system

I think, a very basic understanding about the interaction between assistive technology and the operating system would be good at the beginning. But, as I wrote - it's optional.

**Comment by daniel-montalvo** [comment]
Hi Gerhard:

Two more little tweaks:

* Current wording: "* Study the interdependencies between components of web accessibility (web browsers, authoring tools, web designers and developers, and more)".
* Suggested change: "* Study the interdependencies between components of web accessibility (web browsers, authoring tools, web designers and developers, accessibility platforms, and operating systems)".



* Current wording: "• Introduce potential options to improve accessibility in different situations. Guide students to reflect on the implications of using a more accessible browser, exploring plug-ins for tools, and requiring accessibility during procurement".
* Suggested wording: "* Introduce potential options to improve accessibility in different situations. Guide students to reflect on the implications of using a more accessible browser, exploring accessibility platforms and APIs, and requiring accessibility during procurement".[



I am closing this as I think this would address this second part, but feel free to reopen if needed.
