### ISSUE TITLE
Proposals for Unit 3: Business Case and Benefits

### ISSUE THREAD

**Issue by gernus** [w3c/wai-curricula#125]
Impact of Web Accessibility on Search Engines / Search Results -> SEO with Web Accessibility

Accessible Websites may have a better ranking in search results -> quite a good sales argument for Web Accessibility

**Comment by daniel-montalvo** [comment]
Hi Gerhard:

I propose to introduce this thought in one of the teaching ideas of this module.

Current wording: "* Introduce case studies of organizations who have adopted accessibility. Explain the resulting benefits, such as improved brand reputation."
Suggested changes: "* Introduce case studies of organizations who have adopted accessibility. Explain the resulting benefits, such as improved brand reputation or increased search traffic."

Would this help?

**Comment by gernus** [comment]
> Suggested changes: "* Introduce case studies of organizations who have adopted accessibility. Explain the resulting benefits, such as improved brand reputation or increased search traffic."

Maybe: "* Introduce case studies of organizations who have adopted accessibility. Explain the resulting benefits, such as improved brand reputation or improved search result ranking."

**Comment by daniel-montalvo** [comment]
Done!

Thank you very much for your detailed input.

I will close the issue, feel free to reopen if necessary.
