### ISSUE TITLE
[Curricula opening page] - Learning Outcomes definition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#127]
[!!]
Current wording:

> Learning Outcomes — Describe what the students need to know after completion of the unit. This is the core of the curricula.

Suggested wording:

> Learning Outcomes — Describe what the students will know and should be able to demonstrate after completion of the unit. This is the core of the curricula.

Rationale: A learning outcome is and "outcome." What is the end result, not what is needed.

**Comment by daniel-montalvo** [comment]
Thanks for your input, @bakkenb 

You can see a preview addressing this issue at https://deploy-preview-132--wai-curricula.netlify.com/curricula/

**Comment by bakkenb** [comment]
I still do not feel that this is addressed properly. The current preview wording still uses the term, "what the students need to know".  A learning outcome is not what they "need to know", that is an Objective. A Learning Outcome is what the student "will know after completion." I still feel like the following wording should be used:

> Learning Outcomes — Describe what the students will know and should be able to demonstrate after completion of the unit. This is the core of the curricula.

**Comment by daniel-montalvo** [comment]
Should be fixed now. I had not changed the verb. Sorry about that.

It is now:

> * Learning Outcomes &mdash; Defines what students will learn and should be 
able to demonstrate. This is the core of the curricula.

Note that I changed "know" to "learn". We cannot be sure if they will know, this is what the ideas to assess knowledge are for.

**Comment by bakkenb** [comment]
+1 to this change. Thank you.
