### ISSUE TITLE
[Curricula Opening Page] - Topics definition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#128]
[!!]
Feel like we need to use the Oxford comma here to clarify sentence...

Current wording:
> Topics — Stand for specific pieces of content within the units. They also expand the learning outcomes, teaching ideas and ideas to assess knowledge.

Suggested wording: 
> Topics — Stand for specific pieces of content within the units. They also expand the learning outcomes, teaching ideas, and ideas to assess knowledge.

**Comment by daniel-montalvo** [comment]
Thanks for your input, @bakkenb 

You can see a preview addressing this issue at https://deploy-preview-132--wai-curricula.netlify.com/curricula/
