### ISSUE TITLE
[Curricula Opening Page] Ideas to Assess Knowledge definition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#129]
[medium/strong]

Current wording:
> Ideas to Assess Knowledge — Describe a variety of activities that instructors can carry out to assess students’ performance. These are not compulsory. You can adapt them to your particular needs, remove some of them or add new ones if necessary.

Suggested wording:
> Ideas to Assess Knowledge — Describe a variety of activities that instructors can carry out to assess students’ **knowledge**. These are not compulsory. You can adapt them to your particular needs, remove some of them or add new ones if necessary.

Rationale: Are we providing ideas that actually assess a students' performance? I am not sure we are. These are more about assessing the students' knowledge of the concepts being taught. To assess their performance we would need to add activities that actually the remediation of accessibility issues or conducting real evaluations.

**Comment by daniel-montalvo** [comment]
Thanks for your input, @bakkenb 

You can see a preview addressing this issue at https://deploy-preview-132--wai-curricula.netlify.com/curricula/
