### ISSUE TITLE
[Curricula Opening Page] Teaching Resources definition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#130]
[!!]
Typo. Second use of "contents" in this paragraph should be "content".

Current wording:
> Teaching Resources — Introduce resources to teach the contents in the units. It is advisable that you use them to build the course, but you can extend the list as needed to achieve your particular goals. Some of these are linked through the curricula contents, some others can serve as further readings for you and your students.

Suggested wording:
> Teaching Resources — Introduce resources to teach the contents in the units. It is advisable that you use them to build the course, but you can extend the list as needed to achieve your particular goals. Some of these are linked through the curricula **content**, some others can serve as further readings for you and your students.

Rationale: When referring to many parts of content (as a noun) in a work you say "contents," which is correct in the first sentence. When referring to the entire body of work as we do in the third sentence, "the curricula content," then we should not have the "s" at the end.

Grammar people, please double check this for me.

**Comment by daniel-montalvo** [comment]
Thanks for your input, @bakkenb 

You can see a preview addressing this issue at https://deploy-preview-132--wai-curricula.netlify.com/curricula/
