### ISSUE TITLE
[Curricula Opening Page] Table heading/cell alignment

### ISSUE THREAD

**Issue by mpalmersg** [w3c/wai-curricula#133]
The insertion of the 'Basic' row breaks the visual association between the cell headers and the values further down the page.

**Comment by daniel-montalvo** [comment]
Thanks for your input.

While we figure out if we can fix the alignment, would it block publication in your view? How much does it impact access to information and understanding of the structure of the table?

Thanks.

**Comment by yatil** [comment]
@daniel-montalvo Visually there is a large-ish gap (as long as the list in the basic row) between the headers and the Intermediary row. That means it is is hard to scan the header cells in context to the content cells. 

We could repeat the header cells – but that would be unconventional for users be cause the table only has three rows.

Dismantling the table as suggested in #137 would probably fix this issue, too.

**Comment by daniel-montalvo** [comment]
Table has been simplified.

* We no longer have this "Basic" row,
* We have now "Developer Modules", "Foundation Modules", and "Author |Modules" underneath the "Foundation Modules" to make it easier to relate and process.
