### ISSUE TITLE
[ED-med] future just draft

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#136]
Under https://www.w3.org/WAI/curricula/#future-outline

Make it clear that the table is draft ideas, not finalized.

**Comment by daniel-montalvo** [comment]
An attempt is at 591a68e260ef785ea6c677cc1b47f7051bf7b8b9

**Comment by daniel-montalvo** [comment]
Removed in 22ff98d631cb8efa747cc4efe44b43f9d8a5522a
