### ISSUE TITLE
[ED-low] table width

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#137]
Under https://www.w3.org/WAI/curricula/#future-outline
tweak the table to limit horizontal scrolling:

Consider changing table to multiple nested headings (as @yatil prefers) -- e.g.,
<h3>Basic for Developer, Designer, Author, Manager, Tester
<h3>Intermediate
<h4>Developer
<h4>Designer
<h4>Author
<h4>Manager
<h4>Tester
<h3>Advanced
<h4>Developer
<h4>Designer

<hr>
Or removing the space before the bullet items (which @yatil doesn't like).

Or using the full width of the page (which I assume @yatil doesn't like).

**Comment by yatil** [comment]
> Or removing the space before the bullet items (which @yatil doesn't like).

Which is not really possible to do well in all browsers. This has nothing to do with what I like.

> Or using the full width of the page (which I assume @yatil doesn't like).

We are using the full width of the content. We don’t have a template that goes wider and that would break reading line length even more. It would need a full redesign of the website, which is hard to pull off in just a couple of hours until we publish. Again, this has nothing to do with what I like or not.

**Both** solutions would only work on certain width desktop browsers and still break hard on mobile (which is our preferred agreed-on fallback).  This works on desktop as “well” as on mobile.

See #140.

**Comment by yatil** [comment]
FWIW, this is how I have in the past successfully implemented scrollable tables: https://5ddcfcd0a1d7a800093c6f7b--wai-curricula.netlify.com/curricula/

**Comment by daniel-montalvo** [comment]
This seems to have been fixed after the table simplification at https://wai-curricula.netlify.com/curricula/
