### ISSUE TITLE
[ED-very-low] table description

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#138]
Under https://www.w3.org/WAI/curricula/#future-outline

> Rows refer to three levels: basic, intermediate, and advanced. Columns refer to five roles: developer, designer, author, manager, and tester.

This seems unnecessary.

**Comment by daniel-montalvo** [comment]
Hey Shawn,

Thanks for your feedback.

I wrote this thinking about:
* Screen reader users, who might find it difficult to navigate this table as #120 seems to suggest.
* People with cognitive disabilities, who might find it hard to process this table. This description might help them understand the concepts that we are using.

Why do you think it is unnecessary? Would you remove it completely?

**Comment by shawna-slh** [comment]
We have not done this in the past with tables. Not sure why we would now. I think that most -- if not all -- of the target audience for this material should be fine with tables.

*If* we were to decide to do it, it should be *before* the table, not after.
