### ISSUE TITLE
[ED-Med] Assessing something that hasn't been taught

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#148]
In People and Digital Technology, Diverse Abilities, Tools, and Strategies, one of the assessment is:

> * Practice &mdash; Students go to three different types of websites (e.g., shopping site, banking site, or entertainment site) and identify accessibility features from those they learned about. Assess students' capacity to explain how better design can enhance those features.

However, the topic goals are:

- List types of disabilities and related accessibility needs.
- Define the terms “assistive technology” and “adaptive strategies”.
- List some examples of assistive technologies and adaptive strategies.
- Describe some accessibility design features and barriers.

These don't seem to match up.

**Comment by daniel-montalvo** [comment]
Hi @iadawn 

I am assuming that what is a bit awkward here is:

> ... Assess students' capacity to explain how better design can enhance those features.

It is a fair point that asking students to explain how design can enhance those features is asking too much at this state.

Changed to:

> ... Assess students' capacity to recognize accessibility features.

b564953
