### ISSUE TITLE
Replacing "Prerequisites" with a more defining term: "Competences" "Prior knowledge"

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#15]
We may be interested in replacing the current "Prerequisites" heading by "Competences" or a similar formula. This is a suggestion by @eoncins To be aligned with the terminology used in HE (Higher Education), as it is shown in ["Defining, writing and applying learning outcomes"](https://www.cedefop.europa.eu/en/publications-and-resources/publications/4156). The relation there is clear between learning outcomes and competences of learners.

**Comment by bakkenb** [comment]
To me this depends on how the term "prerequisites" is being used. If straight forward, simpler terminology may be "prior knowledge." I will look into where it is being used to see if I want to comment further.

**Comment by Sylduch-Conseil** [comment]
Prior knowledge sound clear to me. Pre-requisites is a term we also use in French, but it sounds more difficult to pronounce in English. Otherwise, what about : "what you should know before doing this course."? Otherwise, I have no further ideas.

**Comment by daniel-montalvo** [comment]
Thanks all @bakkenb  and @Sylvie42  for your comments.
"What you should know before this course: is what we somehow want to cover in that section but I am afraid it might be too long a heading, so definitely prior knowledge would well summarize that phrase.

Let's wait if somebody else comments on this to make a decision, given that "Competences" seemed to have some rejections due to being a complicated word to understand.

**Comment by eoncins** [comment]
I would shift the problematic issue on the title if an explanation is given. I think that after the title it might be worth to provide a sentence with the comments from @Sylvie42 "what you should know before doing this course."
Therefore, you can use: "Pre-requisites" "Basic competences" or "prior knowledge" and then add this sentence.

**Comment by daniel-montalvo** [comment]
That sentence seemed like only addressing students. Now we have "Skills required for this unit" which I think:

* Covers both instructors and students.
* Steps back a little bit. We are not building a specific course but a resource for other to develop their own courses.

Closing this, feel free to reopen if needed.
