### ISSUE TITLE
[ED-med] Vague wording

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#151]
In the intro. when defining structure, we say "...which are not necessarily taught in this grouping" Not sure what this means or what the intent is.  Does it mean "do not have to be taught in this specific order"  ?  Needs clarification.

**Comment by daniel-montalvo** [comment]
Thanks @sharronrush 

Changed to:

> * Topics &mdash; Thematic gathering of objectives within a module, which are not necessarily taught in a specific order.

Does it clarify?

Thanks!

**Comment by sharronrush** [comment]
Yes thank you!
