### ISSUE TITLE
[ED-Med] Inconsistency in presentation of outcomes

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#152]
In Business Case and Benefits the student outcomes for the module are presented in a nested list:

> * Explain how accessibility can:
>   * Extend market reach.
>   * Demonstrate social responsibility.
>   * Drive innovation.
>   * Minimize legal risk.

However, in the topic within the module they are presented as a simple list:

> * List examples of organizations that have adopted accessibility, and the benefits these organizations report.
> * List examples of accessibility features and explain how they also benefit people without disabilities.
> * Explain how accessibility can enhance brand reputation and help demonstrate social responsibility.
> …

The former was a bit off as it differed from the previous presentation of outcomes. The latter is a bit off because of the repetition.

Both are off because they are not consistent.

**Comment by daniel-montalvo** [comment]
Hi @iadawn 

We decided to use nested lists to avoid repetition. It is tru that his is the first time in the curriculum that we use nested lists for learning outcomes but we use them in other sections, such as the [Structure](https://wai-curricula.netlify.com/curricula/#structure) , or [competencies for module 4](https://wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/principles-standards-and-checks/#competencies) , or [Competencies for module 5](https://wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/getting-started-with-accessibility/#competencies)

I have adapted the learning outcomes of the topic in d407801 as follows:

<blockquote>

* List examples of organizations that have adopted accessibility, and the benefits these organizations report. 
* Explain how accessibility can:
  * Benefit people with and without disabilities.
  * Enhance brand reputation and help demonstrate social responsibility.
  * Help reduce overall maintenance and remediation costs.
  * Promote human-centered design approaches, which result in more usable products.
* Describe some potential risks of not addressing accessibility, such as possible lawsuits and costly litigations.

</blockquote>
