### ISSUE TITLE
[ED-Med] Unclear value

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#153]
In Business Case and Benefits, Benefits of Accessibility, Teaching Ideas one idea is:

> * Reflect about how accessibility can reduce design and development time if implemented from the beginning, e.g., when selecting a specific CMS for a project. Contrast the amount of time it takes to implement accessibility depending on CMS support.

Achieving an accessible end product is cheaper if you start early. Taking an accessible approach isn't cheaper whether you start early or late if you are unconcerned about the accessibility of the end product.

So, accessibility does not reduce design and development time.

Also, I am not sure the example helps as product procurement is not necessarily the same as product development.

**Comment by sharronrush** [comment]
Yes this is a good point. The phrasing here is not quite right. Suggest:
- Compare the cost and effectiveness of retro fitting for accessibility vs integrating accessibility requirements into a project from the start.  
- Contrast the amount of time it takes to implement accessibility depending on CMS support.
- Discuss the need for procurement as well as development processes to integrate accessibility requirements.

**Comment by daniel-montalvo** [comment]
Hi @iadawn  and @sharronrush 

Changed to:

> * Compare the cost and effectiveness of integrating accessibility requirements into a project from the start versus integrating accessibility later. Discuss the need for procurement as well as development processes to integrate accessibility requirements.

Removed references to CMS support as it is a very specific use case and we have generalized this idea with the second sentence.

cb89a4c

See https://wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/business-case-and-benefits/

**Comment by iadawn** [comment]
Slight flip around of second sentence. Otherwise, looks good :)

> Compare the cost and effectiveness of integrating accessibility requirements into a project from the start versus integrating accessibility later. Discuss the need to integrate accessibility requirements and standards into procurement as well as development processes.

**Comment by daniel-montalvo** [comment]
Appreciated. See 8eaf46b and https://wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/business-case-and-benefits/#topic-benefits-of-accessibility for it in context.
