### ISSUE TITLE
[!!] Principles not described

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#156]
In Principles, Standards, and Checks, Principles of Web Accessibility is states:

> Introduce the web accessibility concepts Perceivable, Operable, Understandable, and Robust (POUR). Refer to [Accessibility Principles](/fundamentals/accessibility-principles/).

However, this resource doesn't actually explain POUR. It uses them as headings for grouped Guidelines but doesn't really talk about the high level principles. Doing a quick search I only found: https://www.w3.org/TR/UNDERSTANDING-WCAG20/intro.html#introduction-fourprincs-head.

If the goal is to explain the Principles and then explore what aspects of standards are grouped within the Principles then there is a bit more needed in this introduction and possibly in the learning outcomes.

**Comment by daniel-montalvo** [comment]
Fair point. We can include this reference as follows, pointing to WCAG 2.1 instead of WCAG 2.0:

> Introduce the web accessibility concepts Perceivable, Operable, Understandable, and Robust (POUR). For an explanation of these concepts, see [Understanding the Four Principles of Accessibility](https://www.w3.org/WAI/WCAG21/Understanding/intro#understanding-the-four-principles-of-accessibility). For an introduction to some web accessibility requirements belonging to each principle, refer to [Accessibility Principles](/fundamentals/accessibility-principles/).

And then change the second learning outcome of this topic to:

* List requirements of each of the principles.


Would this address your issue?

**Comment by iadawn** [comment]
Awesome... I was sure there was a 2.1 version of the page, just couldn't find the thing!

**Comment by daniel-montalvo** [comment]
Good!

Would you then consider this solved?

**Comment by iadawn** [comment]
I would

**Comment by daniel-montalvo** [comment]
Thanks.
