### ISSUE TITLE
[!!] Unclear topic introduction

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#158]
In Getting Started with Accessibility, Planning and Managing Web Accessibility introduction it states:

> Select strategies that best apply to the students’ context.

It is not clear what this means or relates to.

**Comment by daniel-montalvo** [comment]
Hello Kevin,

This resource contains many strategies that one can use to integrate accessibility throughout the web production process. We are telling instructors to go to that resource and select those strategies that are relevant to the students' context. Some may need to emphasize strategies such as "Develop business case" or "Raise awareness", and others may be interested in "Review websites" and "prioritize issues".

If I change to:

> Select strategies that best apply to the students’ context from [Planning and Managing Web Accessibility](/planning-and-managing/).

Would that make this clearer?

**Comment by iadawn** [comment]
Unfortunately not that much.

I am trying to think exactly what is not clear and I think it is roughly around:

* It is not clear why there is a need to 'select strategies' - why would you select them? what for? to achieve what?
* It is not clear what relevance the students' context has - what about their context matters for the strategy? what learning would be taken from this?

**Comment by daniel-montalvo** [comment]
The idea of selecting specific strategies was to help instructors narrow the scope of their courses. Those with accessibility expertise might know which strategies are more needed depending on the context of their students, but other instructors might skip this and just present them all. We have been working with the hypothesis that, in an introductory course, all planning strategies should not be presented in all contexts, but maybe this is wrong and we need to generalize it more. 


Let's see if the following helps:

Current:

> Select strategies that best apply to the students’ context from [Planning and Managing Web Accessibility](/planning-and-managing/). Emphasize that it is crucial to have management support to succeed in long-term accessibility implementations.

Proposed:

> Introduce strategies from [Planning and Managing Web Accessibility](/planning-and-managing/). Emphasize that it is crucial to have management support to succeed in long-term accessibility implementations.

And then qualify in the teaching idea:

> * Introduce specific considerations to integrate accessibility based on your particular students.

**Comment by nitedog** [comment]
How about something like:

> Introduce different approaches for integrating accessibility throughout the design and development process.

Or

> Introduce different strategies for integrating accessibility throughout the design and development process.

Or

> Introduce different approaches for integrating accessibility throughout the design and development process, and help students select strategies that best apply to their context.

**Comment by iadawn** [comment]
@nitedog I think that is much more action oriented and clearer on the teaching ask. Of the three, the first seems to be most sensible:

>Introduce different approaches for integrating accessibility throughout the design and development process.

I think there is scope to revisit and iterate this but that is clearer.

**Comment by daniel-montalvo** [comment]
Good!

@iadawn At least for this first iteration this would solve the issue, right?

**Comment by iadawn** [comment]
All good
