### ISSUE TITLE
[ED-low] Ideas to assess knowledge sections

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-curricula#159]
It struck me in reviewing the curricula that we have Ideas to assess knowledge under each topic and then overarching ideas to assess knowledge for the entire module.  Should we differentiate between the assessment for the topic vs. module?  For instance, specify "Ideas to assess topic knowledge."  Apologies if this has been discussed already - I just found it slightly confusing when I was going from the last topics Ideas to assess knowledge into the module ideas to assess knowledge.

**Comment by daniel-montalvo** [comment]
Hi @kakinney 

We discussed [The structure for unit 1](https://www.w3.org/2019/09/20-eo-minutes.html#item02) and decided we were going to apply this in the rest of the units.
Then we changed these [ideas](https://www.w3.org/2019/09/06-eo-minutes.html#item03).

What is exactly that strikes you from the last topic and unit 5 ideas for assessment?

Open to refine as needed in the coming weeks.

**Comment by kakinney** [comment]
Hi Daniel, 
I didn't specifically mean the unit 5 ideas for assessment.  I just meant the titles of the Headings are the same and when they are back to back, it may cause confusion.   Let me see if I can get a screenshot to show you what I mean.

**Comment by daniel-montalvo** [comment]
Thanks @kakinney 

Don't worry, a screenshot won't mean much to me as I am a screen reader user myself. Definitely feel free to upload it if you think it can help others.

I definitely make a note on this. My understanding is that EOWG agreed on the major structure and this included having "Ideas to Assess Knowledge" both at a topic and at a module level. 

With that being said, I think we could close this and revisit in future iterations if there are further problems related to this structure. Feel free to reopen if you feel I have not addressed your concern appropriately.

Thanks.

**Comment by kakinney** [comment]
I was trying to figure out how to mark it up so that it would be accessible to you.  But closing it is fine, it was just a point I wanted to raise that could cause potential confusion, but I am fine with just passing on it.

**Comment by nitedog** [comment]
@kakinney we also use the same title "Learning Outcomes" on the Module and Topic levels. Do you feel that is also confusing? Or is "Ideas to Assess Knowledge" potentially more confusing because they appear closer to each other (end of the last Topic is close to the end of the Module, so the two headings appear in close proximity but for different parts of the Curriculum)?

**Comment by kakinney** [comment]
I think it was the close proximity that caused confusion.  I had finished reading "Ideas to Assess Knowledge" and went into reading "Ideas to Assess Knowledge" that were entirely different than what I had just read.   It made me do a double-take and I wanted to bring it up in case it may do something similar for someone else too.    Just calling out a point of confusion I had - may not cause confusion for anyone else.

**Comment by nitedog** [comment]
I'm not sure EOWG considered that particular aspect when the title name was picked but @daniel-montalvo would know better. Maybe this can be fixed visually (ie. more spacing or such), or maybe needs something bigger. Or nothing at all, if others don't encounter the same confusion (it didn't occur to me personally but now you raised it, I see your point and that it could confuse others).

**Comment by shawna-slh** [comment]
I think adding "for Module" or "for Topic" is a simple fix. e.g.:
h2> Introduction
h2> Learning Outcomes for Module   _(probably not needed for this one?)_
h2> Competencies
h2> Topics to Teach in Module   _(probably not needed for this one?)_
h3> Topic: Stories of People with Disabilities
h4> Learning Outcomes for Topic
h4> Teaching Ideas for Topic
h4> Ideas to Assess Knowledge for Topic
h3> Topic: Scope of Web Accessibility
h4> Learning Outcomes for Topic
h4> Teaching Ideas for Topic
h4> Ideas to Assess Knowledge for Topic
h2> Ideas to Assess Knowledge for Module
h2> Teaching Resources for Module   _(maybe not needed for this one?)_

While it makes the headings longer, it provides clarity -- and people using this regularly, will probably easily "mask them out" when not needed

**Comment by kakinney** [comment]
Thanks, @slhenry - that is what I had thought, but I wasn't sure if others had a similar concern as I did.  I don't see a problem differentiating, just for clarity. Its not too much more text for additional noise, just adds clarity.

**Comment by shawna-slh** [comment]
[EOWG minutes 13 Dec](https://www.w3.org/2019/12/13-eo-minutes.html#item04)

**Comment by daniel-montalvo** [comment]
> I think adding "for Module" or "for Topic" is a simple fix. e.g.:

Sure. And thanks @kakinney for raising this.

> h2> Introduction
> h2> Learning Outcomes for Module _(maybe not needed for this one?)_

I think it is needed, since it is repeated at a topic level.

> h2> Competencies
> h2> Topics to Teach in Module _(maybe not needed for this one?)_

I think it is not needed, since it is not repeated (it appears once per module).

> h3> Topic: Stories of People with Disabilities
> h4> Learning Outcomes for Topic
> h4> Teaching Ideas for Topic
> h4> Ideas to Assess Knowledge for Topic
> h3> Topic: Scope of Web Accessibility
> h4> Learning Outcomes for Topic
> h4> Teaching Ideas for Topic
> h4> Ideas to Assess Knowledge for Topic
> h2> Ideas to Assess Knowledge for Module
> h2> Teaching Resources for Module _(maybe not needed for this one?)_

I think this is not needed since it is not repeated (it appears once per module).
> 
> While it makes the headings longer, it provides clarity -- and people using this regularly, will probably easily "mask them out" when not needed
