### ISSUE TITLE
[!!]Module 5 URL

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-curricula#161]
Under the topic:  Developing Policies and Statements
The URL for Developing the Organizational Policy on Web Accessibility is oddly displayed.  The link works, but all this extra text is displayed.  Just needs to be cleaned up.  

 See Developing Organizational Policies on Web Accessibility%20and%20%5BDeveloping%20an%20Accessibility%20Statement%5D(/planning/statements/)

**Comment by daniel-montalvo** [comment]
Thanks for raising this.

Should be fixed when merged You can see a preview at https://deploy-preview-143--wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/getting-started-with-accessibility/
