### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-curricula#162]
I have posted the preview on Twitter this morning in a conversation and [the question of licensing came up](https://twitter.com/mgifford/status/1200027699076632577). “Why not chose a Creative Commons License?” That’s a good question, I thought, so I posted it here.

I personally think it might be beneficial for take-up to use a standard CC license instead of the W3C license that we usually use (which was described as “confusing”).

Thoughts?

(This question is not blocking publication.)

**Comment by shawna-slh** [comment]
Daniel, unless @nitedog disagrees, please add this to the footer of each page, at the end:

```
<p><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p>
```

**Comment by nitedog** [comment]
Fine by me.

**Comment by yatil** [comment]
@daniel-montalvo @slhenry @nitedog I’ll provide a way to specify the license in the header area that puts out the correct code which will make it easier when we update the license (which basically is happening with this update, considering [this PR which updates our licenses from CC unported 3.0 to CC Intl. 4.0](https://github.com/w3c/wai-about-wai/pull/60/files)). We can then also have the license specified in the metadata of the HTML output which makes it easier to find when people are searching for specifically licensed content.

I’ll also add a CC icon to our icon set so that it works nicely in the footer.

**Comment by yatil** [comment]
I’ve added the CC functionality in https://github.com/w3c/wai-website-theme/commit/feb6542293ddda812ef5eaa32085f6b0e633272d (including documentation) and updated #163 to match. I will now merge the Pull Request.
