### ISSUE TITLE
Unit 1: Learning outcomes

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#17]
3 Learning Outcomes begin with "Understanding." It should be that the outcome is to Understand...
or the outcome is Understanding of...
My preference is for the first, an outcome is that the student will:  
 - Understand the definition of web accessibility for people with disabilities
- etc

**Comment by daniel-montalvo** [comment]
Thanks for the comments!
Further work needs to be devoted to learning outcomes: its structure, the verbs in use, and the scope of some of them for an introductory module like this one. We definitely take this into account and will be working on them in #14

**Comment by daniel-montalvo** [comment]
Addressed in #22. Feel free to reopen if you feel there is more to do here.
