### ISSUE TITLE
minor text edits for https://wai-curricula.netlify.app/curricula/developing-accessible-content/

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-curricula#177]
https://wai-curricula.netlify.app/curricula/developing-accessible-content/

Under Module 1
Topic: Marking up Page ontents.  - should be Contents

Also some of the list items have periods at the end and some do not. I suggest removing all periods for list items that do not contain a complete sentence.

**Comment by daniel-montalvo** [comment]
> https://wai-curricula.netlify.app/curricula/developing-accessible-content/
> 
> Under Module 1
> Topic: Marking up Page ontents. - should be Contents

Topic references should now be updated (and that typo should be corrected).

> Also some of the list items have periods at the end and some do not. I suggest removing all periods for list items that do not contain a complete sentence.

Thanks for raising this. Last year we discussed it in
https://github.com/w3c/wai-curricula/issues/98
, but punctuation at the end of lists is something we may want to discuss again as we diverged a bit from our style guide.

**Comment by daniel-montalvo** [comment]
Hey @lakeen 
This should now be fixed. Please note that I reorganized module 1 according to other comments. You can see a preview at https://5ef34a4fd612ce00078e8256--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/

I am closing this issue, but reopening #98 to deal with overall list capitalization and terminal punctuation
