### ISSUE TITLE
[Module 1 Page Structure] Topic: Headings

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-curricula#178]
https://wai-curricula.netlify.app/curricula/developing-accessible-content/page-structure/
Topic: Headings
Under "teaching Ideas for Topic"  - capitalize Teaching
First bullet under Optional Ideas

"Invite students to explore screen readers to go to next or previous heading. Show advanced functionality that allows to present all headings in a list where users can select the one they want to get to. For reference on how screen reader users interact and navigate web pages, see Stories of Web Users."

Revise sentences: "Invite students to explore screen readers to go to next or previous heading. Show advanced functionality that allows to present all headings in a list where users can select the one they want to get to. “
Suggest: “Invite students to navigate headings using a screen reader. Explore advanced screen reader functionality which presents all headings in a list where users can select the heading they are interested in.”

**Comment by daniel-montalvo** [comment]
> https://wai-curricula.netlify.app/curricula/developing-accessible-content/page-structure/
> Topic: Headings
> Under "teaching Ideas for Topic" - capitalize Teaching
> First bullet under Optional Ideas
> 
> "Invite students to explore screen readers to go to next or previous heading. Show advanced functionality that allows to present all headings in a list where users can select the one they want to get to. For reference on how screen reader users interact and navigate web pages, see Stories of Web Users."
> 
> Revise sentences: "Invite students to explore screen readers to go to next or previous heading. Show advanced functionality that allows to present all headings in a list where users can select the one they want to get to. “
> Suggest: “Invite students to navigate headings using a screen reader. Explore advanced screen reader functionality which presents all headings in a list where users can select the heading they are interested in.”

Thanks for this!

These issues Should be now fixed. Please see teaching ideas for:
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-headings
and
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-page-regions
I am closing this, feel free to reopen if needed.
