### ISSUE TITLE
[Module 2 Navigation and Menus] Topic: Multiple Ways of Navigation - grammer - suggested revision

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-curricula#179]
https://wai-curricula.netlify.app/curricula/developing-accessible-content/navigation-and-menus/
Topic: Multiple Ways of Navigation
Second bullet Under Teaching Ideas for Topic
Revise sentence: “Explain that they can be included using either a form field with a button to trigger the search, or a link that takes to the search form.”
Suggest: “Explain that search functions can be included with a textbox form field and button to trigger the search or, a link that takes the user to the search form.”

**Comment by daniel-montalvo** [comment]
Thanks @lakeen 

We are now working within the Task force to include navigation an orientation strategies in module 1, under a topic called (not surprisingly) [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation). Teaching ideas for search functions, site maps, and breadcrumbs have been put together, as there were some comments that the way we presented search functions was a little bit dry from a developer's perspective. What do you think about these changes?

**Comment by daniel-montalvo** [comment]
We are leaning towards covering multiple ways for navigation more deeply in future curricula for authors and designers. References are still kept at
https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#topic-page-structure
but the sentence mentioned in this issue is no longer in the draft.
