### ISSUE TITLE
Unit 1 Topic: Stories of People with Disabilities

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#18]
1. Issue: 1st paragraph repetition of "real" is awkward.
Change: 
Introduce real stories of how people with disabilities use the Web. If you can, invite real people with disabilities to demonstrate how they use the Web. 
To: 
Introduce stories of people with disabilities actively using the web. As it is possible, invite actual people with disabilities to the class to demonstrate how they use the Web.  
(3rd use of real in the paragraph is then OK)

2. Learning Outcomes - again, ungrammatical use of "ing" ending.

3. Teaching Ideas: awkward sentence - "Coach students in trying out assistive technologies and adaptive strategies by themselves." Suggested alternative: "Encourage students to try out assistive technologies and adaptive strategies by themselves."

4. Tips advise to "emphasize the social model of disability and avoid using a medical approach." 
Will instructors understand that without further explanation?

**Comment by daniel-montalvo** [comment]
Thanks for the comments.

> Issue: 1st paragraph repetition of "real" is awkward.

I note this down and work on this later on. This sentences has received comments from more people as well.

> Learning Outcomes - again, ungrammatical use of "ing" ending.

Learning outcomes will be dealt with in #14 


> Teaching Ideas: awkward sentence 

@slhenry also had concerns with this sentences, it definitely needs to be reworded.

> Tips advise to "emphasize the social model of disability and avoid using a medical approach."

This will be dealt with in July 12th meeting discussion. How we portray people with disabilities.

**Comment by daniel-montalvo** [comment]
Addressed in #22. Feel free to reopen if you feel there is more to do here.
