### ISSUE TITLE
[overview pages] "Its aims are to:" setence seems confusing

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#180]
On the overview pages of the "Introduction" and "Developer" curricula we have this sentence:

> "Its aims are to:"

Followed by a bulleted list, listing different aims.

However, this seems slightly confusing as it implies that these are the aims of the curricula, as opposed to courses developed based on this curricula. I think a more accurate sentence would be:

> "This curriculum results in courses that:"

**Comment by daniel-montalvo** [comment]
Hey @nitedog 

I added this to:
* [Editor's draft](https://wai-curricula.netlify.com/curricula/developing-accessible-content/) for the developers' curriculum.
* [Possible changes](https://deploy-preview-165--wai-curricula.netlify.app/curricula/introduction-to-web-accessibility/) for the introduction to web accessibility curriculum.

I am closing this. Feel free to reopen if necessary.

**Comment by daniel-montalvo** [comment]
> I added this to:
> 
> * [Editor's draft](https://wai-curricula.netlify.com/curricula/developing-accessible-content/) for the developers' curriculum.
> * [Possible changes](https://deploy-preview-165--wai-curricula.netlify.app/curricula/introduction-to-web-accessibility/) for the introduction to web accessibility curriculum.
