### ISSUE TITLE
[Module 1: Page Structure] Order of topics

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#181]
I think the order of the topics should be changed to:

1. Headings
2. Page Contents
3. Page Regions
4. Meta Information

I think this better reflects importance, ease of implementation and value to end user.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for this.

I think these contents could really be taught in many different orders. I have updated the order according to your suggestions, but please note that the Task Force is discussing a module reorganization that includes now navigation and orientation strategies in the last topic of the module that were previously taught in the second module.

You can take a look at https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/
