### ISSUE TITLE
[Module 1: Page Structure] Aside missing from Page Regions

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#182]
Is the `aside` element missing from the Page Regions topic?

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for this.

I have added `aside` and `article` in the [learning outcomes](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-page-regions). Not so in the teaching ideas, as they are about showing different page layouts that contain different page regions (among which `aside` and `article` could be included).

I am afraid, though, that we may be getting into too much level of detail. Let's see what others think about it.

**Comment by nitedog** [comment]
I like the addition of these elements. Not sure why they can't be added to the corresponding teaching idea in the same way but don't feel too strongly.

**Comment by daniel-montalvo** [comment]
> I like the addition of these elements. Not sure why they can't be added to the corresponding teaching idea in the same way but don't feel too strongly.

I menat that currently in the learning outocmes we mention the element itself (and we style it differently) and in the teaching ideas the emphasis is in the different layouts containing these elements. Anyway, the teaching idea now reads:

> * Show examples of different page layouts, and their markup of the header, navigation, main content, section, article, complementary, and footer regions. Emphasize that native HTML elements are more likely to be supported by browsers and assistive technologies. For guidance on how to code HTML5 sections, see the WAI website tutorials, [Regions](https://www.w3.org/WAI/tutorials/page-structure/regions/).
