### ISSUE TITLE
[Module 1: Page Structure] Explaining the purpose of regions and how they are used

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#183]
Is there a learning outcome missing around the purpose of the regions and how they are used?

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for your feedback.

I plan to do the following:

- Change the introductory paragraph of this topic to:
  "Explain how page regions, such as header, footer, navigation, and main, allow people with disabilities to orient and navigate. Provide hands-on training for common markup used to identify such page regions".
- Change the first of the learning outcomes to:
  "Describe how page regions allow people with disabilities to interact with and move through a web page by using":

I think these changes better convey that, in our context, the purpose of regions is to allow for orientation and navigation. Is that what you mean by the purpose of regions?

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for your feedback.

I am not sure if I understand this correctly. Maybe something like:

"Define the scope and purpose of `header`, `footer`, `main`, `section` ... etc?

I see you refer to this in #185 but not in the headings topic. Would you also add this in the headings topic?

**Comment by iadawn** [comment]
Use of headings seems more obvious. Not sure it is necessary there.

**Comment by daniel-montalvo** [comment]
I think this is addressed in the current version of the draft at 
https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#topic-page-regions

Closing, feel free to reopen if needed.
