### ISSUE TITLE
[Module 1: Page Structure] Missing information on writing good headings

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#184]
I think there could be more around writing good headings. It is touched on but there isn't anything that would encourage teaching of this as a key outcome for the topic.

Actually, it is there... but I think priority is given to learning how to use screen readers and sort out hierarchy. I think there may be an opportunity to promote the value of the actual words in the heading.

**Comment by shawna-slh** [comment]
In a **coding** curricula, I think it should just be mentioned as something covered elsewhere, yet not covered here.

So, I don't think this learning objective belongs in this curricula:
> Provide heading text that describes the passages entitled by the heading.

That seems like a content development and writing task, not a coding/developing task.

**Comment by sloandr** [comment]
This might be an opportunity to establish a clear and consistent way to signpost to instructors and learners that the concept being discussed is a shared responsibility for accessibility between developers/people writing code and others, and that providing correct markup will on its own not be enough to ensure accessibility.

(Apologies if this is already in hand—this is my first comment and I'm still getting up to speed with what's been done already in the project :) )

**Comment by daniel-montalvo** [comment]
Thanks for this @iadawn 

I have added the following in the teaching ideas about headings, third bullet.
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-headings

It now reads:

"Present examples of headings and reflect with students if they are descriptive of the sections they entitle. **Mention that providing descriptive headings is a shared responsibility among team members: content authors, designers, and developers**. For reference on how to use headings to organize passages of text, see the WAI website tutorials, section Organize Passages of Text."

---

We were discussing with the Task Force that this is part of a higher level issue that we have when it comes to clarifying the scope of this curricula with respect to other curricula we plan to develop in the future. We plan to also add a sentence in the first paragraph of the overview page for this curriculum
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/
that reads:
"This curriculum focuses on markup and coding techniques to develop accessible content. It is designed for teaching developers, with particular focus on front-end developing techniques. **Other curricula will address specific techniques for teaching other roles, for example, content authors, project managers, and accessibility testers**."

**Comment by nitedog** [comment]
See also [side note](https://github.com/w3c/wai-curricula/issues/220#issuecomment-650815748) in #220 on explaining the focused scope of this curriculum in the broader context of other curricula, in addition to cross-linking on a case-by-case basis where needed (like here, in the future when we have the curriculum for content authors).

**Comment by daniel-montalvo** [comment]
There is work to signpost these responsibilities that a developer should be aware of, but that may fall under other roles' responsibility.

We plan to signpost these references in several other modules and topics with the phrasing:

"Summarize related requirements for designers/authors..."

In this specific case, we have it in [Module 1: Structure and Semantics -- Topic: Section Headings](https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#topic-section-headings), learning outcomes, last bullet.

In [Task Force Meeting August 25](https://www.w3.org/2020/08/25-wai-curricula-minutes.html#item01)

Closing this, feel free to reopen if needed.
