### ISSUE TITLE
[Module 1: Page Structure] [Topic: Contents] Element definitions missing from learning outcomes

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#185]
In the Page Contents topic the definitions and usage of elements are explored within the teaching ideas but are not highlighted as learning outcomes.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 

I think this is somehow similar to #183 

Am I correct?

**Comment by daniel-montalvo** [comment]
Added "Describe the purpose and scope of ..." at
https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#topic-sections-of-content

Closing, feel free to reopen if needed.
