### ISSUE TITLE
[Module 1: Page Structure] Quality of writing

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#187]
Flagging this as a question to which I probably know the answer ;)

Is there something about the quality of the writing that needs to be included somewhere? For Page Structure it is relevant for the content of headings. Written content is relevant for paragraphs and lists as well but this doesn't seem to be covered anywhere.

**Comment by daniel-montalvo** [comment]
Hello @iadawn 

I think strategies on how to write content fall more clearly under the content authors curricula. In the case of headings, overlap is more likely to occur, as I [commented in the other issue](https://github.com/w3c/wai-curricula/issues/184#issuecomment-648956076).

This is one of the places where I do see us adding a link for the content author's curricula, once we develop it, as we were discussing in the [Task Force meeting](https://www.w3.org/2020/06/23-wai-curricula-minutes.html#t01) yesterday. But for now, I don't think we should be doing much here.

Anyway, let's see what others think.

**Comment by nitedog** [comment]
See also [side note](https://github.com/w3c/wai-curricula/issues/220#issuecomment-650815748) in #220 on explaining the focused scope of this curriculum in the broader context of other curricula, in addition to cross-linking on a case-by-case basis where needed (like here, in the future when we have the curriculum for content authors).

**Comment by daniel-montalvo** [comment]
Closing, see
[related comment](https://github.com/w3c/wai-curricula/issues/184#issuecomment-680833132)
