### ISSUE TITLE
[Module 1 Page Structure] Is the module title descriptive

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#188]
I don't find the title descriptive enough. The learning outcomes and topics cover more than "Page Structure". Suggestions:
- Page and Content Structure
- Page Structure, Content and Information
- Page
- Web Page

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Thanks for this.

I have now uploaded an updated version of this module. AS we discussed in yesterday's [Task Force Meeting](https://www.w3.org/2020/06/23-wai-curricula-minutes.html#t02) the title of this module and the order of some of its topics has changed. You can see the preview at
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/

There were other comments about some titles not being descriptive enough, so I think this will still remain open for input.
