### ISSUE TITLE
[Module 1 Page Structure] Focus of the learning outcomes on how people with disabilities use page structure

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#189]
After going through the content, the focus of multiple learning outcomes (for the module and specific topics) seems to be more on "**how page structure allows people with disabilities** to orient themselves and navigate within web pages" than what is currently listed ("**how people with disabilities use page structure** to orient themselves and navigate within web pages")

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

This has now been slightly changed.

[Introduction](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#introduction)

* Explain how page structure and navigational mechanisms  allow people with disabilities  to orient themselves and navigate within web pages.

[Learning Outcomes for Module](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#learning-outcomes-for-module).

* Explain how page structure allows people with disabilities to orient themselves and navigate within web pages.

[Learning Outcomes for topic headings](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-headings)

* Describe how headings allow people with disabilities to understand the structure of a page and navigate it by using:

[Learning Outcomes for topic regions](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-page-regions)

* Describe how page regions allow people with disabilities to interact with and move through a web page by using:

Is that what you meant with this issue?

**Comment by carlosapaduarte** [comment]
Yes, @daniel-montalvo 
Looks good to me

**Comment by daniel-montalvo** [comment]
Thanks.

Closing then!
