### ISSUE TITLE
Unit 1 Topic: Scope of Web Accessibility

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#19]
Learning outcomes - remove "ing" endings

**Comment by sharronrush** [comment]
Separate into two sentences: Introduce the definition and scope of web accessibility. Present common terminology using the [Introduction to Web Accessibility] as a resource.

**Comment by sharronrush** [comment]
Teaching Ideas: 
- Define web accessibility as the ability for people with disabilities to use web content, tools, and technology equally.

This idea should emphasize the fact that the disabling factor is not the person's disability but the lack of good, standards-based design.

**Comment by daniel-montalvo** [comment]
> Separate into two sentences: Introduce the definition and scope of web accessibility. Present common terminology using the [Introduction to Web Accessibility] as a resource.
Dealt with in #14

**Comment by daniel-montalvo** [comment]
> Learning outcomes - remove "ing" endings

Dealt with in #14

**Comment by daniel-montalvo** [comment]
> Separate into two sentences: Introduce the definition and scope of web accessibility. Present common terminology using the [Introduction to Web Accessibility] as a resource.

Dealt with in a new pull request. I will update this when finished.

**Comment by daniel-montalvo** [comment]
> Teaching Ideas:
> 
> * Define web accessibility as the ability for people with disabilities to use web content, tools, and technology equally.
> 
> This idea should emphasize the fact that the disabling factor is not the person's disability but the lack of good, standards-based design.

I'm feeling a new pull request needs to be opened as well for teaching ideas an homework. I will update this when available.

**Comment by daniel-montalvo** [comment]
Addressed in #22. Feel free to reopen if you feel there is more to do here.
