### ISSUE TITLE
[Module 1 Page Structure] Tables are not covered

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#190]
Both the module learning outcomes and the Page Contents topic refer to tables as an example of elements that are covered. However, the teaching ideas do not cover tables.

FWIW, I don't think tables should be covered in this module.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

We made reference to tables as examples of how to structure some pieces of content. but I see your point that this might get a little confusing. Either we explain some bits of how to do it in this module, or we leave it for the dedicated module that we have on tables. I think we should do the latter.


Let's see what others think about this.

**Comment by carlosapaduarte** [comment]
I agree that it's best to leave for the dedicate module.

**Comment by daniel-montalvo** [comment]
Closing this for now, input from others welcome anyway!
