### ISSUE TITLE
[Module 1 Page Structure] Is web page identification and navigation out of scope

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#191]
The main goals of the module mention within page navigation and usage of HTML elements to convey page and content structure.
The last topic seems to be out of scope of this module, by addressing between page navigation and page and content language.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I think this is now addressed with thereorganization of [module 1](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation).

Putting this for further discussion so that everybody else can have a look.
