### ISSUE TITLE
[Module 1 Page Structure] Missing learning outcome on sequence of content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#192]
The sequence of content is an addressed topic, but it is not listed as a learning outcome for the module.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte :

In 
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#learning-outcomes-for-module
we have now a learning outcome along those lines.

• Ensure content follows a meaningful sequence.
