### ISSUE TITLE
[All Modules] Is "Demonstrated completion or courses" a skill

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#193]
I find the presentation of "Demonstrated completion of courses" as a skill to be awkward. I would argue that is not a skill. But even so, shouldn't we leave the decision of it needing to be demonstrated to the entities that will be implementing the module on their courses?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I see your point. For me the focus should be on whether students have (or not) completed courses based on the previous modules, so I don't see an issue removing the "demonstrated" qualifier. 

We should be removing this from all modules, right? I will change the issue title accordingly, but correct me if I am wrong.

**Comment by carlosapaduarte** [comment]
@daniel-montalvo Yes, I agree that we should remove it from the other modules. Just didn't want to repeat the same issue for all modules.

**Comment by daniel-montalvo** [comment]
Done in
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#competencies

and will replicate in others as well.
