### ISSUE TITLE
[Module 1 Page Structure] Missing success criteria 4.1.1

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#194]
I would argue that SC 4.1.1 Parsing should be listed as one of the SC in the "applied expertise" list. It addresses nesting elements according to specifications, which is important for headings, at least.

**Comment by daniel-montalvo** [comment]
Added in 
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#competencies
