### ISSUE TITLE
[Module 1 Page Structure] Learning outcomes for Page Regions topic

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#195]
I believe there are two mismatches between the learning outcomes and the teaching ideas.
1. I think the use of the word "strategies" is too advanced (describing how the features can be used is different from the strategies in which they can be used) and the teaching ideas don't seem to go that far. Additionally, I don't think users interact with regions but with the page or the assistive technology. My suggestion for the first list item would be "Describe how to move to different regions of a web page by using"
2. The last list item is not addressed in the teaching ideas. If it is to be kept, there should be a teaching idea on why it is relevant to label regions and how to do it.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 
I plan to do the follwoing:

Rewrite the learning outcome according to your other suggestion in #189

> * Describe how page regions allow people with disabilities to interact with and move through a web page by using:

Keep region labels and add a teaching idea to support them.

> * Show examples of labels for regions included in headings, or using `aria-label`, or `aria-labelledby`. Explain that page regions need to be labeled to distinguish them from one another when two regions of the same type are used in a web page. For reference on how to label regions, see the WAI website tutorials, [Labelling regions](https://www.w3.org/WAI/tutorials/page-structure/labels/).

**Comment by carlosapaduarte** [comment]
Looks good @daniel-montalvo
