### ISSUE TITLE
[Module 1 Page Structure] Use of the expression "general preference"

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#196]
On several instances, "general preference" is used to refer to the use of native elements instead of aria. Should this be presented as a preference or connected to improved browser/AT support?

**Comment by daniel-montalvo** [comment]
Hey Carlos:

This has now been tweaked.

https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-headings
Teaching ideas, second bullet
"* Explain that headings are organized in a hierarchical structure, i.e., h1 being the first rank and h6 being the last one. Emphasize that native HTML elements are more likely to be supported by browsers and assistive technologies. Show examples of how headings can be nested to entitle different sections and subsections of content. For several examples on how to structure pages using headings, see the WAI website tutorials, section [Headings that Reflect the Page Organization](https://www.w3.org/WAI/tutorials/page-structure/headings/#headings-that-reflect-the-page-organization)".

https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-page-regions

Teaching ideas, fourth bullet.
"* Show examples of different page layouts, and their markup of the header, navigation, main content, and footer regions. Emphasize that native HTML elements are more likely to be supported by browsers and assistive technologies. For guidance on how to use HTML5 sections, see the WAI website tutorials, [Regions](https://www.w3.org/WAI/tutorials/page-structure/regions/)".
