### ISSUE TITLE
[Module 1 Page Structure] Interact with headings

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#198]
The expression "interact with headings" is used in the learning outcomes for the Headings topic. I would prefer "browse headings" or "navigate to headings" instead. Users will interact with the page or the assistive technology to achieve such goals.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

In
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-headings
This is now changed to:

• Describe how headings allow people with disabilities to understand the structure of a page and navigate it by using:
