### ISSUE TITLE
[Module 1 Page Structure] Included in headings

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#199]
The last list item for the teaching ideas for the Headings topic uses the expression "texts that are included in headings". Wouldn't it be more inclusive to refer just to headings ("Present examples of headings and reflect with students if they are descriptive of the sections they entitle") given that headings may be composed of more than just text?

**Comment by daniel-montalvo** [comment]
This entire learning outcome has now been removed as this curriculum focuses mainly in markup and code techniques.
