### ISSUE TITLE
Open question on relevance

### ISSUE THREAD

**Issue by notabene** [w3c/wai-curricula#2]
First of all this in no way means that I'm against the idea ;)

I'm just wondering if this is still relevant. Most companies already have trainings in place or resort to consultancies who can provide the training. So I wonder whether it's relevant to invest energy on this part of EO activity or whether the energy would not be more useful elsewhere (eg. videos or making our resources more well-known).

It's really an open question, asked in good faith.

**Comment by nitedog** [comment]
Thank you for this candid question @notabene - totally fine to question the value of any work.

My personal opinion is that I strongly disagree with your statement that most companies have training in place. Maybe some larger corporate companies but even there hardly "most". Especially if we take the international perspective and countries that are only recently starting with accessibility. This work should help more organizations, universities, and other institutions to provide training, and to promote better quality across training offered by different organizations (see the [audiences and use cases](https://www.w3.org/WAI/EO/wiki/WAI_Curricula_(WAI-Guide)#Audience)).

**Comment by notabene** [comment]
Fair enough, I may be very biased ;)
(Thus closing the issue)
