### ISSUE TITLE
Unit 2: Intro and Learning Outcomes

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#20]
Suggest to break up long sentence as follows:
This unit builds on the previous unit “What is Web Accessibility.” It explores assistive technologies, adaptive strategies, and accessible design principles in more detail. As well students will consider the inter-dependencies between these components.

Learning Outcomes:
Again, suggest wording should be that the outcome is" 
Understanding **of**
-or- 
Understand

**Comment by daniel-montalvo** [comment]
> Suggest to break up long sentence as follows:
> This unit builds on the previous unit “What is Web Accessibility.” It explores assistive technologies, adaptive strategies, and accessible design principles in more detail. As well students will consider the inter-dependencies between these components.

This will be addressed in a separate pull request. Updated when available.

> Learning Outcomes:
> Again, suggest wording should be that the outcome is"
> Understanding **of**
> -or-
> Understand

#14

**Comment by daniel-montalvo** [comment]
Addressed in #22. Feel free to reopen if you feel there is more to do here.
