### ISSUE TITLE
[Module 1 Page Structure] Teaching ideas for the Page Contents topic

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#200]
In this section the terms "how to code the element" and "how to use the element" seem to be used interchangeably. It would be better if we used one term consistently.

**Comment by daniel-montalvo** [comment]
I have taken a pass on this and should be now corrected. It may take a few minutes for Netlify to deploy the changes.

https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-page-contents
