### ISSUE TITLE
[Module 1 Page Structure] Learning outcomes for Meta Information topic

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#201]
The first learning outcome seems to include two outcomes: knowing how to mark up a title, and knowing how to write a descriptive title. I think it would be better to split them
- Mark up page titles with the `title` element
- Write page titles that describe the contents of the page

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I have now included titles and language of page in a new topic called [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation), as discussed in the [Task Force Meeting](https://www.w3.org/2020/06/23-wai-curricula-minutes.html#t02)

* Describe mechanisms to orient, navigate, and find content within web pages using:
  * Page titles.
  * Page language.
  * Content language.
  * Search functions.
  * Site maps.
  * Breadcrumb trails.

**Comment by carlosapaduarte** [comment]
@daniel-montalvo To be honest, I'm still having trouble considering "page language" and "content language" as "mechanisms to orient, navigate and find content"

**Comment by nitedog** [comment]
I think page language and language of parts is essential for understanding the content, which is part of orientation. I think they are fine under this topic but maybe deserve their own learning outcome with a clearer lead-in?

**Comment by daniel-montalvo** [comment]
This has now evolved into

> Topic: Page structure
> 
> Learning outcomes
> 
> * mark up page titles to allow people to identify different web pages
> ...
> * identify the existence of requirements for authors to write meaningful page titles
> * identify the existence of requirements for designers to create designs for different viewport sizes

Requirements for writing page titles are signposted here, because they fall more under the role of author. We are leaning towards focusing on the specific tasks that developers perform, and leaving others for future curricula on the particular role.
