### ISSUE TITLE
[Module 1 Page Structure] Skip to main content link

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#202]
Shouldn't this module address the use of the skip to main content link, i.e., G1 [1]

[1] https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html

**Comment by daniel-montalvo** [comment]
In [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation) we have:

Learning outcome: 
* Code mechanisms to bypass blocks of content repeated on multiple pages.


Teaching Idea

* Demonstrate use of HTML links that allow to bypass blocks of content that repeats on multiple pages. Explain that keyboard-only users and users with motor disabilities rely on them to jump to the specific content of a web page, or to skip large blocks of navigation. For reference on how to code such links, see technique [G1: Adding a link at the top of each page that goes directly to the main content area
](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html).

Now we point to the technique you mention instead to jus the SC.

Do you think skip to main content link is now better addressed?

**Comment by carlosapaduarte** [comment]
Looks good, @daniel-montalvo

**Comment by daniel-montalvo** [comment]
Thanks.

Closing then.
