### ISSUE TITLE
[Module 2 Navigation and Menus] Learning outcomes for module

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#203]
1. "Structure navigational mechanisms" is unclear. After reading through the module I'm not sure what exactly is this goal.
2. The last item in the list is ambiguous (is it the student or the page/navigation that indicates where the user is and allows for consistent navigation). Suggestion: "Build navigational mechanisms that indicate where the users are and allow for consistent navigation."

**Comment by daniel-montalvo** [comment]
We have worked on this topic, it now covers

* menu structure -- referring back a little to the previous module
* menu styling -- conventions for developers to code menus
* flyout menus -- dynamic functionality
* application menus -- warning that there needs to be a compelling use case to use them

https://deploy-preview-240--wai-curricula.netlify.app/curricula/developing-accessible-content/navigational-menus/
