### ISSUE TITLE
[Module 2 Navigation and Menus] Order of teaching ideas for topic Multiple Ways of Navigation

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#206]
The first item on the list should be moved to the end to be consistent with the learning outcomes for the same topic

**Comment by daniel-montalvo** [comment]
Done in https://github.com/w3c/wai-curricula/commit/27a5680ca574852dda4dc290ce4888983e22e949#diff-c190770c18d5acb3978e1723bda86c82
