### ISSUE TITLE
[Module 2 Navigation and Menus] Difference between menu and sitemap

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#207]
When mentioning sitemaps in the topic ideas we could include an explanation of the difference between a sitemap and a menu

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Sitemaps are now in Module 1, and menus will have its own module. I will leave this open for now and work on how to differentiate them better. Any suggestions are welcome.
