### ISSUE TITLE
[Module 1 Structure, Semantics, and Navigation] Multiple types of breadcrumbs

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#208]
When presenting breadcrumbs in the learning topics, only one of one their usages is presented in its definition (a way for users to keep track of the hierarchical structure). But breadcrumbs can also be a representation of the path a user took to reach a web page.

**Comment by daniel-montalvo** [comment]
This now belongs to module 1 according to the structure discussed in our [Task Force Meeting](https://www.w3.org/2020/06/23-wai-curricula-minutes.html#t02).

I have reworded this entire topic, now called Navigation and Orientation, and now the teaching idea dealing with breadcrumb trails is combined with the other navigational mechanisms, as we have had comments that teaching all of them one by one may be a bit dry for a developer. The teaching idea now reads:

* Show examples of different mechanisms to orient, navigate, and find content within web pages, such as search functions, sitemaps, or breadcrumb trails. For references on how to build mechanisms that help people orient, navigate, and find content within pages, see techniques [G161: Providing a search function to help users locate content](https://www.w3.org/WAI/WCAG21/Techniques/general/G161.html),  [G63: Providing a site map](https://www.w3.org/WAI/WCAG21/Techniques/general/G63), and [G65: Providing a breadcrumb trail](https://www.w3.org/WAI/WCAG21/Techniques/general/G65).

We no longer present the definition of these mechanisms, but invite instructors to show them in action. 

What do you think about this change?

**Comment by carlosapaduarte** [comment]
I think that works, @daniel-montalvo (and solves the issue)

**Comment by daniel-montalvo** [comment]
Thanks.

Closing then!
