### ISSUE TITLE
Unit 2: Topic: Diverse Abilities, Tools, and Strategies

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#21]
Shorten and change the order of the sentences as follows:
Introduce the wide range of people with disabilities. Explain the wide range of abilities, needs, and preferences within different groups. Consider various needs of those with auditory, cognitive, neurological, physical, speech, and visual disabilities.

**Comment by sharronrush** [comment]
Learning Outcomes:
- Increase awareness ...
- Understand ... (or Understanding of...)

**Comment by daniel-montalvo** [comment]
> Learning Outcomes:
> 
> * Increase awareness ...
> * Understand ... (or Understanding of...)

#14

**Comment by daniel-montalvo** [comment]
> Shorten and change the order of the sentences as follows:
> Introduce the wide range of people with disabilities. Explain the wide range of abilities, needs, and preferences within different groups. Consider various needs of those with auditory, cognitive, neurological, physical, speech, and visual disabilities.

Will be addressed in a separate pull request. I will update when available.

**Comment by daniel-montalvo** [comment]
Addressed in #22. Feel free to reopen if you feel there is more to do here.
