### ISSUE TITLE
[Module 3 Images and Graphics] CSS as required competencies and resource

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#211]
Given the scope of the materials in this module, I would suggest adding CSS as:
- required skill for students (basic knowledge of)
- required skill for instructors (applied expertise in teaching)
- teaching resource

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

Done in 
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics

Feel free to reopen if needed.
