### ISSUE TITLE
[Module 3 Images and Graphics] Complex images

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#212]
Complex images are presented as images that cannot be expressed in a short phrase. Should we mention that charts are, usually, conveyable as tables?

**Comment by daniel-montalvo** [comment]
I have tweaked this teaching idea.

* I have tried to address your above concern.
* I have also added a remark that providing image descriptions is a shared responsibility among different team members, as per our [Task Force Meeting discussion](https://www.w3.org/2020/06/23-wai-curricula-minutes.html#t01).

It now reads:

> Show examples of complex images, such as graphs, charts, or diagrams. Explain that charts may be described using tables, and other complex images may need its own dedicated page with its description. Remember that describing images is a shared responsibility among different team members: content authors, designers, and developers. For reference on complex images, see the WAI website tutorials [Complex Images](https://www.w3.org/WAI/tutorials/images/complex/).

**Comment by carlosapaduarte** [comment]
Looks good @daniel-montalvo

**Comment by daniel-montalvo** [comment]
Thanks!
