### ISSUE TITLE
[Module 3 Images and Graphics] <picture> element

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#213]
I found no reference to the `<picture>` element in this module. It is being "promoted" by many web developers, so I expect to see some increase in its usage. If the `img` is marked appropriately (i.e. it has an alt) then the `picture` element will be accessible to screen readers also. Would it be appropriate to add a mention to it?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

Now included in https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics

Feel free to reopen if needed.
