### ISSUE TITLE
[Module 3 Images and Graphics] longdesc

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#214]
Browser support for longdesc is not uniform. It's not clear how long it will be part of the HTML spec. Do we want to include it?

**Comment by daniel-montalvo** [comment]
I don't feel strongly about this one, but I mildly think we should keep it. I do see some screen readers have dedicated keystrokes to access information contained in the `longdesc` attribute. I guess it could be argued that `longdesc` has more support from ATs than it has (or may have in the future) from browsers.

Also, we are currently pointing to the resource [Complex images](https://www.w3.org/WAI/tutorials/images/complex/), which does include `longdesc`. It would be odd from my perspective that we point to that resource without mentioning `longdesc`.

Let's see what others think about it.

**Comment by nitedog** [comment]
It could be kept with a brief mention/note that it used in specific contexts (I think some e-learning platforms and digital publishing tools use it fairly strongly).

**Comment by daniel-montalvo** [comment]
This has been now added under learning outcomes of topic [Complex Images](https://wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics/#topic-complex-images).
