### ISSUE TITLE
[all] Add overall title in h1

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#215]
e.g.:
> **Module 1: Page Structure**
_in Curricula on Web Accessibility, Developing Accessible Content_

or:
> **Module 1: Page Structure**
_in Developing Accessible Content in Curricula on Web Accessibility_

I'll check how we've done that in other "resource suites" -- I just wanted to add the issue now so we don't forget.

*** 

following proposal in https://github.com/w3c/wai-curricula/issues/215#issuecomment-773401261:

Hidde to do: 

* [ ] implement as above
* [ ] add it to docs

@slhenry  to do (at any point): 

* [ ] update existing pages that use `resource.ref` to use `parent_in_h1`

**Comment by nitedog** [comment]
Please also provide the coding instructions for these styles.

**Comment by shawna-slh** [comment]
Hi @daniel-montalvo Thanks for the e-mail ping on this.

I think we'll need additional code if we want two levels of parent pages listed, as above. Current code only adds one parent, and I don't think it's set up to handle two levels of parents. Also, I think it currently uses full parent title, and I think we'd want this one to use "nav_title" (that is, "Curricula on Web Accessibility" rather than "Curricula on Web Accessibility: A Framework to Build Your Own Courses").

fyi:

Adding this to the meta data:
> resource:
>   ref: /curricula/

Results in:
> in Curricula on Web Accessibility: A Framework to Build Your Own Courses

As done in: [pull request 1](https://github.com/w3c/wai-curricula/pull/246/files) , [preview 1](https://deploy-preview-246--wai-curricula.netlify.app/curricula/developing-accessible-content/custom-widgets/)

Adding this to the meta data:
> resource:
>   ref: /curricula/developing-accessible-content/

Results in:
> in [Draft] Developing Accessible Content

As done in: [pull request 2](https://github.com/w3c/wai-curricula/pull/247/files) , [preview 2](https://deploy-preview-247--wai-curricula.netlify.app/curricula/developing-accessible-content/custom-widgets/)

**Comment by hidde** [comment]
I have submitted a [PR for the WAI website theme](https://github.com/w3c/wai-website-theme/pull/16) to allow for: 

- multiple reference parents (can be added as a YAML list)
- prefer nav title to page title (it will use nav if it exists, and fall back to page if not)

**Comment by hidde** [comment]
@daniel-montalvo I just merged this in; if you get the latest of the `wai-website-theme` submodule in this repo, you should be able to add multiple refs to these pages.

**Comment by hidde** [comment]
Hi @daniel-montalvo,

As a headsup, @slhenry and @nitedog have asked me to revert this change, I just did in https://github.com/w3c/wai-website-theme/commit/5be873ff25346abb97214e2492acca01298ac161, so we now display full page title as we did before.

**Comment by shawna-slh** [comment]
Hi @daniel-montalvo

I'm not seeing this implemented in the Developer Modules for publication.

Is this ready to implement, or do you have additional questions?

**Comment by daniel-montalvo** [comment]
> Hi @daniel-montalvo
> 
> I'm not seeing this implemented in the Developer Modules for publication.
> 
> Is this ready to implement, or do you have additional questions?

We were discussing ways to include the two upper levels we have in the curricula. For a module page we would have had:

Module 1: Page Structure
in
Developer Modules
in
Curricula on Web Accessibility

But apparently this change was reverted as @hidde  tells in 
https://github.com/w3c/wai-curricula/issues/215#issuecomment-719430879

What we could do now:

 - Modules pages point to overview of their corresponding part.
     Module 1: Page Structure,
     in
     Developer Modules
- Overview pages point to opening page
    Developer Modules
    in
    Curricula on Web Accessibility

**Comment by hidde** [comment]
It was implemented as “Allow multiple resource refs, prefer nav title" (see explanation in https://github.com/w3c/wai-website-theme/pull/16). @slhenry and @nitedog asked me to revert, which I have done.

If we want to address this at the WAI Website Theme level, which I would recommend, so that:

* other parts of the site can use the same pattern for the same problem and, with that, 
* users get a more consistent site

please let me know how you want it. This could be (the same as in https://github.com/w3c/wai-website-theme/pull/16, or in a different way. In any case, I would recommend to do this in a way that is not specific to the problem at hand (for the reasons listed above).

**Comment by shawna-slh** [comment]
Hi @hidde . To be clear, we wanted only this part reverted:
> It is now updated to use the nav title instead, falling back to page title if there is no nav title set.

So that it would not change all the other places that we have already used this throughout the site.

We wanted the default to stay as it is -- using the (full) title -- and for there to be _**options**_ to use nav_title instead, for one or both levels.

Is that implemented and documented? Is it in a preview or somewhere where we can see it? I'm guessing we want “in” at the beginning, then just a comma between them (and not 2 “in”s) – although I could pretty easily be talked out of that. :-) Definitely both on the same line.

> **Page Title**
> _in Parent Page Title, Grandparent Page Title_

e.g., using parent title (full and nav are the same afaik) and grandparent nav_title:
> **Module 2: Menus**
> _in Developer Modules, Curricula on Web Accessibility_

**Comment by hidde** [comment]
> So that it would not change all the other places that we have already used this throughout the site.

I think we need something that _does_ also apply to all other places, because we're building it into the code that applies everywhere. 

Rather than introducing a new prop like `titleWeNeedInTheJanuary2021curricula` (exaggerated :-) ), which would become confusing when it exists beyond the page we'd use it in right now, I'd recommend we try and ensure  `navTitle` works as “a shorter and preferred way to refer to a page”. I think it works (or can work) in every place we use it, so that it can be a good default.

It sounds like you'd propose something like `useNavTitleAsTitle` (which can be `true` or `false`) to be able to tweak per site whether we want to prefer the nav title. That level of tweakability makes (1) the set of possible settings of WAI Website pages and (2) the templates more complex. Again, I'm not sure if it's worth it in the long term. I would recommend picking a reasonable default, and re-revert the solution we built in October.

> Is that implemented and documented? Is it in a preview or somewhere where we can see it? I'm guessing we want “in” at the beginning, then just a comma between them (and not 2 “in”s) – although I could pretty easily be talked out of that. :-) Definitely both on the same line.

Yes, agreed this makes most sense, and just for the record, this ('in' at the start and comma in between if needed) was exactly how it was implemented in https://github.com/w3c/wai-website-theme/pull/16.

**Comment by nitedog** [comment]
I think we agreed that we do not want to change the functionality on any of the existing pages, and that we have slightly different requirements for this particular resource only. Let's map out these exact requirements when we meet on Thursday, while ensuring backward compatibility.

**Comment by nitedog** [comment]
After speaking with @hidde, this is the solution he proposes:

1. current behavior will remain unchanged: using "ref: url" will add sub-title "in ..." using the full title of the page referenced via url
2. alternative format for the "ref" directive is to provide multiple urls, each with a flag if the full or short (nav) title should be used

Example:

> resource:
>  - ref:
>    - url: /dir/sub-dir/page1/
>    - title: long
>    - url: /dir/sub-dir/page2/
>    - title: short

This would generate the sub-title: "in page1-full-title, page2-short-title".

(note the comma "," as separator between the titles)

@daniel-montalvo @slhenry please confirm that this addresses your requirements too.

**Comment by shawna-slh** [comment]
Yes, that was what I understood we wanted to do.

Three comments:

1. Please confirm that we can also **choose** to use the nav_title when there is only one-level parent (though it's full title by default / if not specified). e.g.,:

> resource:
>  - ref:
>    - url: /dir/
>    - title: short

2. [minor] instead of "title: long"and "title: short" why not "title: full"and "title: nav" or "title: default"and "title: nav" 

3. [feel free to ignore - I'm just wrenching like SAZ does:-] We actually have 3 versions of the title (per [Frontmatter](https://wai-website-theme.netlify.app/writing/frontmatter/#title)). While we're updating this, do we want to go ahead and enable the option to use "title: html"? (I don't see that we'd want to use that right now, although who knows about the future...)

**Comment by nitedog** [comment]
1. that was my understanding, @hidde please confirm
2. I think @hidde can use any labels, I made these up
3. I don't understand what that third option does?

**Comment by shawna-slh** [comment]
> I don't understand what that third option does?

Currently, our frontmatter/meta "title" cannot include HTML markup. It's used for "title" in the resulting HTML meta, and for the H1. For some resources, we want some HTML markup in the page's H1, for example, `<code>` or `<br>`. If we were to included this as an option for the resource parent listing, then we could choose the HTML version , which is "title_html" in Frontmatter.

That is, then an editor could choose to list the parent page with any one of these three options from [Frontmatter](https://wai-website-theme.netlify.app/writing/frontmatter/#title):
* title
* nav_title
* title_html

**Comment by nitedog** [comment]
Makes sense, I believe in the magic powers of @hidde to make this happen! :-)

**Comment by hidde** [comment]
Thanks all for taking the time to tweak what this front matter would ideally work like! For the record, the solution I proposed today is not ideal and more complex, both in code and in mental load for future maintainers; I would only recommend it if we are absolutely sure that we need this level of flexibility. 

Taking into account previous comments, this could be implemented:

If you would want to list just one parent page with full name:

```yaml
ref: [uri of that page]`
```

(this is how it currently works)

If you want to list multiple parent pages or one with control over what gets displayed: 

```yaml
ref: 
  - url: [uri of that page]
    title: [title | nav_title | title_html]
  - url: [uri of another page]
    title: [title | nav_title | title_html]
  - url: [uri of yet another page]
    title: [title | nav_title | title_html]
```

So that you can choose to display the `title`, or the `nav_title` or the `title_htmll` value.

If it is needed, we could also allow for a string as the value for `title` so that you could fully control how it gets displayed. An example with all of that:

```yaml
ref: 
  - url: /atag/at/a/glance
    title: title
  - url: /wcag/at/a/glance
    title: nav_title
  - url: /uaag/at/a/glance
    title: "This link text is different from any of the front matter on the UAAG page"
```

**Comment by shawna-slh** [comment]
> If it is needed, we could also allow for a string as the value for title so that you could fully control how it gets displayed.

Guess what -- I just discovered such a use case:  the Perspectives Videos sub-pages, where EOWG wants the parent page listed in a different way than is in the title or the nav_title (or the title_html) -- because of context.

So, yes, I support enabling a string (ideally that can include HTML markup, though I don't know that we'll need to).

<hr>

And, to make things even more complicated, we have two "refs", afaik.

1. this one for adding parent page in a sub-page's h1. indented under "resource"
> resource:
>   &nbsp;&nbsp;&nbsp;ref: /path/of/parent/

That's not in the Frontmatter documentation, afaik, so we need to add it.

2. left aligned
> ref: /path/to/page/

From [frontmatter](https://wai-website-theme.netlify.app/writing/frontmatter/#ref):
> "The unique identifier (“reference”) of a page. It uses the permalink of the English version of the page and is used (among other things) to identify the set of translations of a page."

I don't know if there's anything reasonable to do about that now -- without causing a whole lot of work to figure out where they're used and changing them... Or, maybe we "bite the bullet" and say we're going to change how we do add parent page titles to sub-page's h1s (using something other than duplicate "ref") and we'll have to change all the pages that are doing in the old way.

In any case, we'll also need to confirm and document what we should do for translations...

sigh! Let's talk Wed after eo-plan or Thur.

**Comment by hidde** [comment]
> Guess what -- I just discovered such a use case: the Perspectives Videos sub-pages, where EOWG wants the parent page listed in a different way than is in the title or the nav_title (or the title_html) -- because of context.

Yay! 

> And, to make things even more complicated, we have two "refs", afaik.

Ah yes, you're right, what we're talking about here is the `ref` that falls under 'resource', as the main 'ref' is how to identify the page. 

So I guess “url” is not the right name, as a ref could be something else, it is only an uri by convention. 

```yaml
ref: /identifier/for/this/page
resource:
  ref: 
    - url: /atag/at/a/glance
      title: title
    - url: /wcag/at/a/glance
      title: nav_title
    - url: /uaag/at/a/glance
      title: "This link text is different from any of the front matter on the UAAG page" 
```

Let's chat about it more tomorrow or Thursday.

**Comment by hidde** [comment]
Discussed: 

If you want to have the default behavior, that displays a page's parent underneath the title, you can pass a string in (the optional attribute) `ref`, we currently do:

```yaml
resource:
  ref: /some/ref    # uses the page's ref value
```

we would change it to an (optional) setting called `display_parent`:

```yaml
parent_in_h1: /atag/at/a/glance     # uses the page's ref value
```

If you want to diverge from (1) displaying the direct parent page, (2) displaying it with its own title, you can pass an object. It would work for multiple or just a single link. 

```yaml
parent_in_h1: 
  - ref: /atag/at/a/glance
    name: title  # use the page's title value
  - ref: /wcag/at/a/glance
    name: nav_title   # use the page's nav_title value
  - ref: /wcag/at/a/glance
    name: title_html   # use the page's title_html value
  - ref: /uaag/at/a/glance
    name: "This link text is different from any of the front matter on the UAAG page"  # name it any way you like
```

**Comment by nitedog** [comment]
@slhenry @hidde @daniel-montalvo just to confirm the *output* -- as I understand, the series of titles in the H1 will be preceded with the word "in" and separated by a comma "," each.

It would generate the following H1:

```yaml
Page_Title in Parent1_Title, Parent2_Title, Parent3_Title ...
```

**Comment by hidde** [comment]
Agreed, with the exception that the 'in … ' text is in a `p` underneath the `h1`, as it is in current implementation (makes sense as it isn't really heading text, but also happy to change it people feel strongly).

**Comment by shawna-slh** [comment]
ug. I thought it was part of the h1. I see that it's not.

I actually think that in most cases it is heading text. That is, if you land on a sub-page without context, you kinda need to know the parent page.

For example, we have these pages:
* **Video Captions**
* **Captions/Subtitles**

And it seems the h1 and <title> should include the parent page:
* **Video Captions** in Web Accessibility Perspectives Videos
* **Captions/Subtitles** in Making Audio and Video Media Accessible

/me notes the parent page isn't in the generated HTML <title> either.

I don't know the implications of changing it -- e.g., for translations.

I wonder about now just making the update above to allow different name/strings, and add GitHub issue for later to consider adding it to the <title> and putting it in the h1 ?

**Comment by hidde** [comment]
Ok, will add the text into the `h1` element. Also does more precisely what it says on the tin, if we call the parameter   `parent_in_h1` (emphasis on “in”).

We could do something in the `title`, maybe let's do this in a separate issue.

**Comment by shawna-slh** [comment]
Lookie what I found https://github.com/w3c/wai-website/issues/216 = open issue for the <title> (which I forgot about) (and ignore that I got the H1 info wrong :-/)

**Comment by daniel-montalvo** [comment]
Hey @slhenry 

This is now added, thanks to @hidde 's changes in https://github.com/w3c/wai-website-theme/pull/26

See preview at
https://wai-curricula.netlify.app/curricula

Closing. Feel free to reopen if needed.

**Comment by hidde** [comment]
Hm, looks it is not comma separating as it should. Reopening, will try and add a fix as soon as possible.

**Comment by shawna-slh** [comment]
Hi @daniel-montalvo

For second-level page, I see:
> Foundation Modules
> in Curricula on Web Accessibility: A Framework to Build Your Own Courses

For third-level pages, I see:
>Module 1: What is Web Accessibility
> in Foundation Modules
> in Curricula

(I know Hidde is working on the comma and staying on the same line)

I'm a bit surprised that for the second-level pages you used the long title, and for the third-level pages you used just "Curricula". I though you'd use "Curricula on Web Accessibility" in both places.

I don't feel strongly about using the long title in the second-level pages.
I feel medium about not using just "Curricula" in the third-level pages.

**Comment by hidde** [comment]
Update: the commas are now fixed.

**Comment by daniel-montalvo** [comment]
Hi @slhenry 

> I'm a bit surprised that for the second-level pages you used the long title, and for the third-level pages you used just "Curricula". I though you'd use "Curricula on Web Accessibility" in both places.
> 
> I don't feel strongly about using the long title in the second-level pages.

I think this long title provides more context for those coming to the resource through this overview pages for the different parts.

> I feel medium about not using just "Curricula" in the third-level pages.

I think "Curricula" works well in shortening the heading, and also works well as people getting to these third-level pages will probably be more familiar with the resource than those just staying in the first and second-level overview pages. But will change to "Curricula on Web Accessibility" and will update this comment when it is done.

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

I am closing tis as I think work here is finished.

Feel free to reopen if needed
