### ISSUE TITLE
[Developing overview page] [minor]  - wording clarification

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#217]
> It is designed for developers, with special focus on front-end developing techniques.

"special" has all sorts of connotations. It would be good to change that word. 

Also, the curricula is not "designed for developers" -- it's designed for teaching developers.

Ideas for edits:

* It is designed primarily for teaching front-end developers.
or
* It is designed for teaching developers, with particular focus on front-end developing techniques.
or
* It is designed for teaching developers, particularly front-end developers.

**Comment by daniel-montalvo** [comment]
Hey @slhenry 

Done. See first paragraph at
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/#introduction

This paragraph has now one more sentence that helps clarifying the scope of this curriculum.

Does it look better now?

**Comment by shawna-slh** [comment]
Better.

Suggestion to simply and make more relevant to this developing curricula -- change:
> Other curricula will address specific techniques for teaching other roles, for example, content authors, project managers, and accessibility testers.

to:
> Other curricula addresses teaching designers, content authors, and others.
