### ISSUE TITLE
[C2 Developing-all Modules] Resources listing - not all Perspectives Videos

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#220]
> Teaching Resources
...
>  Web Accessibility Perspectives (videos) — Is a series of 1-minute videos that demonstrate that web accessibility is essential for people with disabilities and useful for all. They show accessibility features, how they impact people with disabilities, and how they benefit everyone in a variety of situations.

-1 for linking to all Perspectives (videos).
Maybe list the specific video(s) relevant to the Module topics. Although, I'm not fully convinced they should be in the Developing curricula at all. One the one hand, this should focus on coding, not additional benefits. On the other hand, it is good in a coding course to *briefly* mention additional benefits, to help motivate them to do it?

If do include, I think should be the lower on the list.

**Comment by daniel-montalvo** [comment]
I think the motivation part is always important, especially for those who are responsible for the coding aspects, who may not be as exposed to these perspectives. Agree that they should be moved to the last position in the list of resources.

**Comment by shawna-slh** [comment]
hey @daniel-montalvo 

I suggest linking to **only the specific individual Perspectives Video(s) that are relevant to the specific topics in that module**, not to the top-level page for all of the Perspectives Videos &mdash; since several are not particularly relevant to that module.

**Comment by nitedog** [comment]
I agree with linking only the most relevant videos.

Side note: We have multiple scoping issues, that are in some ways conceptually related -- this curriculum focuses only on the developer tasks but we need to somehow acknowledge that there are other related tasks (eg. designers). Similarly, we focus only on the technical aspects but need to somehow acknowledge that there are other aspects (eg. motivation, empathy, business benefits etc.). We need a good way to declare the specific scope of this curriculum in the context of other parts. I can explain more by phone.

**Comment by daniel-montalvo** [comment]
Will make a proposal on this one.

**Comment by daniel-montalvo** [comment]
We now have individual references to relevant perspective videos. Currently we mention:

* [Module 1: Page Structure](https://wai-curricula.netlify.app/curricula/developer-modules/page-structure/#teaching-resources) -- "Text to Speech" and "Clear Layout and Design"
* [Module 2: Menus](https://wai-curricula.netlify.app/curricula/developer-modules/menus/#teaching-resources) -- "Keyboard Compatibility"
* [Module 3: Images](https://wai-curricula.netlify.app/curricula/developer-modules/images/#teaching-resources) -- "Video Captions"
* [Module 4: Tables](https://wai-curricula.netlify.app/curricula/developer-modules/tables/#teaching-resources) -- "Text to Speech" and "Clear Layout and Design"
* [Module 5: Forms](https://wai-curricula.netlify.app/curricula/developer-modules/forms/#teaching-resources) -- "Notifications and feedback"
* [Module 6: Custom Widgets](https://wai-curricula.netlify.app/curricula/developer-modules/custom-widgets/#teaching-resources) -- "Notifications and Feedback", "Keyboard Compatibility", "Text to Speech", and "Clear layout and Design".
* [Module 7: Rich Applications](https://wai-curricula.netlify.app/curricula/developer-modules/rich-applications/#teaching-resources) -- "Notifications and Feedback", "Keyboard Compatibility", "Text to Speech", and "Clear layout and Design".
