### ISSUE TITLE
[C2 Developing-all Modules] Resources listing - WCAG & ARIA

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#221]
Link to overview page and do not include version numbers.

* WCAG 2.1 -> [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
* WAI ARIA 1.1 -> [WAI-ARIA](https://www.w3.org/WAI/standards-guidelines/aria/)

**Comment by daniel-montalvo** [comment]
Thanks, @slhenry 

This is now done at
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#teaching-resources

I am closing this, feel free to reopen if necessary.
