### ISSUE TITLE
[C2 Developing-all Modules] Resources listing descriptions

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#222]
Reconsider the descriptions. Maybe we want to say something different about these resources in the Developer Curricula? -- that is, point out what is more relevant for developers.

For example, maybe this is not wording to have in the Developer Curricula:
* "and that provides a better user experience for everyone."
* "Following these guidelines will also often make Web content more usable to users in general."

Also, need to edit "A kitchen sink full of technologies for the web." (It uses a regional phrase, and I think incorrectly?)

**Comment by daniel-montalvo** [comment]
Thanks, @slhenry 

I have implemented your suggestions + I have shortened the descriptions for "How people with disabilities use the Web" and the perspectives videos.

At the moment you can see them only at
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#teaching-resources

If you have further suggestions to refine these, please put them here and then we can implement them in the rest of the modules.

**Comment by shawna-slh** [comment]
Better! (I'm not able to make the time now for more suggestions.)
