### ISSUE TITLE
[Module 1] Survey comments from Laura.

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#223]
* [ ] In general, the topics and coding techniques in “Developing Accessible Content” focus heavily on support for screen readers and assistive devices. I wonder if an introduction discussing why coding for screen readers and assistive devices are the primary focus could be helpful. A sentence such as: The coding techniques and page structure that benefit screen reader users are the same techniques that benefit people who have low vision and people with physical and cognitive disabilities, for example.
* [x] Minor contextual comment: Should mark up as a noun have no space? I think yes “markup” should replace “mark up” when used as a noun.
* [ ] I realize that instructors should be experienced in markup techniques but wonder if examples could be included in the curricula document or provide a link to the WAI tutorial under Learning Outcomes.

**Comment by nitedog** [comment]
On use of screen readers, similar to #226, maybe @lakeen can provide specific example of other assistive technologies using coding structures?

**Comment by lakeen** [comment]
@nitedog  - I'm not sure my comment was meant to call out specific assistive technologies but I will mention one that we use at the Library.  We've incorporated ReadSpeaker to Congress.gov bill text and bill summaries and Loc.gov articles and essays.  Incorporation of this app benefits people with low-vision, cognitive disabilities, ESL, and the blind who are visiting our reading rooms and using our sites.  This tool also benefits busy people who want to download the text of the bill in audio form to listen as they drive or accomplish other tasks.

Assistive technologies as well as technologies yet to be developed depend on structural well defined apis to work well.  I believe I was commenting on the heavy use of screen readers/screen reader users.

**Comment by nitedog** [comment]
Thanks @lakeen, I fully agree that we need to address more types of assistive technologies. The issue is that when we are talking about coding structure, screen readers is one of the most apparent examples. To me, ReadSpeaker is a browser-based screen reader but maybe the term "screen reader" is too much associated with people who are blind only? The other term could be "text-to-speech" but this may be too generic and vague? What type of assistive technology would you categorize ReadSpeaker into?

**Comment by lakeen** [comment]
@nitedog  I agree that ReadSpeaker is a browser-based screen reader but also offers features for sighted users such as text highlighting and enlargement as well as downloadable audio files so the term screen reader is too limiting IMO.  I'm wondering if we can use the term assistive technologies to cover every possibility.

**Comment by daniel-montalvo** [comment]
We now have:  "voice commands, keystrokes, and gestures provided by assistive and mainstream technologies"

With this we try to cover not only screen readers, but also other types of assistive technologies and different ways to interact with such technologies (commands, keystrokes, or gestrues).

Closing, feel free to reopen if needed.
