### ISSUE TITLE
[Modules 1 and 2] comments from Shadi

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#224]
From Shadi:

# Topic: Multiple Ways of Navigation
- [x] Using "navigate across web pages" rather than "across websites" used earlier. Not sure which one is more correct but need to decide and be consistent.
- [x] "Provide mechanisms to bypass blocks of content using HTML links" - think can replace "using HTML links" with "repeated on multiple pages"
- [x] "Provide examples of HTML links ..." comes first but it is the latter learning outcome - mildly suggest to keep the same order in the teaching ideas
- [x] "Provide examples of HTML links that allow to bypass blocks of content" could be "Demonstrate different mechanisms to allow users to bypass blocks of content" or such ("provide" seems a little awkward here)
- [ ] "Invite students to explore search functions" - I think most students (ie. developers) know what a search function is. This teaching idea needs to be made more appealing but not sure how.
- [x] I think your definition of primary and secondary navigational menus may not be generalizable. Not sure why this definition is important. Also this teaching idea does not seem appealing to developers - what are they supposed to learn?
- [x] Seems that this entire topic can be boiled down to "people navigate differently". It seems more tangible for UX/IA designers than for content developers? Only "bypass blocks" seems more appealing to developers here.

# Topic: Static Navigational Mechanisms
- [x] The topic title doesn't really click with me but do not have an immediate suggestion.
- [x] "Mark up navigational sections using headings and/or the nav element" - add "HTML" in front of "nav element" for consistency.
- [x] "Label navigational items in a web page using link text and/or the elements aria-label or aria-labelledby" - these are ARIA roles not elements
- [ ] Using "navigational items", elsewhere also "navigational mechanisms" and "navigational sections" - are these all the same thing or different? Confusing.
- [ ] Seems this "Label navigational items ..." and the "Markup navigational sections ..." belong together or at least next to each other?

# Topic: Dynamic Navigational Mechanisms
- [ ] "Convey the hierarchical relationship ..." also applies to static menus. This is more about nested menus. It seems the topic categorization is a little limiting here.
- [ ] Not sure if the explanations of "true" and "false" in the teaching ideas are necessary - think most developers would get this

# Topic: Meta Information for a Navigational Mechanism
- [ ] Topic title definitely does not make sense. For example, I would not recognize focus order "meta information".
- [ ] Seems that much of this topic is about orientation (visual and non-visual)?
- [ ] Think aria-current="page" only applies to some types of menus? Maybe better to explain the aria-current attribute more generally, for example for application menus?

**Comment by daniel-montalvo** [comment]
Hey @nitedog 

> # Topic: Multiple Ways of Navigation

Please note that these topic is now under [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation).

> * [x]  Using "navigate across web pages" rather than "across websites" used earlier. Not sure which one is more correct but need to decide and be consistent.

We are now using "across web pages".

> * [x]  "Provide mechanisms to bypass blocks of content using HTML links" - think can replace "using HTML links" with "repeated on multiple pages"

This now reads: "Code mechanisms to bypass blocks of content repeated on multiple pages."

> * [x]  "Provide examples of HTML links ..." comes first but it is the latter learning outcome - mildly suggest to keep the same order in the teaching ideas

Done.

> * [x]  "Provide examples of HTML links that allow to bypass blocks of content" could be "Demonstrate different mechanisms to allow users to bypass blocks of content" or such ("provide" seems a little awkward here)

Done. This has had comments from others as well. It now reads: "Demonstrate use of HTML links that allow to bypass blocks of content that repeats on multiple pages [...]".

> * [x]  "Invite students to explore search functions" - I think most students (ie. developers) know what a search function is. This teaching idea needs to be made more appealing but not sure how.

I have put together in one single teaching idea the navigational mechanisms, and have tried to make it more practical, like showing them in action rather than defining them or explaining them. See last teaching idea at [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation).

> * [ ]  I think your definition of primary and secondary navigational menus may not be generalizable. Not sure why this definition is important. Also this teaching idea does not seem appealing to developers - what are they supposed to learn?

Will be dealing with this in module 2. And will be removing the idea of primary and secondary menus. Instead, I will be using main menu and other menus, as the concept of main menu seems much more broadly understood.

> * [x]  Seems that this entire topic can be boiled down to "people navigate differently". It seems more tangible for UX/IA designers than for content developers? Only "bypass blocks" seems more appealing to developers here.

We have put together contents on this topic with those from what was previously called "Meta Information" in module 1. The new topic is at [Navigation and Orientation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#topic-navigation-and-orientation).

> 
> # Topic: Static Navigational Mechanisms
> * [ ]  The topic title doesn't really click with me but do not have an immediate suggestion.
> * [ ]  "Mark up navigational sections using headings and/or the nav element" - add "HTML" in front of "nav element" for consistency.
> * [ ]  "Label navigational items in a web page using link text and/or the elements aria-label or aria-labelledby" - these are ARIA roles not elements
> * [ ]  Using "navigational items", elsewhere also "navigational mechanisms" and "navigational sections" - are these all the same thing or different? Confusing.
> * [ ]  Seems this "Label navigational items ..." and the "Markup navigational sections ..." belong together or at least next to each other?
> 
> # Topic: Dynamic Navigational Mechanisms
> * [ ]  "Convey the hierarchical relationship ..." also applies to static menus. This is more about nested menus. It seems the topic categorization is a little limiting here.
> * [ ]  Not sure if the explanations of "true" and "false" in the teaching ideas are necessary - think most developers would get this
> 
> # Topic: Meta Information for a Navigational Mechanism
> * [ ]  Topic title definitely does not make sense. For example, I would not recognize focus order "meta information".
> * [ ]  Seems that much of this topic is about orientation (visual and non-visual)?
> * [ ]  Think aria-current="page" only applies to some types of menus? Maybe better to explain the aria-current attribute more generally, for example for application menus?

**Comment by nitedog** [comment]
> We are now using "across web pages"

But now that you combined navigation on individual web pages and across entire websites, I'm not sure this works well. Why not just remove "within web pages" in the 5th learning outcome?

> Demonstrate use of HTML links that allow to bypass blocks of content that repeats on multiple pages

I think "that allow to bypass" is grammatically incorrect. How about removing "that allow"? Also, "blocks of content that repeats" should be "blocks of content that are repeated".

**Comment by daniel-montalvo** [comment]
I think these comments are addressed in the current versions at

https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/

and

https://wai-curricula.netlify.app/curricula/developing-accessible-content/navigational-menus/
