### ISSUE TITLE
[Module 1] [Topic Page Regions] Comments from Donal

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#226]
From Donal:

the learning outcome entitled "Describe strategies to interact with and move to different regions of a web page" is very heavily focussed on those who interact using screen readers. No reference is made to, for example, voice navigation, switch control, or magnification.

In the suggested topics, there is again an emphasis on screen readers with little-to-no mention of other assistive technologies. I would recommend reviewing to ensure that this bias is somewhat reduced.

**Comment by daniel-montalvo** [comment]
> From Donal:
> 
> the learning outcome entitled "Describe strategies to interact with and move to different regions of a web page" is very heavily focussed on those who interact using screen readers. No reference is made to, for example, voice navigation, switch control, or magnification.
> 
> In the suggested topics, there is again an emphasis on screen readers with little-to-no mention of other assistive technologies. I would recommend reviewing to ensure that this bias is somewhat reduced.


Hey @donalfitzpatrick

See my comment at https://github.com/w3c/wai-curricula/issues/227#issuecomment-649712009

I think this issue is somehow related to the other one.

**Comment by nitedog** [comment]
Would be good to gather specific examples of how other assistive technologies make use of the *coding* of page regions (as opposed to visual design, which would be for the designer curriculum to address). Some tools for content adaptation used by people with cognitive and learning disabilities come to mind but it would be important to gather some more examples, and build the text based these examples.

**Comment by daniel-montalvo** [comment]
I have not seen references to regions in the Fusion user guide. I have also not seen any commands or gestures for switch controls to go to next or previous regions. Page regions seem to be used by screen reader users and some extensions like [Landmarks](https://github.com/matatk/landmarks).

I think we could mention these extensions in addition to screen reader keystrokes and advance functionality, but I doubt we should touch upon screen magnification and switch controls here.

**Comment by daniel-montalvo** [comment]
We have tweaked these.

In learning outcomes we have:

> * explain how properly coded page regions can be presented in different ways, including being read aloud using text-to-speech technologies, with custom or without any styling, and in different screen and text sizes.

And in teaching ideas:

> * Demonstrate use of voice commands, keystrokes, and gestures provided by assistive and mainstream technologies to navigate page regions. Explore advanced functionality that some tools provide, such as presenting all page regions in a list or tree where users can select the region they are interested in. Examples of how people with disabilities interact with the Web are provided in [Stories of Web Users](https://www.w3.org/WAI/people-use-web/user-stories/).

I think this bias is reduced now. 

Closing this, feel free to reopen if needed.
