### ISSUE TITLE
[Module 1] [Topic Headings] Survey comments from Donal

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#227]
From Donal:

* [ ] the first learning outcome is again almost exclusively focussed on screen readers and does not take note of other Assistive Technologies.
* [ ] In the second learning outcome, I would recommend adding some text to the effect that the student should also become familiar with the occasions when it is appropriate to use h1-h6, and when to use the ARIA role. This is a crucial competency in my view as the ARIA role is frequently misused and this juncture represents an ideal opportunity for its inclusion.

**Comment by daniel-montalvo** [comment]
Hey @donalfitzpatrick

Thanks very much for your feedback. I am copying your comments here so that we can keep track of the discussion and have others chime in easily.

I am pinging @nitedog  and @carlosapaduarte who have commented on this as well.

I have done the following

> * [ ]  the first learning outcome is again almost exclusively focussed on screen readers and does not take note of other Assistive Technologies.

I have reworded the learning outcomes as follows:

* Describe how headings allow users of the following assistive technologies to understand the structure of a page and navigate it:
  * Screen readers.
  * Screen magnifiers.
  * Switch controls.
  * Voice navigation.

And the teaching ideas as follows:

* Demonstrate use of commands, keystrokes, or gestures of assistive technologies to move to next or previous heading. Explore advanced functionality which presents all headings in a list where users can select the heading they are interested in. For reference on how people with disabilities interact and navigate web pages, see [Stories of Web Users](https://www.w3.org/WAI/people-use-web/user-stories/).

You can see a preview in topics "Page Headings" and "Page Regions" at 
https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/

This is a similar issue to #226 but for regions we do have browser reading functionality, which in my opinion makes things a bit more balanced.

What do you think about these changes?

> * [ ]  In the second learning outcome, I would recommend adding some text to the effect that the student should also become familiar with the occasions when it is appropriate to use h1-h6, and when to use the ARIA role. This is a crucial competency in my view as the ARIA role is frequently misused and this juncture represents an ideal opportunity for its inclusion.

I see use of ARIA headings when it is not possible to use native `h1-h6`.

I included references to ARIA headings to give all the possible ways in which headings could be coded, but I am now leaning to removing references to ARIA headings, as they may be creating more confusion than they are helping.

I do think there is a compelling reason to keep ARIA landmarks for older browsers and assistive technology support, but not very much for ARIA headings. Could you elaborate on other reasons or use cases where ARIA headings could be used that make us keep these references?

**Comment by nitedog** [comment]
1. I'm not sure how headings, from a coding perspective, help users of screen magnification, switch controls, and voice navigation? It doesn't really fit with the teaching idea either. Maybe the visual styling of headings helps these users but this would be for the designer curriculum.

2. I don't think the references to WAI-ARIA should be removed from the second learning outcome. Instead, I suggest a small tweak that would reflect what you say in the second teaching idea, which is that use of native is preferable and WAI-ARIA only if needed. It may be as simple as adding a word or two into the existing learning outcome.

**Comment by daniel-montalvo** [comment]
According to [Fusion Info](https://www.zoomtext.com/fusion-info-en/) 
users of screen magnification could move through headings using dedicated keystrokes. They could have their screen magnifying technology configured so that headings would be spoken and focused, or focused only. So technically we could say they also use keystrokes to move through headings.

I am not quite sure that a user of switch controls have dedicated gestures to go to next and previous heading. I have tried to find examples but I have not been successful at the time. I would not mention switch controls in this section. Rather, I would mention them when talking about meaningful sequence and focus indicators.

**Comment by nitedog** [comment]
I think some screen magnification software have screen reader functionality. From a quick skim, this tool seems to integrate an entire screen reader. I agree that we need to increase the diversity of assistive technologies we refer to but sometimes the choices are limited.

**Comment by daniel-montalvo** [comment]
I think these concerns are addressed at

https://deploy-preview-240--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#topic-section-headings

Closing, feel free to reopen when needed.
