### ISSUE TITLE
Writing Learning Outcomes

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#23]
Several formulas to write learning outcomes:

## Learning Outcomes

Learners should be able to:
- Describe...
- Explain...
- Define

----------------------

## Learning Outcomes

* Describing...
*  Explaining...
* Defining...

---------------

Which one is better? Do you have any strong oppositions to any of the above?

**Comment by eoncins** [comment]
I do prefer the option with "should be able to + infinitive" I think is more user oriented and focused.
