### ISSUE TITLE
[Module 1] Use of Criteria instead of Criterion

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#233]
In the list of required expertise for instructors, several "Success Criterion" are presented as "Success Criteria". The offending ones are: 2.4.5, 3.1.2, 3.2.4 and 4.1.2

**Comment by daniel-montalvo** [comment]
This should now be fixed.

[Module 1](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-Psemantics-and-navigation/)
