### ISSUE TITLE
[Module 1] Meaningfull sequence

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#235]
One of the learning outcomes states "Ensure content follows a meaningful sequence"

I find this to be ambiguous: is the student/developer responsible for deciding what is the meaningful sequence for content presentation, or is the student/developer responsible for marking up content in a way that follows the meaningful sequence that was defined by the content author?

**Comment by daniel-montalvo** [comment]
Good point, @carlosapaduarte, I will reword this according to your suggestion.

 

--

 

Daniel Montalvo

 

Accessibility Education and Training Specialist

W3C/WAI

**Comment by daniel-montalvo** [comment]
Done> Second last bullet at:
https://wai-curricula.netlify.app/curricula/developing-accessible-content/structure-and-semantics/#learning-outcomes-for-module
