### ISSUE TITLE
[Module 3] [Topic Simple Images] comments from Shadi

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#236]
- [ ] Not sure alt-text should be the only technique to be taught. Definitely to be emphasized but I think developers should know that they have different options.
- [ ] While developers do not need to dive deep into the "art of text alternatives", there are basics that they should know - for example putting decorative images in the CSS, ensuring text alternatives for functional images include any textual words in the image etc. This may be another reason to combine this topic with the prior one.

**Comment by eoncins** [comment]
+1

**Comment by daniel-montalvo** [comment]
> * [ ]  Not sure alt-text should be the only technique to be taught. Definitely to be emphasized but I think developers should know that they have different options.

Added in topic simple images, learning outcomes.
https://wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics/#topic-simple-images

> * [ ]  While developers do not need to dive deep into the "art of text alternatives", there are basics that they should know - for example putting decorative images in the CSS, ensuring text alternatives for functional images include any textual words in the image etc. This may be another reason to combine this topic with the prior one.

These are now combined. These hints have been added to teaching ideas for both topics
https://wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics/#topic-simple-images

https://wai-curricula.netlify.app/curricula/developing-accessible-content/images-and-graphics/#topic-functional-images
