### ISSUE TITLE
[all] "Competences" section markup and visual format

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#24]
A few things:
* Conceptually this is not a definition list.
* I don't think we want it to have the visual emphasis of bold and italic.
* I like brackets, yet I don't think they are good here.

Therefore, I suggest simple paragraphs and lists and m-dashes:

> Learners:
> * Basic &mdash; Basic understanding of computers and the Web.

> Instructors:
> * Medium &mdash; Good understanding of how to introduce and integrate accessibility strategies throughout organizational processes.

(Note that above and on some places there will only be a one-item list. Yet in other places there are multiple items -- so I think that's OK.)

**Comment by daniel-montalvo** [comment]
Thanks for this. Pretty straight-forward change, I will deal with it in a separate branch and will update this issue with reference to the pull request.

**Comment by yatil** [comment]
I think they are _description lists_ (HTML5 has redefined `<dl>`s quite significantly). I am unsure of using square brackets do determine the levels. (This change has not yet been made in units 1 and 2.)

I don‘t argue for one approach or the other, just clarifying that it is OK to use it here.

**Comment by daniel-montalvo** [comment]
After receiving some more input for this section in #38 , I have added an introductory paragraph. An example is at https://w3c.github.io/wai-curricula/curricula/1-3/#competences

I feel the need to have a definition/description list there, especially if is going to be a paragraph at the beginning.

@slhenry  do you still feel strongly about not using this list?

**Comment by shawna-slh** [comment]
never felt strongly :-)
