### ISSUE TITLE
[Unit 5]: [Wordsmith]: Change "Crucial" to some synonym

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#27]
In the introduction for [Topic: Planning and Managing Web Accessibility](https://w3c.github.io/wai-curricula/curricula/1-5/#topic-planning-and-managing-web-accessibility) for unit 5 we currently have:
> Refer to the [Planning and Managing Web Accessibility](https://www.w3.org/WAI/planning-and-managing/) resource to select those strategies that best suit the particular business context of learners. Emphasize that it is crucial to have management support and backing to succeed in implementing accessibility.

Crucial is not the right word for this. Acknowledging that having managerial support is important, there might be cases where developers and designers are doing accessibility because they are inclined to do it and possibly managerial staff is not even aware 😂

We need to look for another word that still communicates the convenience of having such managerial support, but that is not as restrictive as "crucial".

Suggestions are:
* Important.
* Relevant.
* Convenient.
* Advisable.

**Comment by yatil** [comment]
> Crucial is not the right word for this. Acknowledging that having managerial support is important, there might be cases where developers and designers are doing accessibility because they are inclined to do it and possibly managerial staff is not even aware 😂

While I agree that such cases exist, they are usually not successful over the long run as staff changes. I think managerial support is essential for the longtime success. 

(So Im leaning to keep as is but also trust the editor to pick something appropriate.)

**Comment by vmmiller** [comment]
I understand Daniel's reasoning and realize that developers and/or designers will of their own initiative work on accessibility.  However, for a long term strategy, implementation and continuity, I think it is really important to have managerial support.  Thus, my preference is to keep "crucial".

**Comment by JenniferChadwick** [comment]
I agree to push for managerial support being recognized as a key part of the success of accessibility initiatives within an organization - even to allow for extra time for staff to explore and test their own code, learnings initiated by the staff.   Other adjectives include essential, critical.  :)

**Comment by hidde** [comment]
Agreed that management support is crucial for long term success, yet not for any accessibilty effort per se, like you say, developers and designers could do things on their own. 

Maybe we could keep “crucial” and add “in the long term” at the end of that sentence, to address this?

**Comment by daniel-montalvo** [comment]
Thanks all!

> Refer to the Planning and Managing Web Accessibility resource to select those strategies that best suit the particular business context of learners. Emphasize that it is crucial to have management support to succeed in long term accessibility implementations.

Might be the one.

**Comment by yatil** [comment]
This has my support.

**Comment by Sylduch-Conseil** [comment]
this last suggestion of @daniel-montalvo works also for me. +1
