### ISSUE TITLE
[Developers] [Module 4 Tabular Information]

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#274]
[ED medium] - Learning Outcomes section - grammar edit: bullet "mark up data and header cells associations explicitly in complex tables", I would change the word "cells" to "cell" (singular).

**Comment by daniel-montalvo** [comment]
Fixed in
https://deploy-preview-273--wai-curricula.netlify.app/curricula/developing-accessible-content/tabular-information/#learning-outcomes-for-module
