### ISSUE TITLE
[Developers] [Module 4 Tabular Information]

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#275]
[ED strong] - Ideas to Assess Knowledge for Module - first bullet needs the following sentence reworked. Does not fit or make sense as is. "Then they are asked how many tables they have found and which their headers are."

**Comment by daniel-montalvo** [comment]
Fixed aat
https://deploy-preview-273--wai-curricula.netlify.com/curricula/developing-accessible-content/tabular-information/#ideas-to-assess-knowledge-for-module
