### ISSUE TITLE
[Unit 5] Case Studies for Accessibility

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#28]
In [Topic: Planning and Managing Web Accessibility](https://w3c.github.io/wai-curricula/curricula/1-5/#topic-planning-and-managing-web-accessibility), we have sentences like:
Learning Outcome:
> * Describe some accessibility case studies from organizations

Teaching Ideas
> * Discuss case studies of organizations that have adopted accessibility. Analyze with students successes and challenges of such cases. See the [Business Case for Digital Accessibility](https://www.w3.org/WAI/business-case/) resource.

Can we point students to the current WAI resources to find such case studies? Are they enough for this purpose?

Is it important to keep this references in the curricula rewording these sentences or should we remove them. It is not an easy thing to find business cases that we can point students to, specially if we want to remain vendor neutral (and we want).

**Comment by yatil** [comment]
I think pointing to the business case is the right way to handle it.

**Comment by JenniferChadwick** [comment]
In full support of sharing case studies if they are available.

**Comment by daniel-montalvo** [comment]
The issue here is what to do when they are not available, which may be the case when we point to the [current resource](https://www.w3.org/WAI/business-case/).

**Comment by SiddharthaGuatama** [comment]
I am uncertain if this has been addressed in its entirety, but when presenting examples of case studies, listing what the pre-determined goals of an instruction or research project as a series of goals may assist others outside a particular field with some direction as to what they should be striving for at that time.

Others may find a project is far more approachable when they see a goal has involved and that approaches and reaches the end.

These are some of the oldest keypoints of instructional design.

**Comment by daniel-montalvo** [comment]
I think it has been addressed with general changes that we have been implementing to this unit based on general improvements to "Teaching Ideas" and "Ideas to Assess Knowledge". Feel free to reopen if necessary and give specifics.
