### ISSUE TITLE
[Overview Page #PR119] tweak intro to better reflect activities more than roles

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#288]
This refers to the introduction text in Pull Request #119, based on a discussion at the [3 November Curricula TF meeting](https://www.w3.org/2020/11/03-wai-curricula-minutes.html):
 - https://deploy-preview-119--wai-curricula.netlify.app/curricula/

Issue: Currently the introduction (and navigation) is very strongly focused on roles. For some, this could be deterring. For example, a UX designer who occasionally codes would not feel connected with a "developer" curriculum.

Proposed solution: Tweak the introduction section, maybe even just the first sentence only, to be clearer that these curricula can be used for different types of teaching (ie. activities) and that it happens to be organized by roles -- these can, however, be combined as needed.

**Comment by daniel-montalvo** [comment]
Work finished. Changed implemented in
https://www.w3.org/WAI/curricula/
