### ISSUE TITLE
[Developer] [Module 7] Focus management

### ISSUE THREAD

**Issue by hidde** [w3c/wai-curricula#299]
Regarding

> code Single Page Applications (SPA) so that the focus is placed at the beginning of the content when new screens are generated, to replicate the behavior of page reloads for assistive technologies

Should we also list other approaches to focus management for page changes, like moving focus to first `h1`?

**Comment by nitedog** [comment]
Good point. Maybe this should be "for example" rather than appearing to be exclusive:

> ensure that the focus is placed appropriately when new screens are generated in Single Page Applications (SPA); for example, so that the focus is placed at the beginning of the content to replicate the behavior of page reloads for assistive technologies

**Comment by hidde** [comment]
Great suggestion. I think the listed solution is the most straightforward (and therefore the best example), “for example” helps clarify there are more ways.

**Comment by daniel-montalvo** [comment]
My experience with moving focus to the first h1 is that it may not have the desired effect in many cases. Some screen readers may not pay attention to that focus placement and would still try to read from the very top of the web/application. In addition, this may interfere with some custom configuration that users may have put in place to have their screen reader read from a specific point of the website or application.

With that being said, I quite like making the actual example a suggestion, without mentioning moving focus to the first h1.

**Comment by daniel-montalvo** [comment]
Proposed:

> * ensure that the focus is placed appropriately when new screens are generated in Single Page Applications (SPA); for example, at the beginning of the content to replicate the behavior of page reloads for assistive technologies

Shortening a bit the learning outcome, as that was getting a bit long.

Closing, feel free to reopen if necessary.

**Comment by hidde** [comment]
Excellent!
