### ISSUE TITLE
[Developer] [Overview page] minor and low text edits

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#301]
**Low - for editors' discretion:**

* "around" -> "for"

> explain accessible markup and coding techniques around:

-> explain accessible markup and coding techniques for:

* change from passive voice to active voice:

> Knowledge of HTML and CSS is also expected.

**Minor:**

*  under "Prerequisites for Students", remove the quote marks around the topics.

**Comment by daniel-montalvo** [comment]
Hey @slhenry 

I took a general pass, see:
https://wai-curricula.netlify.app/curricula/developer-modules/

Closing, Feel free to reopen if you feel your comments have not been addressed.
