### ISSUE TITLE
[Developer] [Overview page] Prerequisites for Students a bit annoying

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#302]
Use case (this is what I did): Read "Students of courses based on this curriculum are expected to have achieved the following learning outcomes from the prior Foundation modules:...". Thought: "Is this the list of all content from the Foundations Modules?" Counted topics here, then opened Foundations page, scrolled down, counted topics there... Thought: "Hum, most but not all, I wonder which are not included... " Started to compare and got a little annoyed with it.

Also thought: the sentence says "achieved the following learning outcomes" but then it lists Topics, not learning outcomes.

< end use case >

I'm happy to help talk through design ideas to provide better user experience...

**Comment by daniel-montalvo** [comment]
Hey @slhenry 

Changed to:

> The developer modules are designed for students who have achieved the learning outcomes from the following subset of Foundation modules:
> 
> ...

Happy to discuss further tweaks (wording or design-related).

**Comment by shawna-slh** [comment]
OK. Thanks!
