### ISSUE TITLE
[Developer] [Overview page] Potential misunderstanding of scope

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#303]
[Medium - editor's discretion]

edit opening sentence from:
> The modules in this curriculum focus on accessible markup and coding techniques.

to something like:
> The developer modules address accessible markup and coding techniques.

Rationale: While I do understand how we are using "curriculum", I think it's likely not to be clear to others. That is, I think, we are saying:
* Foundation Modules is a singular curriculum 
* Developer Modules is a singular curriculum
* and all the Modules together make up the plural Curricula on Web Accessibility

However, if someone just lands on this page first without any context, they could process it as: "... this curriculum focus on accessible markup and coding techniques. ... primarily designed for... front-end developers." and then assume that the whole curricula is just for developers.

Please consider if we need to look at that potential misunderstanding elsewhere, too, e.g.,:
> This curriculum guides the creation of courses that

**Comment by daniel-montalvo** [comment]
> [Medium - editor's discretion]
> 
> edit opening sentence from:
> 
> > The modules in this curriculum focus on accessible markup and coding techniques.
> 
> to something like:
> 
> > The developer modules address accessible markup and coding techniques.
> Rationale: While I do understand how we are using "curriculum", I think it's likely not to be clear to others. That is, I think, we are saying:
> 
> * Foundation Modules is a singular curriculum
> * Developer Modules is a singular curriculum
> * and all the Modules together make up the plural Curricula on Web Accessibility
> 
> However, if someone just lands on this page first without any context, they could process it as: "... this curriculum focus on accessible markup and coding techniques. ... primarily designed for... front-end developers." and then assume that the whole curricula is just for developers.
> 
> Please consider if we need to look at that potential misunderstanding elsewhere, too, e.g.,:
> 
> > This curriculum guides the creation of courses that


Done (replicated where appropriate throughout the page).
See
https://wai-curricula.netlify.app/curricula/developer-modules/

Closing, feel free to reopen if needed.
