### ISSUE TITLE
[all] Do a copy-edit pass for passive voice

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#304]
For example, change:

> Practical &mdash; Students are presented with different types of menus and are asked to code them...

to:

> Practical &mdash; Give students different types of menus and ask students to code them...

**Comment by daniel-montalvo** [comment]
Thanks for this, @slhenry .

Mainly addressed in:
* ec98742ed924f9eaae9a87d5e497919b36b4175a (origin/master, origin/HEAD)
* 7574719f64dfea6987ecbcaff7e5340259343266 (HEAD -> master)
Will be closing tihs once we address some more instances present in learning outcomes.

**Comment by daniel-montalvo** [comment]
Closing as we have already taken a pass (and agreed) on learning outcomes within TF.
https://www.w3.org/2021/01/19-wai-curricula-minutes.html#item01
