### ISSUE TITLE
Ideas for first heading title in overview page

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#316]
Ref:
https://wai-curricula.netlify.app/curricula/#overview

First heading title is "Overview", but didn't click for some.

Some ideas.

- Overview
- Gist
- About this Resource
- About
- What Should I Know?
- What you Should Know
- Outline and Uses
- Essence.

Which of these do you think better communicates what is currently in that section?

Any other thoughts/ideas?

**Comment by shawna-slh** [comment]
brainstorms:
* Using this Curricula
* Using this Resource

**Comment by daniel-montalvo** [comment]
Changed to "Using the Curricula"
https://wai-curricula.netlify.app/curricula/#using-the-curricula
