### ISSUE TITLE
[ED] Throughout - using "and" instead of "or"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#328]
Example sentence (from Module 2: Menus - Topic: Menu Structure):

> Practical - Students identify the regions of the page that contain the menus and mark them up using navigation regions or headings where appropriate. Assess students' use of the HTML element `nav` or headings where appropriate to mark up menus.

Issue: In several places the combination should be "and" rather than "or". In this example, students need to be able to mark up navigation regions *and* headings, rather than *or*. Instructors should also assess both uses. A better phrasing would be:

> Practical - Students identify the regions of the page that contain the menus and mark them up using navigation regions and headings as appropriate. Assess students' use of the HTML element `nav` and headings to mark up menus.

Note the change of "where appropriate" to "as appropriate" and removal of the second instance.

Suggestion: Take another pass, as several of these sentences are being wrongly added in this iteration.

**Comment by daniel-montalvo** [comment]
I have taken a pass on modules 1-5 at
https://github.com/w3c/wai-curricula/pull/334/files/

Not sure if this is what you meant or this is going too far at this stage.

**Comment by nitedog** [comment]
I was mostly referring to the newly made changes but this reads **much** better in my opinion.

PS: I blame @slhenry who made me aware of this grammatical refinement in the past... ;-)
