### ISSUE TITLE
[High] Module 2: Menus - Topic: Application Menus

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#329]
> Show examples of different application menus, such as web application menus, sidebars, or toolbars. Emphasize that application menus are used when desktop functionality is recreated in a web application. Mention that application menus are not advised for navigational menus, toolbars, or sidebars, where navigation using the tab key is more predictable and expected.

Issue: This paragraph seems to contradict itself -- "Show examples of application menus, such as [...] toolbars. [...] Mention that application menus are not advised for [...] toolbars" -- aren't toolbars commonly found in applications, and so often need to be coded as application menus? Also, how do sidebars relate to menus? Maybe we mean horizontal versus vertical menu bars?

Suggestion: Simplify this to something like "Show examples of different application menus. Emphasize that application menus are used when desktop-like functionality is needed, rather than for navigational functionality. Mention that using the tab key with navigational menus is more predictable and expected for navigational purposes."

**Comment by daniel-montalvo** [comment]
Addressed in https://deploy-preview-320--wai-curricula.netlify.app/curricula/developer-modules/menus/#topic-application-menus


Will close when merging.

**Comment by nitedog** [comment]
Change square brackets "[desktop-like]" to round brackets "(desktop-like)".

**Comment by daniel-montalvo** [comment]
Done.
https://wai-curricula.netlify.app/curricula/developer-modules/menus/#topic-application-menus
