### ISSUE TITLE
[High] Module 5: Forms - Topic: Controls and Labels

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#330]
This learning outcome:

> identify situations in which it is necessary to use other techniques to provide labels for form controls, and mark up form controls using the following techniques as appropriate:

Was changed to this:

> identify situations in which it is necessary to have labels for form controls appear only on hover or focus but still have them permanently available for assistive technologies and write markup for such labels using the following techniques as appropriate:

Also this sentence was added later in the "Teaching Ideas for Topic":

> especially for cases where the label is only shown on hover or focus but still needs to be associated for assistive technologies

Issue: Besides making the sentence even longer and more difficult to read, I also feel that adding "labels for form controls appear only on hover or focus but still have them permanently available for assistive technologies" is too specific/situational. It also seems more related to the designer modules then here. Content that appears on hover only is often quite problematic (eg. for people not using a mouse and some types of cognitive and learning disabilities), and this sentence seems to encourage such practice. Moreover, we should probably be speaking of labels and instructions in this module, not of entire content that appears on hover.

Suggestion: Remove this addition, or add it as a "sign-post" -- for example, "students should be able to ... describe shared requirements for designers to ensure that labels that appear on hover are understandable and operable by all users" or such. Also remove the sentence added in the "Teaching Ideas for Topic" section.

**Comment by daniel-montalvo** [comment]
These references have been removed. These are now as they were before.

https://deploy-preview-320--wai-curricula.netlify.app/curricula/developer-modules/forms/#topic-controls-and-labels

Will close when merging.
