### ISSUE TITLE
[Medium] Module 7: Rich Application - Topic: Structure and Relationships

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#331]
> write code for updating applications and dynamically generated content with appropriate markup structures and semantics

Issue: (1) The term "updating applications" is unusual and not used elsewhere. Applications are by design dynamic. Updating applications could be misunderstood to mean updating the version of the application rather than dynamic changes to the content. (2) The sentence has now become quite unwieldy.

Suggestion: Change to something like "ensure that applications and dynamically generated content has appropriate markup structures and semantics".

**Comment by daniel-montalvo** [comment]
Addressed in https://deploy-preview-320--wai-curricula.netlify.app/curricula/developer-modules/rich-applications/#topic-structure-and-relationships

Will close when merging.
