### ISSUE TITLE
[ED] Module 7: Rich Application - Topic: Keyboard and Focus Interactions

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#332]
> whereas [...] is a designer's responsibility

Note several occurrences of this sentence.

Issue: (1) "a designer" sounds too vague and could be anyone. This can be fixed by saying something like "responsibility of *the* designer". Yet more importantly (2), is this really only the responsibility of the designer or rather a shared responsibility?

Suggestion: Change to something like "whereas [...] is a shared responsibility with the designer".

**Comment by daniel-montalvo** [comment]
Addressed in https://deploy-preview-320--wai-curricula.netlify.app/curricula/developer-modules/rich-applications/#topic-keyboard-and-focus-interactions

Will close when merging.

**Comment by nitedog** [comment]
Did you check of other occurrences of this issue?

**Comment by daniel-montalvo** [comment]
I did. There were two occurrences of this phrase.

https://github.com/w3c/wai-curricula/blob/master/content/2-7.md#l164
https://github.com/w3c/wai-curricula/blob/master/content/2-7.md#l165

In other mmodules we do have a slighly different wording to sign-post responsibilities.

https://github.com/w3c/wai-curricula/blob/master/content/2-
https://github.com/w3c/wai-curricula/blob/master/content/2-
https://github.com/w3c/wai-curricula/blob/master/content/2-
https://github.com/w3c/wai-curricula/blob/master/content/2-
https://github.com/w3c/wai-curricula/blob/master/content/2-
https://github.com/w3c/wai-curricula/blob/master/content/2-

**Comment by daniel-montalvo** [comment]
There were two occurrences of this phrase.

* https://github.com/w3c/wai-curricula/blame/master/content/2-7.md#L164
* https://github.com/w3c/wai-curricula/blame/master/content/2-7.md#L165

Other places where we mention these shared responsibilities in teaching ideas are:

* https://github.com/w3c/wai-curricula/blame/master/content/2-1.md#L119
* https://github.com/w3c/wai-curricula/blame/master/content/2-2.md#L147
* https://github.com/w3c/wai-curricula/blame/master/content/2-6.md#L194
* https://github.com/w3c/wai-curricula/blame/master/content/2-6.md#L239

But these do not share the same phrasing you commented in this issue.

Are you suggesting that we harmonize these different approaches?

**Comment by nitedog** [comment]
Thanks for confirming!
