### ISSUE TITLE
Developer Modules - Module 7 links broken?

### ISSUE THREAD

**Issue by S-Bowen** [w3c/wai-curricula#343]
Within the Developer Modules page (https://www.w3.org/WAI/curricula/developer-modules/), it looks like the links to Module 7 are slightly incorrect. 

For context, the link to Module 7 goes to https://www.w3.org/curricula/developer-modules/rich-applications rather than where I think it's meant to go: https://www.w3.org/WAI/curricula/developer-modules/rich-applications

It's not a big problem but I thought you might want to know!

Cheers,
Serena

**Comment by daniel-montalvo** [comment]
Thanks for reporting this  @S-Bowen ,

This should now be fixed
https://www.w3.org/WAI/curricula/developer-modules/
