### ISSUE TITLE
[editor’s discretion] URLs

### ISSUE THREAD

**Issue by yatil** [w3c/wai-curricula#35]
I’m not a big fan of the numeric URLs. Instead of 

```
https://w3c.github.io/wai-curricula/curricula/1-1/
```

I’d like

```
https://w3c.github.io/wai-curricula/curricula/module1/unit1/
```

or even better:

```
https://w3c.github.io/wai-curricula/curricula/introduction/unit1/
```

Reasoning: That way users can adopt the URL to jump to different units and deleting the unitX part gets you to the overview page for that module. It is also easier to read, for example during a presentation.

(I feel personally very strong about it, but I know that it is a personal preference, so I don’t feel it is a show stopper for me.)

**Comment by daniel-montalvo** [comment]
Changed.
