### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Unclear wording for introductory sentences

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#352]
Unclear what is meant by "explain how people with disabilities identify and distinguish user interface components based on different features, such as color, layout, spacing, and position."

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Module scope is now changed according to broader changes in structure.

These sentences have now been changed to.

<blockquote>

* demonstrate how people with disabilities rely on layouts that adapt to different screen sizes, screen configurations, and style sheets
* explain accessibility requirements for color, layout, spacing, and position of components

</blockquote>
