### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Awkward phrases that are hard to read and understand

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#353]
There are awkward phrases that are hard to read and have confidence that I understand them. One example:
- design user interfaces that support positioning different regions and user interface components where users expect them

Not sure I understand well enough to say this accurately but do you mean something like 
- fulfill user expectations with design choices in which regions and user interface components are easily found and used.

**Comment by daniel-montalvo** [comment]
Thanks @sharronrush 

We are working on alternatives for "design user interfaces" which is lengthy and hard to read.

We also need to take a pass on the whole curricula to simplify language.

We are currently working on all of this, and will update when we have results.

**Comment by daniel-montalvo** [comment]
We have reworded these sentences according to broader structure changes. That specific example is no longer there.

"design user interfaces" has been changed throughout the whole curricula to:

* "design layouts ..."
* "use ..."
* "design ..."
* "define ..."

as appropriate.
