### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Remove "alone" from second learning outcome

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#354]
The goal is to use other ways to supplement information conveyed through color. I don't think we need to use "color alone". "color" should be sufficient.

**Comment by daniel-montalvo** [comment]
I took a pass at this. Removed "Color alone" and tried to clarify that information conveyed through color needs supplemental cues

See
https://github.com/w3c/wai-curricula/pull/389/commits/2b3f7457c3478294ad6a71df508e3abddb2735bb

and preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/flexible-layout-and-design

Will leave open for now as it might require more work.

**Comment by daniel-montalvo** [comment]
Removed.
