### ISSUE TITLE
[Designer Module 1: Visual Design] Topic: Orientation Cues, improve legibility of second learning outcome

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#355]
I suggest to replace "text cues to convey information provided through vision only" with "text cues to convey information that otherwise would be provided through vision only". I believe this helps highlight the importance of the additional text cues.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

"that would otherwise be provided through vision only" is a bit of a convoluted phrase.

What about

> use text cues to supplement information provided through vision only, for example to convey required form fields and available dates in a calendar

* We try to get rid of the "design user interfaces" phrase
* we changed "conveyed" to "supplement", which is another way of highlighting the importance of the text cues

Thoughts?

**Comment by carlosapaduarte** [comment]
I think that could work. Would you be okay with adding a bit more detail to the example, to make the issue clearer? 
Something like:
> use text cues to supplement information provided through vision only, for example to convey required form fields represented with an icon and available dates in a calendar represented with a different background color

**Comment by daniel-montalvo** [comment]
This has now significantly changed since it was open.

Last agreed iteration in 
[EOWG Meeting 5 November](https://www.w3.org/2021/11/05-eo-minutes.html#t04)
