### ISSUE TITLE
[Designer Module 2: Navigation] Define "mega menu"

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#356]
"mega menu" is not defined in the WAI tutorial on Menus. Would it be worth it to define it?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

First, I wondered how we could define it. We could say something like "multi-level navigation menu" or something like that. But I think that would make things even more complicated. Can we look for a clearer term? Could we change "mega menu" to "hamburger menu" or similar?

Do you think that would solve the issue by making the type of menu more explicit or a definition is still needed?

**Comment by carlosapaduarte** [comment]
I think that making it more explicit (hamburger menu should be understood by all interested in the curriculum) would be sufficient.

**Comment by daniel-montalvo** [comment]
"Mega menu" changed to "hamburger menu"

Will show up in preview when I next upload changes.
