### ISSUE TITLE
[Designer Module 2: Navigation] Topic: Menu Behaviors and Patterns, include right to left languages?

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#357]
Should we include a reference to right to left languages in the teaching ideas?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

This was discussed in our [7 September TF meeting](https://www.w3.org/2021/09/07-wai-curricula-minutes.html)

We seem to agree that the relationship between this comment and accessibility requirements is not really clear. Writing systems seem to fall more under the usability and internationalization requirements than under accessibility requirements.

What were the specifics you would add here? Would it be OK for you if we leave it as-is?

**Comment by carlosapaduarte** [comment]
Hi @daniel-montalvo 

I'm okay with leaving it as is. My intention was to have this discussed to make sure we don't want to include it. And that goal was achieved. 

And apologies for missing the discussion.
