### ISSUE TITLE
[Designer Module 2: Navigation] Topic: Location, fix reference to set of websites

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#358]
On first teaching idea, I believe "set of websites" should be "set of web pages"

**Comment by daniel-montalvo** [comment]
Changed at
https://github.com/w3c/wai-curricula/pull/389/commits/7f18b9858c6d5d1485c41253d7f9fac8e63a809c

Preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/navigation
