### ISSUE TITLE
[Designer Module 3: Information Design] Topic: Textual Information, fix link

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#359]
The text of the first link should reference module 2, not module 3 (the module's name is correct)

**Comment by daniel-montalvo** [comment]
Fixed at
https://github.com/w3c/wai-curricula/pull/389/commits/189410ede2c8faf4276426ae030896a898c347eb

Preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/information-design
