### ISSUE TITLE
[Designer Module 3: Information Design] Topic: Textual Information, clarify need for reference

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#360]
It should be clear why we need to refer back to module 2

**Comment by daniel-montalvo** [comment]
Good point. This reference may not be understood unless we give it more context. As we may be moving things around, I will keep this open and amend once we clarify the overall structure.

**Comment by daniel-montalvo** [comment]
I think that reference is no longer needed with the new structure. I am proposing to take this reference out, as the separation between visual design and information design are now more explicit.

Closing this, feel free to reopen if you think this is still needed.
