### ISSUE TITLE
[Designer Module 3: Information Design] Topic: Textual Information, clarify responsibilities 

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#361]
It should be clear that the responsibility of providing the visual cues to understand textual information lies on the content authors, not the designers which are responsible for defining the way its presented

**Comment by daniel-montalvo** [comment]
Added in
https://github.com/w3c/wai-curricula/pull/389/commits/4542db634f91f5b5b6c1728c57358298aa8c6e9b

See preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/information-design/

I currently say "shared with the content author" as there might be intersections there. The author would provide these cues in a blog post or a piece of news, but probably the designer needs to provide some input when designing templates for web pages based on a specific authoring tool. Do you think we should attribute that responsibility exclusively to content authors?

**Comment by carlosapaduarte** [comment]
Given that there are many types of visual cues, I agree that the shared responsibility if probably the best way to go. 
But the example we provide on the learning outcomes (for example diagrams of a process to complement the textual information) is a good example of a situation where the responsibility is on the content author.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte  You convinced me on this one :-) And this is more consistent with other parts of this curricula. Feel free to reopen if you think there is something missing here.
