### ISSUE TITLE
[Designer Module 3: Information Design] Topic: Forms and Controls, missing contents related to the use of labels and instructions

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#362]
Learning outcomes and teaching ideas related to the use of labels and instructions are missing. The module has a learning outcome related to this subject, but contents are missing from this topic .

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 
 These have been now added in
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/information-design/#topic-labels-and-instructions

**Comment by carlosapaduarte** [comment]
Hi Daniel
The second teaching idea seems to be misplaced or not correctly focused on the topic. The way it is presented makes the idea about filtering mechanism, not labels or instructions. Could it be rephrased to address labels for long lists and how to organize (e.g. split) the long list?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Thanks for pointing this out.

I need to take a pass to the overall teaching ideas and ideas to assess knowledge. especially given the structural changes we are proposing. But I was waiting for getting into that until we have feedback from EOWG people commenting on structure.

**Comment by daniel-montalvo** [comment]
This should be fixed now. Closing, feel free to reopen if needed.
