### ISSUE TITLE
[Designer Module 5: Multimedia and Animations] Update prerequisites

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#363]
The prerequisites might include also Module 4, to ensure player controls created from (functional) images are accessible.

**Comment by daniel-montalvo** [comment]
Added in
https://github.com/w3c/wai-curricula/pull/389/commits/3dee74b59972ace4b3fd26950035eba5f17bd2f7
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations
