### ISSUE TITLE
[Designer Modules] Replace "Prototype Design" with "Prototyping"

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#366]
I think "Prototyping" is a clearer way to express the competency. 
"Prototype Design" can be understood as "designing prototypes" or "prototyping designs".
This needs to be replaced in all modules.

**Comment by daniel-montalvo** [comment]
Changed at
https://github.com/w3c/wai-curricula/pull/389/commits/8bfae6ab4310002c03c7ebe0cfe931848174e4c6

See preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/
