### ISSUE TITLE
[Designer Module 4: Images and Graphics] Mismatch between learning outcomes and topics

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#368]
The topics focus on different types of image but the learning outcomes cover a slightly different perspective: how images help, use of iconography, annotations for developers, alternative text.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

I have taken a pass on this module and expanded the topic learning outcomes to also cover what was in the module learning outcomes.
https://wai-curricula.netlify.app/curricula/designer-modules//images-and-graphics/

Closing, feel free to reopen if there is something you think is still not addressed.
