### ISSUE TITLE
[Designer Module 4: Images and Graphics] Use of CAPTCHA

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#369]
Concerned that CAPTCHA does not have a hazard warning attached to it!

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks.

Actually, and based on others comments, this is a broader issue. The way this is now written could be read as if we are encouraging the use of captcha, which we should not be doing.

I will rewrite this part to avoid that, and let you know when it is done so that we can revisit it and see  if that warning is still needed.

**Comment by daniel-montalvo** [comment]
Hey @iadawn

These learning outcomes read now:

> * provide alternatives to CAPTCHA and biometrics, for example by providing visual, auditory, and logical CAPTCHA
> * explain the issues associated with relying only on one form of biometrics and CAPTCHA, and describe alternative approaches for authentication

See preview at
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/images-and-graphics/#topic-informative-images

**Comment by daniel-montalvo** [comment]
Closing.
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/images-and-graphics/#topic-informative-images)

These read now

<blockquote>
* define alternatives to CAPTCHA and biometrics, for example by providing visual, auditory, and logical CAPTCHA
* explain the issues associated with relying only on one form of biometrics and CAPTCHA, and describe alternative approaches for authentication
</blockquote>
These may evolve in future iterations but I think main concern here has already been addressed that we do not promote (directly or indirectly) use of CAPTCHA alone.
