### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Split colour and layout

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#370]
Was any consideration made to spliting out colour to be it's own section?

* Why colour is important
* Colour contrast
* Colour and meaning
* Interaction styling with colour

It seems a bit lost within the Layout section?

**Comment by shawna-slh** [comment]
_heh, I said similar thing (though less specifically) before I saw this issue
moved from https://github.com/w3c/wai-curricula/issues/384 :

Additionally, poor contrast and other color issues are one of the most common easy-ish accessibility issues I see (pun intended) these days. (also something that's fairly squarely in a designer role)

Therefore, I'm **very inclined to make module 1 be color** (by itself).

**Comment by daniel-montalvo** [comment]
Hey @iadawn @shawna-slh 

We have discussed this in our [3 August TF meeting](https://www.w3.org/2021/08/03-wai-curricula-minutes.html#item03)

Even though there might potentially be enough material to cover color accessibility on a separate module, we are afraid that the level of detail we need to provide would be more at a course level than at a curriculum level. That would not be consistent with other curricula modules and parts.

We do acknowledge though that current module 1 Flexible Layout and Design needs more work on structure and wording.

Do you have more specific  suggestions on how to make color more prominent? Maybe having color as the first module topic?

**Comment by iadawn** [comment]
Terminology seems to be a bit difficult to follow. However, if the suggestion is to have colour as a comprehensive topic then that would be great.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn

 

And we are taking a look at terminology too.

 

--

 

Daniel Montalvo

 

Accessibility Education and Training Specialist

W3C/WAI

**Comment by daniel-montalvo** [comment]
Hey @iadawn @shawna-slh 

Please see updated [Module 1: Color and Layout](https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/color-and-layout/).

I see this as a subset of #384 , where I have updated an overall proposal.

@iadawn It seems to me you would be comfortable having "color" as a dedicated topic in current [Module 1](https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/color-and-layout), so I am closing this for now. Feel free to reopen if needed.
