### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Text grouping

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#371]
There may be something about grouping related text visually and annotating that for developers

**Comment by shawna-slh** [comment]
Like this: https://www.w3.org/WAI/tips/designing/#use-headings-and-spacing-to-group-related-content ? :-)

**Comment by daniel-montalvo** [comment]
Closing. Added

"use headings, spacing, and styling to group related content"
in
https://wai-curricula.netlify.app/curricula/designer-modules/visual-design/#leawrning-outcomes-for-module
4th bullet
