### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Color and meaning

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#374]
Doesn't appear to be anything on color and meaning in the use of color section

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

We are currently working on this section. It has changed significantly with respect to what we had before.

What we have at the moment is at:
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/color-and-layout/#topic-color

And what we had before is at:
https://wai-curricula.netlify.app/curricula/designer-modules/flexible-layout-and-design/#topic-use-of-color


Second-to-last and last learning outcome bullets talk about visual and non-visual cues to supplement information conveyed through color alone.

These I think relate to what you suggest, as meaning is one of the types of information you can communicate with color. What are the specifics about meaning that you miss here?b

**Comment by daniel-montalvo** [comment]
I think what is now in https://wai-curricula.netlify.app/curricula/designer-modules/visual-design/#topic-color says it more clearly. We don't use "meaning" as such, but "information",

Closing, feel free to reopen if you think this is still not addressed.
