### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Is target size flexible

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#375]
The learning outcome on target size doesn't seem to align with the broader topic of Flexible Design

**Comment by daniel-montalvo** [comment]
This has now been reworded to:

"design layouts with target sizes that adapt to different screen sizes,  screen configurations, and style sheets"

So it is not saying that target sizes are a characteristic of flexible design, but rather that target sizes, in addition to the rest of the contents discussed, need to adapt to different screen sizes,  screen configurations, and style sheets

If we do not mention target sizes in this module and we only discuss these, for instance, in the "Interaction Design" module, we risk that visual designers who only get to this very first modules think target sizes do not have an impact on accessibility.

Does this rewording address your concern? Where do you think target sizes should be discussed?

**Comment by daniel-montalvo** [comment]
Discussed and agreed approach in [EOWG Meeting 5 November](https://www.w3.org/2021/11/05-eo-minutes.html#t05)
