### ISSUE TITLE
[Designer Module 2: Navigation] ARIA patterns as teaching resource

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#376]
ARIA Authoring Practices includes relevant information on keyboard interactions and behaviors

**Comment by daniel-montalvo** [comment]
Hello @iadawn and @shawna-slh 

We discussed this in our [TF meeting for August 10](https://www.w3.org/2021/08/10-wai-curricula-minutes.html#item05)

At first, our rationale was that this resource is much more oriented to developers than to designers, and including it could be daunting for many designers. But we see your point in its informational value also for designers, so we are including it. We were thinking of including a link to the patterns section
https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex

And then having specific inline references to the keyboard guidance you mention at
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard

Is your suggestion that we only reference the section "Developing a Keyboard Interface" or you are open to also including the patterns?

**Comment by shawna-slh** [comment]
un-tagging @shawna-slh (leaving it to others)

**Comment by daniel-montalvo** [comment]
Closing. Added reference to appropriate modules after structure changes.
