### ISSUE TITLE
[Designer Module 2: Navigation] In page or in site distinction

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#377]
Not sure if it is hear but looking at the distinction between in-page navigation, such as tab panels, table of contents, skip links, accordions; and site navigation, menus, breadcrumbs, search, etc.

**Comment by iadawn** [comment]
Hmm... just found it in 'Other Navigation Mechanisms'. I think this might be a terminology issue.

**Comment by daniel-montalvo** [comment]
Closing. We will have:

* Module 3: Navigation Design
  * Topic: Menu Behaviors
  * Topic: Site Navigation
  * Topic: Page Navigation
