### ISSUE TITLE
[Designer Modules] Use of language

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#378]
This is a general thing that I noticed, the language seems to overly follow that used in WCAG in a detrimental fashion.

For example, 'design user interfaces with mechanisms for users to locate a specific web page within a set of web pages'.

**Comment by daniel-montalvo** [comment]
Hey @iadawn and @shawna-slh 

<p>I am working on simplifying the resource language and making the resource tone closer to designers.</p>
<p>Main changes include:</p>
<ul>
  <li>Change phrase "design user interfaces" to "design layouts", "use", and "design user experiences" to make learning outcomes more concise and less jargony</li>
  <li>Overall pass to replace specific terms used in WCAG with simpler and easier to process terms. For example:
  <ul>
    <li>"contrast ratios" -> "color contrast"</li>
    <li>"sets of web pages" -> "websites"</li>
    <li>"general flash and red flash thresholds" -> "acceptable thresholds"</li>
    <li>remove "motion animation triggered by interaction"</li>
  </ul>
  </li>
  <li>move away from WCAG definitions from multimedia content and use terminology from <a href="https://www.w3.org/WAI/media/av/">Making Audio and Video Media Accessible</a></li>
</ul>
<p>For a detailed view of the changes, you can take a look at <a href="https://www.github.com/w3c/wai-curricula/pull/389/files/">Overall Diff with Changes [WIP]</a></p>
<ul>
  <li>Do you think these changes solve the issue?</li>
  <li>What other suggestions do you have that would make the language closer to designers?</li>
</ul>

**Comment by iadawn** [comment]
The main changes all seem sensible. There may be other issues with wording that pop up when the resource is polished.

**Comment by daniel-montalvo** [comment]
Closing. It seems we all are in agreement with the overall approach. Happy to discuss specific wording issues in separate issues.
