### ISSUE TITLE
[Designer Module 3: Information Design] Design of forms

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#380]
Was design of forms considered as a specific module?

* Positioning of labels
* Visual styling of form elements
* Native vs designed form elements
* Non-standard form elements
* Presentation of errors and feedback

**Comment by shawna-slh** [comment]
It would be good to acknowledge that forms design is a specialty all itself. (Expert from my ole usability days): https://www.effortmark.co.uk/forms/ )

And that this curricula highlights particular accessibility issues - and some other aspects of good or bad forms design could disproportionately impact people with disabilities, esp. with COGA.

... I guess that applies to lots in the curricula -- just seems like a bigger deal for forms design.

**Comment by daniel-montalvo** [comment]
Closing.

- Agreed on new module [Forms Design](/curricula/designer-modules/forms-design).
- Implemented suggestions from [EOWG 22 October](https://www.w3.org/2021/10/22-eo-minutes) and [EOWG 29 October](https://www.w3.org/2021/10/2i-eo-minutes) meetings.
