### ISSUE TITLE
[Designer Module 4: Images and Graphics] Presentation of data

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#381]
Might be worth pulling this out as a topic. It is buried in 'Complex Images' but I think that is a poor term as data presentation might not be complex.

**Comment by daniel-montalvo** [comment]
Hey @iadawn

Presentation of data may not have to do with images in some cases. WE tried to have some specifics on data visualization / data representation in the module on images, but ended up concluding that this is a much broader topic that we need to address differently.

Related to our discussion in #373, we are including learning outcomes that go along the lines of assessing and balancing what is too much or too little, and also to determine the appropriateness of a particular component.

In the case of complex images, designers may need to help take decisions about whether a complex image is the best approach to present certain data. Designers may also need to plan ahead for alternatives to that particular presentation of data that authors may provide and developers  may implement later on in the process. These alternatives could include simpler images, tables, and plain text.

In topic "Complex Images" we now have

<blockquote>

* use appropriate contrast ratios for complex images
* assess the use of complex images versus other ways to present the same information, such as tables, simpler images, and plain text
* determine if and how complex images are operated using input devices, including mouse, keyboard, voice, and touch
* consider placement and spacing for alternatives to complex images
* design clear and consistent identification mechanisms for complex image descriptions, including appropriate headings and expandable and collapsible components
* design user experiences for complex images, including how to get to the image descriptions, what the content of the description should look like, and if the descriptions could ultimately replace the image itself
* identify related requirements for content authors to provide descriptive, equivalent textual information to understand complex images and graphics, such as diagrams, charts, maps and infographics
* identify related requirements for content authors to break down complex images into smaller and more manageable pieces, for example simpler images, tables, and plain text

</blockquote>

and previously we had

<blockquote>

* design user interfaces that support appropriate contrast ratios for complex images when these images are required to understand the contents
* identify related requirements for content authors to provide descriptive, equivalent textual information to understand complex images and graphics, such as diagrams, charts, maps and infographics
* determine if and how complex images are operated using the mouse, keyboard, and other input devices

</blockquote>

Do you think these new additions address your concern? What specifics about data representation you are missing from the designers perspective?

**Comment by daniel-montalvo** [comment]
Think addressed with resource reorganization. Feel free to provide specifics if needed.
