### ISSUE TITLE
[Designer Module 5: Multimedia and Animations] Mechanisms disappearing

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#382]
"they should not disappear when the media starts playing"

Does that mean that Netflix should retain their interface elements at all times when a video is playing?

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

My understanding is that these types of interfaces you mention have a "Full screen" mode, and there is where the controls disappear. AS soon as you get out of "full screen" mode, you can see the controls again.

If that is correct, we already have the phrase "are always reachable for users"

Do you think removing the references about the controls "not disappearing when the media starts playing" and providing some examples on how you can make the controls always reachable for users would solve this?

Thanks.

**Comment by iadawn** [comment]
Sounds like a good solution
