### ISSUE TITLE
[Designer Module] Tips

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#386]
Ref: https://www.w3.org/WAI/tips/designing/

Are all these included if wanted? Is the link included in the Resources?

/me didn't read, so just noting for Daniel :-)

**Comment by daniel-montalvo** [comment]
Thanks for this pointer, @shawna-slh 

I think the curriculum covers what is on the Designer Tips, but the resource is not listed in the teaching resources, same as it is not in the developer part.

We thought that the Tutorials covered everything that is on the Tips for the developers, but that is probably not the case with designers.

We may want to include these Tips in both, although I think we should include them only in the first modules, the ones dealing with the most basic knowledge.

**Comment by daniel-montalvo** [comment]
Added Designer tips at 54a621734ec219f4517275f5fba807921aeb5393

as discussed in our [August 10 TF meeting](https://www.w3.org/2021/08/10-wai-curricula-minutes.html#item04)
