### ISSUE TITLE
[overall] WAI Resources in "Teaching Resources"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#387]
Would be good to check that all relevant WAI resources are listed under "Teaching Resources" as appropriate.

e.g., the Tutorials, the media resource, the [Tips](https://www.w3.org/WAI/tips/), ...

See [WAI Resources](https://www.w3.org/WAI/resources/) annotated list.

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

> Would be good to check that all relevant WAI resources are listed under "Teaching Resources" as appropriate.

Yes, there were some missing, I am taking a pass to make sure all relevant ones are included. I plan to add the relevant videos per module

> See [WAI Resources](https://www.w3.org/WAI/resources/) annotated list.

What are you suggesting with this pointer? A change in the wording of our "Teaching Resources" section? Just a place that has all possible resources handy?

**Comment by shawna-slh** [comment]
I saw just pointing you to that [WAI Resources](https://www.w3.org/WAI/resources/) annotated list as a place for you to find all the WAI resources that you/TF/EO might want to include :-)

**Comment by daniel-montalvo** [comment]
Will close both when updating #376

**Comment by daniel-montalvo** [comment]
Updated resources. Feel free to reopen if you miss anything.
