### ISSUE TITLE
Are focus indicators a cue?

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#390]
@MicheleAWilliams-A11y says in 
https://www.w3.org/2002/09/wbs/35532/curricula-designers-starfish/results#xq10

> Are you considering "focus indicators" a cue? Feels out of place to have this here versus the Navigation module.

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y

We discussed placement of focus indicators in our [3 August TF meeting](https://www.w3.org/2021/08/03-wai-curricula-minutes.html#item04).

We put focus in flexible layout and design because focus has to do with the concepts we discuss in that module. A focus indicator can be implemented by using distinctive styles, by modifying background color, or by using borders. If we were to put focus indicators in the navigation we would be restricting its scope.

However, we acknowledge that we need to work on
* better structuring of module 1 to make focus indicators more prominent
* adding clearer cross-references to the navigation module to address your concern that focus indicators help some users navigate the interface.

Would that address your concern?

**Comment by MicheleAWilliams-A11y** [comment]
Sounds good!
