### ISSUE TITLE
[Designer Module 1: Visual Design] "use non-visual cues" in a Visual Design module

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#397]
The fifth learning outcome states "use visual and non-visual cues to convey information, including text, color, patterns, and icons". The module is on Visual Design, so the reference to non-visual cues is a little odd and I'm finding it hard to understand what is meant by this learning outcome. 
Is it "use multiple visual cues because relying on a single type of visual cue (e.g. color) makes the content inaccessible for some users"? 
Or is it "supplement visual cues with non-visual cues because relying only on visual cues, even if multiple ones, makes the content inaccessible for some users"?
If it's only the former, it won't solve the latter. And if it's only the latter, it won't solve the former. But it does not sound like it's both. And I'm not really sure the latter should be in this module, because of the "Visual Design" scope.

**Comment by carlosapaduarte** [comment]
After going through topics Color and Orientation Cues I understand that both of the above are in the scope of this module. Perhaps we can make it more explicit in the learning outcome? Something like "use multiple visual and non-visual cues"?

**Comment by daniel-montalvo** [comment]
That's now changed to:

> use several visual and non-visual cues to convey information, including text, color, patterns, and icons

Worth discussing probably, to make sure everybody is comfortable with scope. I see your point that it is a bit weird to talk about non-visual cues in a visual design module. But still think the idea that relying only on visual cues is not accessible design should be provided up-front.

**Comment by daniel-montalvo** [comment]
Changed to "use multiple visual and non-visual cues to convey information, including text, color, patterns, and icons"

Will close when merged.
