### ISSUE TITLE
[Designer Module 1: Visual Design] Learning outcome "evaluate the overuse of design elements" Missing in teaching ideas

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#398]
The seventh learning outcome states "evaluate the overuse of design elements". I'm having trouble in addressing this from an accessibility perspective. I can understand it from a usability or visual design perspective. 
I'm sorry if this has already been discussed, but I don't recall seeing it before.

**Comment by carlosapaduarte** [comment]
I see it is being addressed in the learning outcomes of topic flexible layouts, but there are no teaching ideas there for this topic, so I'm still not really convinced that the overuse is an accessibility problem, if the design elements are themselves accessible.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

The idea of balancing what is too much or too little for an interface in terms of accessibility was [introduced after the July survey](https://www.w3.org/2021/08/24-wai-curricula-minutes.html#item03). We use "evaluate" and "select" to align to Bloom's taxonomy. The line between accessibility and usability is too fine here, that is a good point. 

We have more of these throughout the other modules. Is it just these instances that you are not comfortable with? Is it the the overuse what you think is out of scope?

**Comment by carlosapaduarte** [comment]
Yes, it is the "overuse of design elements" that I think might be out of scope (because it is more of a usability than an accessibility issue, as long as the design elements are accessible themselves). Would like to know what others think.

**Comment by daniel-montalvo** [comment]
@sloandr  suggests:

> Use of “overuse/too many” is problematic as it implies an absolute condition, when overuse is contextual, and students need to be able to make a contextual assessment. Suggest the following edits:
> 
> In the topic intro, second para:
> 
> “Demonstrate approaches to providing an appropriate number and diversity of design elements use to avoid potential overload and distraction for some users.”
> 
> In the topic LOs, second last bullet:
> 
> “detect the potential overuse of design elements”

**Comment by daniel-montalvo** [comment]
Closing as per above commits and [7 Dec TF discussion](https://www.w3.org/2021/12/07-wai-curricula-minutes.html#item05)
