### ISSUE TITLE
[Designer Module 1: Visual Design] New teaching idea for Topic: Color or Topic: Styles

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#399]
One teaching idea that could be added is showing on a user style sheet for increasing contrast, or turning on the high contrast mode at the operating system level, impacts the visual design of a web page.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Added in

https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/visual-design/#topic-styles

teaching ideas, third bullet.
