### ISSUE TITLE
[Designer Module 2: Information Design] Alternative forms of presentation in Topic: Text and Structure

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#402]
The second learning outcome calls for the need to present (some) textual information through other means, like diagrams and illustrations. Shouldn't we have a similar learning outcome calling out for the need to describe in text, information that is conveyed  in diagrams and illustrations? 
From an Information Architecture perspective I believe that should also be here, even if it is repeated in the Images and Graphics module.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Added in https://github.com/w3c/wai-curricula/commit/f19ab624e1a87ac244bc384e99cae3517cdadaab

For preview, see
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/information-design/#topic-text-and-structure

Do you agree with this?

**Comment by carlosapaduarte** [comment]
Hey @daniel-montalvo 

Yes. Excellent!
