### ISSUE TITLE
[Designer Module 2: Information Design] Should we have something about lists?

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#404]
Lists are only addressed as an alternative to present content in complex tables. But lists are used for many more purposes, some addressed in other modules. 
It is not that uncommon to find lists on the web that are styled as lists, but are not semantically marked as lists. I understand the coding is responsibility of the developer, but in other instances we have indicated the need for the designer to provide instructions to the developer. Shouldn't we do that for lists also?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Added in https://github.com/w3c/wai-curricula/commit/4b85b3985383c4b412773d4a41a1a9ecb456f5e7

See preview at
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/information-design/

Do you agree with these changes?

**Comment by carlosapaduarte** [comment]
Hey @daniel-montalvo 

Yes, I believe these changes highlight the role of lists in this context.
