### ISSUE TITLE
[Designer Module 3: Navigation Design] Blocks of repeated content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#405]
The learning outcomes for module 3 state "define blocks of repeated content". Shouldn't we have a learning outcome for students to "design navigational components that allow skipping blocks of repeated content"? (feel free to improve on my formulation)

**Comment by daniel-montalvo** [comment]
That is good suggestion @carlosapaduarte  and I agree that it is missing in the learning outcomes for module.

I agree we can add this to the existing learning outcomes. Not so sure we can easily replace define. 

If we drop the define aspect, who would decide what is a block of repeated content and what is not? Can we argue that deciding what a block of repeated content is does not need designer's intervention?

**Comment by carlosapaduarte** [comment]
Hey @daniel-montalvo 

I was not proposing dropping the "define blocks of repeated content". Just adding that the curricula should also include the definition of the methods to skip the blocks. But I think the current preview has successfully addressed this.

**Comment by daniel-montalvo** [comment]
Resolved according to [discussion on LO verbs](https://www.w3.org/2022/01/11-wai-curricula-minutes.html#item03).
