### ISSUE TITLE
[Designer Module 3: Navigation Design] Editorial suggestion for teaching ideas of Topic Menus

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#406]
The third teaching idea states "Show examples of navigation menus and menu items large text."
I suppose it's missing a "with" to make it "menu items with large text".

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

"Menu items large text" was intended as a short-hand for "large text of menu items". I have replaced that with your suggestions. It is clearer. Will show up when. updating the preview.
