### ISSUE TITLE
[Designer Module 3: Navigation Design] Redundancy in learning outcomes for topic Site Navigation Can Site Navigation components create distractions and unnecessary noise?

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#407]
I feel the fourth learning outcome just repeats the first and second learning outcomes. De we need to keep it?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

We have several instances of "select navigational components to help users navigate and orient". I agree that "help users navigate and orient" does not add to what we have already.

There are other places in the module where we say "minimize distractions and unnecessary noise". Once again this is trying to make designers aware that too little can be insufficient, but too much can be overwhelming. That bit got lost somewhere. I think we could put it back again.

What if we rephrase this last learning outcome you are referring to as:

Site Navigation

> * select site navigational components that minimize distraction and unnecessary noise

Page Navigation

> * select page navigational components that minimize distraction and unnecessary noise

Do you still think this would be a repetition?

**Comment by carlosapaduarte** [comment]
No, I don't think that would be a repetition. But I don't think we have teaching ideas to address those.

**Comment by daniel-montalvo** [comment]
Will add those.

**Comment by daniel-montalvo** [comment]
Removed the fourth learning outcome  in [Topic Site Navigation](https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/navigation-design/#topic-site-navigation).

**Comment by daniel-montalvo** [comment]
@carlosapaduarte 

Preview:
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/navigation-design/ 

I also moved assessment that was previously in topic Site Navigation, for better coverage of learning outcomes for module. "Give students an interface with excessive use of navigational components and ask them to determine which of these navigational components are necessary and which should be removed. [...]".

"Navigational components that can cause distractions and unnecessary noise" is now in:

- LOs for module.
- LOs, teaching ideas, and ideas to assess knowledge for topic Page Navigation.
- Ideas to Assess Knowledge for Module.

I think these changes gives us a nice balance of when and when not to reference distractions and unnecessary noise.

Closing, feel free to reopen if needed.
