### ISSUE TITLE
[Designer Module 3: Navigation Design] First learning outcome in topic Page Navigation is ambiguous 

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#408]
The first learning outcome reads "select methods to identify blocks of repeated content, such as navigation bars and header contents"

I think this learning outcome is about providing visual and non-visual cues that allow users to identify blocks of repeated content (but not skip them - which is addressed in the following learning outcome). But I don't think the learning outcome expresses this clearly. I think it needs to be clearer that the methods are there to support the user in the identification task. 

My suggestion "design methods (visual and non-visual) to support users in identifying blocks of repeated content, such as navigation bars and header contents"

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

That's good suggestion. I have rephrased that a little bit. I think the below is closer to what we are using in other places

> design visual and non-visual methods to help users identify blocks of repeated content, including navigation bars and header contents

Are you comfortable with these further changes?

**Comment by daniel-montalvo** [comment]
Updated learning outcomes

See preview at https://wai-curricula.netlify.app/curricula/designer-modules/navigation-design/#topic-page-navigation
