### ISSUE TITLE
[Designer Module 4: Interaction Design] Editorial suggestion for the introduction to topic Gestures and Motion

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#409]
The second sentence in the first paragraph reads "Explain that some people may perform these motion-based gestures inadvertently, others may not be able to perform them at all."

I think changing to "while others may not" after the comma would improve the readability.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

This is now added. Will show up when updating the preview.
