### ISSUE TITLE
[Designer Module 4: Interaction Design] &mdash: instead of the dash showing in the first of the Ideas to Assess Knowledge for Module

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#410]
I suppose it's because there is a colon instead of a semi-colon at the end of &mdash

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 


That's now changed. Will show up correctly when uploading the preview.

> I suppose it's because there is a colon instead of a semi-colon at the end of &mdash

Exactly, that was the reason.
