### ISSUE TITLE
[Designer Module 4: Interaction Design] Meaningful sequences in topic Keyboard Interactions

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#411]
While meaningful sequences are mentioned in the module's learning outcomes, I don't think they have enough visibility in the learning outcomes for the topic Keyboard Interactions. One can argue that they are included in "design user experiences for keyboard navigation" which is the first learning outcome. But this way I believe they will be frequently missed.

**Comment by daniel-montalvo** [comment]
This has nwo been addressed in
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/interaction-design/#topic-keyboard-interactions

**Comment by daniel-montalvo** [comment]
@carlosapaduarte 

I think this is addressed with above changes. Preview: https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/interaction-design/#topic-keyboard-interactions

Feel free to reopen if needed.
