### ISSUE TITLE
[Designer Module 5: Images and Graphics] Learning outcome in topic Informative Images is not clear

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#412]
The sixth learning outcome reads "evaluate the issues associated to accessing information contained in informative images"

Do we want students to evaluate the issues associated with accessing information? I don't even know I'm sure what that means! Is this related to how UA and AT process and convey the information? 

I'm wondering if this is about evaluating the benefits and pitfalls of the different alternatives to convey equivalent content to the image?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte

The intent was to relate this to how UA and AT process and convey the information, especially in the context of text alternatives versus ordinary plain text.

"evaluating the benefits and pitfalls of the different alternatives to convey equivalent content to the image" seems to be more related to the content author part.

I think the bottom line here for the designer is to

* ensure that when there is an informative images there is also an alternative, and 
* work with other team members to achieve as much decoration effects using CSS and plain text..

I am taking this learning outcome out as I think we have these points covered through the rest of the bullets.
