### ISSUE TITLE
[Designer Module 5: Images and Graphics] Incorrect role in the teaching ideas for topic Complex Images

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#414]
In the second teaching idea for the topic Complex Images, is stated that "providing these text alternatives is a designers’ responsibility"

Shouldn't it be "a developer's responsibility"?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Thanks for pointing this out. I think what is unclear here is the actual responsibility that we are assigning to designers. This whole sentence may deserve a bit of work.

We currently say:

> Explain that providing these text alternatives is a designer's responsibility, whereas providing the text descriptions is a responsibility shared with the content author.

I would propose:

> Explain that defining the presentation of these text alternatives is a designer's responsibility, whereas providing the text descriptions is a responsibility shared with the content author.

* We scope the designer's responsibilities more clearly -- presentation of the alternatives
* We acknowledge that providing the actual descriptions may be a shared responsibility with the content author. And we give us a little bit of space for the next curriculum on content authors.

Would you agree with my assessment here?
Why is that you mentioned developers rin the context of complex images?

**Comment by carlosapaduarte** [comment]
Hey @daniel-montalvo 

Let me start that I agree with your proposal, and that it clearly scopes the responsibilities. 
I mentioned developers in my comment because I understood "providing these text alternatives" as coding the complex image in a way that AT should be able to access the text alternative. With your proposed changes it's clear that this is not about "providing the code" but about "designing the presentation".
