### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Editorial suggestion for Learning Outcomes for Module

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#416]
The third learning outcome lists accessibility issues. I don't think the items in the sub list should start with a verb (i.e., select) because the accessibility issue is not the selection, but the media player having or not the feature that is described in the list item. My suggestion is to drop "select" in the items in this sublist.

**Comment by daniel-montalvo** [comment]
Hello @carlosapaduarte 

Others have suggested that we should change "issues associated" to "considerations for" on this learning outcome. With that change, we could even shorten the sub bullets a bit more.
So with these two changes, it would read:

> * identify accessibility considerations for media players, including:
>  * support for different methods of interaction, including mouse, keyboard, touch, and voice
>  * controls that have clear and descriptive names, that are easy to find, and that are reachable by all users
Would you be happy with these further changes?

**Comment by carlosapaduarte** [comment]
Yes, I agree with the proposed changes.

**Comment by daniel-montalvo** [comment]
That's done now. Will show up when updating the preview
