### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Editorial suggestion for teaching ideas for topic Alternatives to Multimedia Content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#418]
In the second teaching idea (the one about captions) the penultimate sentence was copied from the previous teaching idea. In that sentence "description" should be changed to "captions".

**Comment by daniel-montalvo** [comment]
Thanks for raising this @carlosapaduarte 

I have replaced the wrong term. Will show up when updating the preview.
