### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Editorial suggestion for teaching idea on media players for topic Alternatives to Multimedia Content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#420]
In the last teaching idea (the one about media players) I wonder if "easy to find" should be expanded to "easy to fin on the page". This would make sure that no one would interpret this as "easy to find when searching for an existing media to use in my design".

**Comment by daniel-montalvo** [comment]
That is a good point @carlosapaduarte 

Why not doing it also on the LO

We would have:

* Added "on the page" in LO: "select media player controls that have clear and descriptive names, that are easy to find on the page, and that are reachable by all users"
* Added on the page in teaching idea: ... "Emphasize how accessible media players are operable by keyboard, make keyboard focus visible, have clear labels, have appropriate contrast ratios, and are easy to find" on the page. ...

**Comment by carlosapaduarte** [comment]
I agree with changing it also to the LO

**Comment by sharronrush** [comment]
+1
