### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Suggestion of idea to assess knowledge for topic Alternatives to Multimedia Content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#421]
I think we could have one idea around media players. My suggestion for your consideration:

"Practical - Ask groups of students to search online for existing media players that can be integrated in a web page and characterise their support for accessibility. Assess how students rated the support for keyboard operation, visibility of the focus indicator, clarity of the labels and the contrast ratio of controls."

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Added in
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations/#topic-alternatives-to-multimedia-content
