### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Suggestion of an assessment idea for topic Movement and Animations

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#422]
Albeit there is a teaching idea about animations that could be considered addressing carousels, I wonder if we shouldn't have one explicitly about carousels? If you agree to this, then here is my suggestion:

"Practical - Give students examples of web pages using carousels and ask them to examine the carousels' support for accessibility. Assess how students understand accessibility requirements for carousels."

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Included. Changed "examine" to "evaluate"
