### ISSUE TITLE
[Designer Module 7: Forms Design] About grouping form elements

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#424]
Structure is a topic that is highlighted (more than once) in the learning outcomes of this module. Grouping form elements is one important way to structure forms. However, there is no explicit mention to grouping associated form elements. This is handled in Module 2, and there is a reference for it in topic Label and Instructions. But I believe it would be good to have an explicit learning outcome in the labels and instructions topic about grouping of form elements.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I propose something like:

> associate form elements that share the same purpose, such as those to provide an address, and communicate these groups visually and non-visually

This ties back to what we have in Information Design:

> associate controls that share the same purpose, such as those collecting personal information, payment methods, and consent to legal conditions, and communicate such groups visually and non-visually

**Comment by carlosapaduarte** [comment]
Hey @daniel-montalvo 

I agree with your proposal, but couldn't find it the last preview.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 


This is now in preview
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/forms-design/#topic-labels-and-instructions
