### ISSUE TITLE
[Designer Module 5: Images and Graphics] [Topic Informative Images] Learning outcomes on captcha and biometrics are the other way round in terms of importance

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#436]
@sloandr  says:

> The two bulleted LOs for CAPTCHA (define alternatives to biometrics and CAPTCHA…, and explain the issues associated with…) seem to be the wrong way round in terms of importance/relevance. Indeed, the first one seems redundant—it’s not clear what the difference is between the two. I’d suggest removing the first or looking at rewording to make the two more distinct.

**Comment by daniel-montalvo** [comment]
Hey @sloandr 
Worked in https://github.com/w3c/wai-curricula/commit/c3539fae5c5a09c07ecf7ab69024f6c28f5ebc62

For preview, see
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/images-and-graphics/#topic-informative-images

Would you agree with these changes?

**Comment by sloandr** [comment]
@daniel-montalvo sorry I missed your earlier request for feedback, but confirming the change seems good to me

**Comment by daniel-montalvo** [comment]
No worries, good to have confirmation. 

 

--

 

Daniel Montalvo

 

Accessibility Education and Training Specialist

W3C/WAI
