### ISSUE TITLE
Appropriate structure of "For example…" sentences

### ISSUE THREAD

**Issue by sloandr** [w3c/wai-curricula#450]
While reviewing the latest version of the Design curricula, I noticed several examples of sentences of the following general structure:

"For example, [list of examples containing gerund clauses]."

As an example, in [Designer Module 2](https://wai-curricula.netlify.app/curricula/designer-modules/information-design/), Topic Text and Structure:

> For example, using pages to split the content into logical units, landmarks to define page regions, and headings with their corresponding rank levels to group related information.

Is this sentence structure considered acceptable in W3C documents? My view is that it's not a proper sentence, but I also see it frequently enough to wonder if it's become acceptable in technical writing and is approved style here.

As an alternative, we could adjust the above example to include a verb at the start:

> **Examples include** using pages to split the content into logical units, landmarks to define page regions, and headings with their corresponding rank levels to group related information.

**Comment by daniel-montalvo** [comment]
hey @sloandr 

Thanks for these comments.

1. I split this type of sentence into to as per EOWG style
https://www.w3.org/WAI/EO/wiki/Style#Punctuation

    <blockquote>
    "For example," OK as own sentence, even if not full sentence. This is generally easier to read, even though not formally correct.
    Usually best:
        <blockquote>Ensure that your design can accommodate visible alternatives for images and media as needed. For example, links to transcripts of audio, text with icons and buttons, and captions and descriptions for tables or complex graphs. 
       </blockquote>
    Only when need to be grammatically correct:
        <blockquote>Ensure that your design can accommodate visible alternatives for images and media as needed; for example, links to transcripts of audio, text with icons and buttons, and captions and descriptions for tables or complex graphs. 
        </blockquote>
     </blockquote>

2. As per use of gerund, I'll differ to @shawna-slh . I've seen this myself but I understand we should change if not grammatically correct.

**Comment by sloandr** [comment]
Thanks for the link to the wiki entry, @daniel-montalvo. That helps clarify things for me with respect to EOWG style conventions.

**Comment by shawna-slh** [comment]
Hi @sloandr Indeed EOWG decided on that when working on simplifying language a couple years back. I'm not totally comfortable with it. Perhaps we should revisit?

For now, I support leaving it as is in this resource. I think we do not want to change to "Examples include..." because that seems harder for some people to process than "For Example,..."

**Comment by daniel-montalvo** [comment]
Closing. Will update status if EOWG revisits this.
