### ISSUE TITLE
Include Infographic to list out the focus areas of each visual design sections 

### ISSUE THREAD

**Issue by PoornimaSubramanian** [w3c/wai-curricula#466]
The Visual design sections are detailed nicely. My below comment is related to the "Topics to teach" section where similar topics are repeated under each topics. 

Suggestion: For intuitive (quick approach) understanding, Include Infographic in either of the below forms - 

1. One (big picture) infographic that categorize the Topics to teach -> topics -> visual design components (Color -> Color Contrast -> Contrast ratio & Gray Scale)

(OR)

2. Create smaller infographics to break down each 'Topics to teach' categories mapping the focus areas of each visual design components

**Note:** If this suggestion sounds like a good idea, let me know. I can actually work on the drafts/sample of Infographic for this module!

**Comment by daniel-montalvo** [comment]
Thanks for your feedback @PoornimaSubramanian

We will consider this for future iteration. We are now working on the [Content Author modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/)
