### ISSUE TITLE
Rephrase 'Students' 

### ISSUE THREAD

**Issue by PoornimaSubramanian** [w3c/wai-curricula#468]
'Students' often refer to the scholars from academic field. As this curricula designed for all learners irrespective of their field of work or study, can this word be rephrased to e.g. 'Learners'  or other similar context?

**Comment by daniel-montalvo** [comment]
Thanks for your feedback @PoornimaSubramanian

The group has largely discussed these terms and decided to use "students". I agree that each term has different meanings depending on culture and society. "Learners", for example, is associated to primary school in some places.

We will close this for now.
