### ISSUE TITLE
[Module 2: Content Structure] Content consistency not address in Learning Outcomes

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#477]
I'm unsure if consistency (in the way headings, links, navigation and interaction in general are written) should be addressed in this module or the first one. I'm more inclined to place it here (you need structure to have consistency), but irrespectively of where it ends, I believe it's something that needs to be addressed.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I was not sure either when I was putting this together.

Consistency, as well of meaningful sequence, I think applies to several of these modules, so will add.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I took a pass at these. in [Module 2: Structure](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/)

* Learning Outcomes for Module
  > * provide meaningful and consistent headings to help users identify and navigate the different content sections
  > * collaborate with designers and developers to:
  >    * ensure meaningful content sequences irrespective of screen sizes, user configurations, and assistive technologies in use
* Learning outcomes for Topic Headings
  > * provide consistent headings and their corresponding rank levels to help users identify and navigate the different content sections
* Learning Outcomes for Topic Orientation and Navigation
  > * explain how people with disabilities rely on meaningful content sequences, tables of contents, and other orientation methods to orient themselves and navigate content

I think this covers the above comments. Closing. Feel free to reopen before the survey or to provide further suggestions when the survey launches.
