### ISSUE TITLE
[Module 1: Content Clarity - last LO]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#480]
The last learning objective state that the student will be able to "ensure content grouping and spacing to communicate sections" which is an ambiguous phrase and seems to have more to do with structure than "clarity."

**Comment by iadawn** [comment]
Agreed, the whole section in 'ensure' seemed to me to be more about visual design. Althoguh I think there is a need for content authors to work with visual designers to agree these elements.

**Comment by bakkenb** [comment]
Agree. Added issue #498 before reading this.

**Comment by daniel-montalvo** [comment]
Hey @bakkenb @iadawn @sharronrush 

closing as per above input and TF discussions.

[Module 1: Clear Content, learning outcomes for module](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#learning-outcomes-for-module), say:

> * identify related requirements for designers and developers to ensure:
>   * appropriate contrast ratio for content> 
>   * easy to read and easy to understand font types and sizes

[Module 2: Structure, learning outcomes for module](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/#learning-outcomes-for-module), say:

> * identify related requirements for developers and designers to ensure:
>   * visual and non-visual perception of content structures , including headings, paragraphs, lists, quotes, and others
>   * adequate content grouping and spacing to communicate semantic structures visually

Feel free you all to reopen this if you disagree with how it looks like.
