### ISSUE TITLE
[Module 2: Content Structure LO #4 links]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#481]
This would seem to belong in content rather than here. It refers to "clear and meaningful link text" which is not really structure.

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Based on [15 March TF discussion](https://www.w3.org/2022/03/15-wai-curricula-minutes.html#item04
), this is moved to 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clarity/
