### ISSUE TITLE
[Module 2: Content Structure] Unclear language

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#482]
I know this is not yet to be wordsmithed but I have to note that the language used in a couple of the LOs around  being "perceivable visually and non-visually" is a bit contorted and could be simplified. A more straightforward phrasing seems especially important in a module focused on content.

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 
Thanks for these comments. It is always good to avoid as much unclear wording from the start.

I changed "both visually and non-visually" to "visual and non-visual perception of", for example in

Learning outcomes for module

> * collaborate with developers and designers to ensure:
>   * visual and non-visual perception of content structures , including titles, headings, paragraphs, lists, quotes, and others

Learning outcomes for topic Headings

> * collaborate with designers and developers to ensure visual and non-visual perception of headings

See preview at https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/
