### ISSUE TITLE
[Module 1: Clear Content] Naming

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#483]
Not sure on the name for a couple of reasons:

* I don't think that 'Content' is required - the module is for content authors so I don't know that adding an additional 'content' adds anything. Feel fairly strong on this one.
* 'Clarity' jars a bit with me a little bit althoguh I can't put my finger on why. Words (and phrases which are less useful) that come to mind for this section are 'Understandable' (too cumbersome), 'Keep it simple' (too familiar), 'Plain language' (covers more than just language). 'Simplicity' might work well but I know that this isn't ideal as it is more 'As simple as possible' and that some people might see this as a possible slur. Not so strong on this.

**Comment by bakkenb** [comment]
Agree on this point. I was leaning towards "Understandable Content" before reading this thread. It is cumbersome, but more accurate of what to convey in the first Module I think.

**Comment by daniel-montalvo** [comment]
Changed to "clear Content" for now.

After having played with "Clarity", "Content Clarity", "Understandable Content", and "Clear Content", the latter:

* sounds best
* is less of a tongue twister
* conveys what is currently discussed in that module

**Comment by daniel-montalvo** [comment]
Hey @iadawn

We have now taken a pass at all names. We have:

- streamlined the titles
- removed "content" in other modules where that felt repetitive

The only one that has content in it is "Clear Content".

- We think "Clear" somewhat needs a qualifier.
- "Clarity" alone is difficult to pronounce
- "Plain Language" is just a sub set of what is covered here.

Would you be comfortable if we keep "content" only in this module given that the other module titles don't have "content" anymore?

**Comment by daniel-montalvo** [comment]
Closing as no opposition has been observed.

Feel free to re
open this if needed.
