### ISSUE TITLE
[Module 1: Content Clarity] Emphasize Quality of text alternatives

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#484]
Slight niggle but 'use text alternatives' I think should be more about the quality of the text in the text alternative. Possibly something like:

* provide text alternatives that clearly communicate the purpose and content of images and other graphics

Not quite right but something more along those lines perhaps.

**Comment by daniel-montalvo** [comment]
Hey @iadawn @bakkenb

Closing.

Ref:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#learning-outcomes-for-module 

Currently it says:

> * write text alternatives that clearly describe the purpose and communicate the content of images and other graphics

More wording tweaks may come later. But I think we have nailed down the distinction now.
