### ISSUE TITLE
[Module 2: Content Structure] Naming

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#485]
I have the same concern about the inclusion of the word 'content' in this title as in #483.

I think 'Structure' would be sufficient on it's own.

**Comment by daniel-montalvo** [comment]
Thanks for this suggestion @iadawn 

Structure would definitely work well on its own for this. Not so sure about "Clarity" for the first module, we would need to look for something else there.

Overall, We could have:

* Clarity
* Structure
* Images
* Data Tables
* Multimedia
* Forms

But we can leave with these for now and come back to titles later.

Is your issue with one-word versus two-word inconsistencies? Or is it about "content" everywhere?

**Comment by iadawn** [comment]
It is about including 'content' in the first two titles really. The one-word versus two-word does tweak my desire for neatness a little bit but it wouldn't be an issue if the two words were necessary.

**Comment by daniel-montalvo** [comment]
We are now clear on Module 2: Structure
