### ISSUE TITLE
[Module 2: Content Structure] Where to put 'titles'

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#486]
I think 'title' is much more of a clarity issue than a structure issue.

**Comment by bakkenb** [comment]
I thought to agree with this on first read. Then I thought, "Well, the title of the page is the first structural element that should be encountered before the H1." 

Not sure about my thinking on this but wanted to add it just in case it helps.

**Comment by daniel-montalvo** [comment]
Hey @iadawn @bakkenb 

I agree titles belong to both clarity and structure.

We may want to sign post this in the first module (Clarity) but discuss in detail in structure.

*Clarity aspects* -- Students should be able to write clear, descriptive, and concise page titles as well as put unique info first.

*Structural aspects* -- Students should be able to ensure appropriate markup for titles
We will discuss in next TF meeting.

**Comment by iadawn** [comment]
+1 on the clarity aim.

Not too sure on the markup for titles. I guess I always feel that markup is much more in the domain of devs than any other role. I know that the real world blends these things a lot more but I think clear lines between things will make the resource clearer.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Discussed in [15 March meeting](https://www.w3.org/2022/03/15-wai-curricula-minutes.html#item03)

Titles will be discussed from a clarity perspective in the first module.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clarity/
