### ISSUE TITLE
[Overall] Tool choices

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#487]
Not sure on the 'tools' section. Certainly someone needs to think about tooling but that cuts across content, design and developers and I don't recall if it was referenced in the other modules. Also, it is likely to be out of the control of many content authors.

Finally, content authors may not appreciate when a tool isn't supporting appropriate markup.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Much of the work that content authors do is based on their authoring tool, so TF thinks it makes sense to make a bit more emphasis than in other curricula.

We have qualified this a bit based on above input and [12 April TF discussion](https://www.w3.org/2022/04/12-wai-curricula-minutes.html#item01)

* Instructor competencies -- "Accessible Authoring tools" -> "Accessible content creation"
* Learning outcomes: "employ accessible authoring tools" -> "explain requirements for authoring tools to [...]" and specifics based on modules and topics.

For context, see
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/

Closing this. Feel free to reopen if needed.
