### ISSUE TITLE
[Module 4: Images] Overlap on alt text

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#488]
Alt text seems to be covered here and in Module 1

**Comment by bakkenb** [comment]
Agree. Added Issue #497  before reading this.

**Comment by daniel-montalvo** [comment]
Hey @iadawn  and @bakkenb 

I thought sign posting this in module 1 would be a good idea. Lack of alternative text makes content unclear if you don't see the image. Lack of iconography that complements text makes content unclear if you have trouble reading.

I do plan to discuss text alternatives in detail in module 3. 

Happy to remove if this is creating confusion.

**Comment by iadawn** [comment]
I think the challenge is just ensuring that the learning outcomes are sufficiently distinct but that they link together clearly enough. That would be where the confusion would arise.

**Comment by daniel-montalvo** [comment]
No reference to alt text in [module 1: Clear Content](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#learning-outcomes-for-module)  based on this and other comments.
