### ISSUE TITLE
[Module 4: Images] Charts

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#490]
Charts and graphs I think is a huge challenge. Alternative text alone is often not sufficient and longer descriptions are often necessary. Might need something to discuss that.

**Comment by daniel-montalvo** [comment]
Relating this also to #492

**Comment by daniel-montalvo** [comment]
First attempt to include the concept of "Data Visualizations".
  
Currently:

- [Module 3: Text Alternatives](https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/text-alternatives/) -- focuses on text alternatives for functional and informative images.
- [Module 4: Data Visualizations](https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/data-visualizations) -- focuses on different types of data visualizations, including complex images and data tables.
  - Separation of short and long descriptions
  - content authors to work with other roles to ensure perception and identification of short and long descriptions

**Comment by daniel-montalvo** [comment]
This separation seemed awkward for the TF in [yesterday's discussion](https://www.w3.org/2022/03/22-wai-curricula-minutes.html).

The TF appreciates consistency with the developers and designers curricula, where we tend to have module titles around specific pieces of content.

Will go back to "Images" and "Tables" and will try to include these mentions to "Data visualizations" where appropriate in these two.

**Comment by daniel-montalvo** [comment]
Addressed as per [EOWG Meeting 25 March](https://www.w3.org/2022/03/25-eo-minutes.html#t02)
