### ISSUE TITLE
[Module 5: Data Tables] Integrate data and graphs?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#491]
Just thinking about #490 and I wonder if it might be better to integrate data and charts somehow. Learning outcomes might be something like (very rough!): 

* explain how people with disabilities rely on appropriate markup to understand, navigate, and process information presented in data tables and charts
* collaborate with designers and developers to create patterns to present complex data structures
* designate the cell role, including header and data cells as well as cell scope
* provide regular data tables as alternatives to graphical representations of tabular data
* provide table descriptions to help users understand the purpose of complex tables
* ensure chart labels and legends clearly communicate the chart content

Dealing with simple tables could be included in structure.

**Comment by MicheleAWilliams-A11y** [comment]
Highly agree. I'll take it further and say the current Data Table module as it's written doesn't feel needed at all. Additionally, sometimes content creators are not designing a table at all (for example, if the data is coming from some already designed source like a school's grading system or a government science agency). I also like Sharron's idea of including "Data Viz" somewhere (#492).

**Comment by daniel-montalvo** [comment]
Relating this also to #492

**Comment by daniel-montalvo** [comment]
First attempt to include the concept of "Data Visualizations".

Currently:

- [Module 3: Text Alternatives](https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/text-alternatives/) -- focuses on text alternatives for functional and informative images.
- [Module 4: Data Visualizations](https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/data-visualizations) -- focuses on different types of data visualizations, including complex images and data tables.

**Comment by MicheleAWilliams-A11y** [comment]
I'm late to updating my comments but I like the new direction for the topics (and I know we've been discussing on EO calls as well but just putting that here to close the loop). Excited to see more!

**Comment by daniel-montalvo** [comment]
Addressed as per [EOWG Meeting 25 March](https://www.w3.org/2022/03/25-eo-minutes.html#t02)
