### ISSUE TITLE
[Module 6: Multimedia] Responsibility for player requirements 

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#493]
Not sure this is the content authors responsibility. There is a part of it that almost fits into Developer Modules > Rich Applications but that might be too vague. Perhaps it is more about working with developers and designers?

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 

This now reads:

<blockquote>

* identify related requirements for designers and developers to make the following perceivable and operable both visually and non-visually:
  * alternatives to multimedia content 
  * media players
  * media player controls

</blockquote>

This can be sufficient to teach content authors working on a larger team. I think we still need to come up with something for those who are just building a website with a CMS and have to choose what media player to use. They would argue there is no designer/developer to work with.

**Comment by iadawn** [comment]
I think I still have an issue with Content Authors taking a role in defining requirements for how media players function. The example you provide of someone who is using a CMS and choosing a media player could be equally applied to the other roles or someone without any of these roles at all, for example a small business owner.

**Comment by daniel-montalvo** [comment]
> I think I still have an issue with Content Authors taking a role in defining requirements for how media players function. The example you provide of someone who is using a CMS and choosing a media player could be equally applied to the other roles or someone without any of these roles at all, for example a small business owner.

This seems to be the position of the TF based on last discussions.

I am proposing to:

* keep the part on "identify related requirements for designers and developers" similarly to what we have in developers and designers curricula to cross reference other role's responsibilities
* withdraw from adding explicit LOs for content authors on defining requirements for media players

**Comment by daniel-montalvo** [comment]
Updating title and scope as per TF discussion.
https://www.w3.org/2022/05/17-wai-curricula-minutes.html

Closing. Related discussion for future reference is in w3c/wai-website#702
