### ISSUE TITLE
[Module 6: Labels and Instructions] Module name

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#494]
I wonder if 'Forms' might be more suitable for this. The module talks about error messages which people may miss if it is not called out specifically but 'forms' is much clearer.

This perhaps misses non-form labels and instructions. That might be better placed in clarity or structure under a section about sign-posting and/or calls-to-action?

**Comment by sharronrush** [comment]
Good idea to use Forms as the module title. +1

**Comment by daniel-montalvo** [comment]
Hey @iadawn @bakkenb and @sharronrush 

This somewhat relates to #478 

We will discuss in TF meeting and will update this accordingly.

**Comment by daniel-montalvo** [comment]
Changed to "forms"

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms
