### ISSUE TITLE
[Module 6: Labels and Instructions] Form field labels

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#495]
People may not connect 'controls' with 'form elements'. For example, I would think of a 'button' as a control but a text input field isn't. Might just be me though.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 

I agree.

We do need to provide specific examples of what we mean by "controls" for people to make this connection.

**Comment by daniel-montalvo** [comment]
Addressed in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/
