### ISSUE TITLE
[Module 6: Labels and Instructions] Qualifying coverage of error messages 

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#496]
The LO related to error messaging needs to make the point more clearly that error messaging must not only be "clear" but also be specific. It is clear to say "you must fix errors before proceeding" but it is not specific.  Unfortunately, this is a common practice and should be clearly explained and addressed within the module.

**Comment by bakkenb** [comment]
I was also thinking about this suggestion too. I agree with Sharron.

Along other lines, there should be some mention of working with the developer on this Learning Objective as well. "error messages and suggestions for correction when possible"... the suggestion may depend on the required format and format validation that the developer chooses to use when implementing a form.

**Comment by daniel-montalvo** [comment]
Hey @bakkenb  and @sharronrush 

Similarly to what we have in the designer modules, I added this in 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#learning-outcomes-for-module

To be polished later.

It now reads

<blockquote>

* collaborate with designers and developers to provide:
  * instructions about expected input types and formats
  * error messages that identify the field in error
  * suggestions for correction when possible based on the selected input formats and validation methods

</blockquote>
