### ISSUE TITLE
[Module 1: Content Clarity] - Ensure LO

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#498]
[Medium]

Under the "Ensure" Learning objective, the first bullet "content grouping and spacing to communicate sections" needs some qualification. 

Suggestions: 
 - adequate content grouping and spacing to communicate sections
 - content grouping and spacing are adequate to communicate sections
 - content grouping and spacing are adequate to clearly communicate sections

**Comment by daniel-montalvo** [comment]
Hey @bakkenb,

It seems like, in addition to rewording, we may need to relate grouping and spacing to structure rather than to clarity and readability.

Will close this and continue the discussion in #480
