### ISSUE TITLE
[Module 5: Data Tables] - Meaningful Presentation

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#499]
Would it be useful to add a learning objective about the sequence in which content is presented in a data table should be well thought out for all users including those with disabilities and how they my access and progress through content.

Content Authors can make some poor decisions up front in how data is presented in a table that can make it almost maddening to try and create sufficient headings or long descriptions for the data. Thinking through the layout and progression through the content may help content authors to simplify the table data and/or structure.

Just a thought.

**Comment by daniel-montalvo** [comment]
Hey @bakkenb 
Ref:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/

We have currently:

- "meaningful sequences for different user configurations and assistive technologies".
- "ensure people can understand content in data cells when navigating one cell at a time"

I am closing this as I think this is now much clearer. Feel free to reopen if you have further suggestions.
