### ISSUE TITLE
[Module 5: Multimedia] - Flashing

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#500]
Do we need to have a learning objective specifically about understanding how flashing content can be problematic for some. I know this is in the Designer modules, but Authors may actually author some scripts that include visuals of flashing content. 

Wondering if this should be an educational learning objective on the issues that flashing content can cause?

**Comment by daniel-montalvo** [comment]
Agreed.

I added something along the lines of "avoid flashing content" to be polished later in:
https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#learning-outcomes-for-module
