### ISSUE TITLE
[Module 1: Content Clarity] - Fonts and Contrast

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#501]
These LO's feel like they are the responsibility of a visual designer: 

- "easy to read and easy to understand font types"
- "appropriate contrast ratio for content"

Additionally, under the "Topic: Plain Language" section, this also feels out of place since a developer would have to ensure this piece:

- "employ easy to read font types and sizes, and ensure people can use their preferred font types and sizes when reading the content"

Seems like they would be left off, particularly since WCAG doesn't address font types. Perhaps this is trying to say that they will designate special markup (like what's a heading) but I think that's covered by the objective that says, "content grouping and spacing to communicate sections".

**Comment by daniel-montalvo** [comment]
That's good suggestion @MicheleAWilliams-A11y 

Writers would probably not want to say too much about font sizes and contrast. Someone who is creating a web page using a CMS for instance would probably want to have their say on these things. I think it's good that we make sure have these learning outcomes to adapt their teaching depending on the content authors.

I agree that this is probably overstated. Would you be comfortable if we soften this a bit, for example if we say something along the lines of

> collaborate with developers and designers to ensure adequate contrast ratio and easy-to-read font sizes
?
Thanks.

**Comment by daniel-montalvo** [comment]
Closing. Currently we say:

> * identify related requirements for designers and developers to ensure:
>  * appropriate contrast ratio for content
>  * easy to read and easy to understand font types and sizes

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clarity/#learning-outcomes-for-topic

**Comment by MicheleAWilliams-A11y** [comment]
Sorry I'm late but yes, this update makes sense. You're right that sometimes content authors work with the CMS which may then get into visual design a bit, but then they would hopefully take some courses on design as well 🙂!
