### ISSUE TITLE
[Module 3: Images] - What's a "Functional Image"?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#502]
Maybe it will be clearer later but I'm not sure what a "functional image" references - is that like an image button? If so, how does it reconcile with "images of text"? If not, how does it differ from an "informative image"?

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

This clasification is based on the [WAI Tutorials on Images](https://www.w3.org/WAI/tutorials/images/)

  The image button example you mention will be included in functional images.

I plan to differentiate this based on the type of text alternative that authors should provide:

- Functional images -- short, succinct text that conveys the action carried out by the interactive component
- Informative images -- Depending on context and type of info authors may need to either provide specific text alternative or rely on the adjacent text
- Image of text -- Should rarely be used, When used, ensure the same text that appears in the images can be accessed through genuine text
Does this clarify? Do you agree with these differences?

**Comment by daniel-montalvo** [comment]
Closing based on above comment and further [Task Force discussion](https://www.w3.org/2022/03/22-wai-curricula-minutes.html#t02)

**Comment by MicheleAWilliams-A11y** [comment]
I'm late to my comments but, yes, that makes more sense when listed with definitions like this. Thanks!
