### ISSUE TITLE
[Module 3: Images] - Should "icons" be part of technical writing?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#503]
This LO feels out of place: "provide icons and symbols that help people better understand text content". 

Overall anything to do with iconography feels like visual design but also the objective isn't really clear on what it's promoting (for instance, are we encouraging the use of icons?).

**Comment by MicheleAWilliams-A11y** [comment]
Okay, I think I'm having trouble understanding the scope. Is this "Content Authors" module about writing text or generally producing content? I see WCAG includes a lot of guidelines when you narrow by "Content Creation" but I've been thinking this is mostly aimed at technical writers. Clarity will help as I continue to review.

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y

My recollection from [18 February discussion](https://www.w3.org/2022/02/18-eo-minutes#item02) is that we did want to include content creators different from technical writers.

This LO is to address requirements mainly for users with cognitive disabilities that have trouble  reading text. See [user story](https://www.w3.org/TR/coga-usable/#symbols-pictographic-or-ideographic-that-represent-concepts-user-story)

I would agree that this is mainly a designer's responsibility. We have included it there. Is it worth figuring out a different approach from the content author's perspective?

We may discuss on Friday's meeting.

**Comment by eoncins** [comment]
In case it helps,
In terms of technical writing that includes icons there is https://www.w3.org/TR/coga-usable/ under section 1 "Summary" (Easy to Understand). Icons are used for understanding the different key points of the document. 

See also the following article on the importance of graphics in technical writing:
https://medium.com/technical-writing-is-easy/graphics-in-technical-writing-1c573441488b 

This might also apply to any type of content creator.

**Comment by daniel-montalvo** [comment]
Closing. Keep references to icons as per https://github.com/w3c/wai-curricula/issues/503#issuecomment-1063726784
