### ISSUE TITLE
[Module 3: Images] - Change #1 LO to "rely on the text alternatives"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#504]
The first LO reads as "explain how people with disabilities rely on images (including diagrams, charts, maps, and infographics) and their corresponding text alternatives to understand information"

This is awkwardly stated and seems to imply people rely on images (that is, the "diagrams, charts, etc." wording interrupts the main point). Since this is about content creation, I think it's okay to just say that people with disabilities rely on the text alternatives; all other populations who need something about the visuals to be clear (such as being able to recolor them) are likely addressed in the Designer modules.

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

That's now changed in
https://content-author-topics--wai-curricula.netlify.app/curricula/content-author-modules/images/
