### ISSUE TITLE
[Module 3: Forms] - Explaining accessible names

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#506]
One thing I'd love to see is an explanation of an accessible name, how they're used by AT (in particular screen readers and voice control systems), and help understanding when to use ARIA to supplement an accessible name (and when not to). Even though developers make the ultimate decisions, I find it helps when everyone understands these basics and make smart decisions upfront that lead to better code decisions down the line.

Maybe something like how to use "aria-describedby" for supplemental form information like date format, especially when a visual designer wants to put that information below the form element. Or perhaps using ARIA to supplement duplicate buttons, like duplicate "edit" and "delete" icon buttons on a summary page that are visually distinguished by their positioning but need programmatic distinction as well.

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

+1 to make clearer distinctions between accessible names and accessible dewscriptions for links, form fields, and form controls. This module seems like a good place to include this.

Not so sure that we should expect content authors to have knowledge on ARIA.

Do you think that authors themselves may decide which ARIA properties to use?

Do you think these decissions would require collaboration with the developer and the developer will have the final say on which ARIA properties to use?

**Comment by MicheleAWilliams-A11y** [comment]
Hey there, I know people feel like ARIA is a big topic but I think in the end it helps for everyone to know some of the basics like label, labelled by, and described by. In my experience, developers are often guessing at what attributes to use because designers and writers just stay in the lane of creating the look, for instance, without considering it will need in the code to be effective. So I would actually push for people to better understand a small piece of how it gets coded so people can know what's being interpreted and experienced. Certainly developers have final say but I'm a strong advocate in better collaborations - especially since there often aren't any and accessibility usually suffers for it. But, much like developers have the final say, you and the subgroup have final say on this one - LOL.

**Comment by daniel-montalvo** [comment]
Added in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#topic-labels

Teaching ideas, last bullet.
