### ISSUE TITLE
[Module 6: Multimedia] Splitting into Topics

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#507]
> Module Multimedia in Content Authors. What's the best way to split this into topics? Audio Content and Video Content? Captions, Descriptions, Transcripts, and Sign Language?

hummm... maybe:

* Audio Content and Video Content -- some is writing text ("script" and kinda "story boarding"), some maybe not directly content authors?, all before production
* Description -- this requires writing text
* Captions, Transcripts, Sign Language -- these are mostly putting existing information in a different form... um, except captions requires deciding what to write about the non-speech sounds.

possibly based on how much the content author actually writes and does?:
* Scripting Audio Content and Video Content -- the things "script" and maybe "story boarding"
* Description -- since it's writing
* Captions -- since some if it is writing
* Transcripts, Sign Language, Media Players, Recording and Producing Audio Content and Video Content -- since this is all "ensure" more than them needing to know lots about it

Not sure. Maybe above will lead others to better thoughts! :-)

**Comment by daniel-montalvo** [comment]
First attempt at splitting this module into topics is at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topics-to-teach

**Comment by daniel-montalvo** [comment]
Closing. No major concerns with current topic outline.
