### ISSUE TITLE
[Unit 1] "Tangible" is not the right word

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#51]
Lewis suggests:

> I don't think "tangible" is the correct word to use in this context "If you cannot bring tangible people, ..."

Changed to:

> If you cannot bring real people...

Here we emphasize the idea that instructors try to invite people to class, not show videos or any other material. If they can't, then these other materials may be used.

**Comment by hidde** [comment]
Was just going to suggest the same, glad it was already taken care of, thanks!
