### ISSUE TITLE
[Content Author Modules Overview Page] suggested edits (Editor's Discretion)

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#510]
Suggested edit for intro:
The content author modules provide a framework to use to create course work that:
    explains that accessibility relies upon clear content
    demonstrates how accessible content enables people with disabilities to effectively use websites and applications
    teaches accessible authoring techniques for:
        text
        forms
        images
        tables
        multimedia (including audio and video)

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Thanks for these suggestions. See my replies below.

> The content author modules provide a framework to use to create course work that:

I'd like to stick with what we have previously used for designers and developers "guide the creation of courses that" + use of plural verbs at start:

> * explains that accessibility relies upon clear content

Will do.

> demonstrates how accessible content enables people with disabilities to effectively use websites and applications

Will do.

> teaches accessible authoring techniques for: text forms images tables multimedia (including audio and video)

If I am not mistaken, this remains the same as it was.

**Comment by daniel-montalvo** [comment]
Closing, edits applied.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/
