### ISSUE TITLE
[Content Author, Module 1] Suggested edits (ED)

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#511]
"explain how clear, easy to understand, and easy to read content benefits accessibility"

benefits accessibility seems an awkward phrase to me though I don't feel strongly. My suggestion is this:

explain the accessibility benefits of providing content that is clear, easy to understand, and easy to read.

**Comment by daniel-montalvo** [comment]
Hey @SharronRush

Thanks for the suggestion. I took a pass at this and thought we could simplify this even more by saying:

> explain the accessibility benefits of providing clear, easy to understand, and easy to read content

**Comment by daniel-montalvo** [comment]
Closing, edits applied.
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#introduction
