### ISSUE TITLE
[Content Author Module1] Learning Objectives

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#512]
This is a great tag line in the video but does not quite have the same purpose here. If the focus is on disability access, it should stand alone - OK to add "benefits all" but in another bullet

Suggested edit:
- explain how clear, easy to understand, and easy to read content is essential for some people with disabilities to be able to effectively interact with the web
- note that clear content provides benefits to all users

**Comment by daniel-montalvo** [comment]
Hey @sharronrush

I thought this would play nicely with the videos and would help cross-reference our own resources. I disagree with putting the benefits to all on a separate learning outcome bullet. We would put "is essential for people with disabilities" and "benefits all" at the same level, and I think the main focus of these curricula should remain on people with disabilities. Good to mention "benefits all" somewhere in between, but not at a peer level IMO.

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 


Closing this issue. Feel free to reopen if you disagree with current approach.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#learning-outcomes-for-module
