### ISSUE TITLE
[Content Author Module1] Learning Objectives - need flexibility?

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#513]
This seems good but may be incomplete - should there be a mention of scalability, flexibility in font types and sizes?

identify related requirements for designers and developers to ensure:
    appropriate contrast ratio for content
    easy to read and easy to understand font types and sizes

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

thanks for raising this.

I am not clear what "flexibility and scalability" would add here.

I think we should focus this more to student being aware that users may choose their preferred font types and sizes, but we cover this in the designer modules already.

We could try to be more succinct here and have something like:

> * identify related requirements for designers and developers for:
>   * appropriate contrast ratio for content
>   * designs that adapt to different font types and sizes set by users

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Closing. I think the work described above addressed this. Feel free to reopen if you have further concerns.
