### ISSUE TITLE
[Content Author Module1] Topic: Easy to Understand

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#514]
This sentence contradicts itself - the language can be clearer:
Students should be able to:
- utilize clear language to support readability, clarity, and conciseness by using the following where possible: 

Suggested edit
Students should be able to:
- apply clear language to support readability and clarity using these techniques:
    clear and straightforward **language**
    short sentences
    active voice 

identify related requirements for designers and developers to provide easy to read font types  **[Should flexibility/scalability be mentioned here?]**

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Suggested edits applied.

I will track work on flexibility and scalability in #513
