### ISSUE TITLE
[Module 2: Structure] Intro

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#516]
Suggested rewrite:

* explore web page structures such as headings, paragraphs, sections, and lists, and explain their critical importance in orientation and navigation for people with disabilities

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Thanks for these suggestions.

> Suggested rewrite:
> 
>     * explore web page structures such as headings, paragraphs, sections, and lists, and explain their critical importance in orientation and navigation for people with disabilities

Where does this suggestion belong? It is not clear to me if this is for the "Introduction" or for the "Learning outcomes for module".

**Comment by daniel-montalvo** [comment]
Hello @sharronrush 

Th
is part has evolved since this issue was open. I am closing this now as it is now out of date.
