### ISSUE TITLE
[Module 1: Clear Content] Competencies

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#518]
One of the student's competencies is "Basic knowledge of: Content creation"
I would argue that "Content creation" is too generic and broad to be useful. 
What does it mean? The student should be able to use a tool to create content (e.g. a word processor, an image editor), or is it the student should know how to write or draw, or anything else?

Do we really need to include this competency?

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Thanks for bringing this to my attention. I agree this is now too generic. I was thinking about all you say, and we should possibly add more.

- writing
- editing
- proof reading
- publishing

We could have specifics per modules as well. I will update the live draft with these at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/


Just brainstorming for now on how these could look like. Let's discuss in TF meeting.

**Comment by daniel-montalvo** [comment]
Closing. This was resolved previously.
