### ISSUE TITLE
[Module 1: Clear Content] Learning outcome out of scope

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#519]
The following learning outcome "write text alternatives that clearly describe the purpose and communicate the content of images and other graphics" is out of scope of this module and should be addressed in the Images module.

**Comment by kakinney** [comment]
I had the same question about this learning outcome.  It seemed out of place.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte  and @kakinney 

@iadawn had a similar comment before. I thought this was a nice cross references to the module on images but it seems it is not working as expected. Will remove.
