### ISSUE TITLE
[Module 1: Clear Content] Topic: Terminology has content that seems more adequate for the Clear Content topic

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#520]
The first learning outcome states "utilize words that are easy to understand for the target audience".
The second teaching idea states "Reflect with students about terms that are difficult to understand based on audience and context"
The final idea to assess knowledge states "Practical — Give students a piece of text with terms that are difficult to understand. Ask them to either provide an explanation for such terms or to substitute them with terms that are easier."

All of these seem to me to be related with the "Clear Content" topic and not this one.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte

Thanks for catching this.

These clearly got mixed up. I will put them where they belong.

**Comment by daniel-montalvo** [comment]
These now are where they belong.
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-easy-to-understand-language
