### ISSUE TITLE
[Module 1: Clear Content] Topic: Titles and Links

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#521]
Not all links are text! Should we have something here to indicate that images which are links should have a descriptive accessible name, or is this covered only in the images module?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

I think we can have this in both. A brief mention in the first of the modules and a more detailed coverage in Module 4: Images, Topic Functional Images probably.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Ref:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/

I added more info about graphical buttons and links in

- Clear content > Titles and Link Text
  - Added teaching idea  
    "Reflect with students on the use of images as links, for example in logos. When using images as links, the image should contain an alternative text that describes the functionality of the link. Alternatives for images are discussed in [Content Author Module 4: Images, Topic Functional Images](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/images/#topic-functional-images)."
- Images > Functional Images
  - Rewritten second intro  paragraph:
    "Discuss different approaches to providing text alternatives for functional images, including for graphical buttons and links."
  - Added mention to images used as links in learning outcome:
    "produce appropriate markup for functional images, including for graphical buttons and links."

Closing now, feel free to reopen if you think something is missing or inaccurate.
