### ISSUE TITLE
[Module 3: Forms] Learning outcome about writing errors messages

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#523]
I'm missing a learning outcome on writing error messages. There is one about collaboration with designers and developers, but I believe there should be one specifically for content authors about writing.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

See 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#learning-outcomes-for-module

There is a specific LO now about error messages for content authors.

I took an overall pass at this based on @sharronrush  input on #529
