### ISSUE TITLE
[Module 3: Forms] Topic: Error messages

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#524]
I would like to have a learning outcome in the this topic, about collaboration with designers and developers to produce the errors messages. The content author is responsible for writing the messages. The designer is responsible for styling them and deciding where they appear in relation to the form or input field. And the developer is responsible for ensuring that they are programmatically associated with the input fields and form and that they are announced to assistive technologies.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

I suggest we add the following at the end of the list:

> * identify related requirements for
>   * designers to define visual and non-visual appearance of error messages
>   * developers to programmatically associate error messages with their corresponding form field or control

We already have "write error messages that identify the field in error and specify the cause of the error" before in the list, so I think these additions nicely point out the related requirements while underlying the specific authors responsibilities.

**Comment by daniel-montalvo** [comment]
added in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#topic-error-messages
