### ISSUE TITLE
[Module 4: Images] Learning outcome about decorative images but not topic addressing it

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#525]
There is a learning outcome about decorative images. But no topic addressing it. The informative images topic almost touches on this (when stating "Explain that these images are considered informative when they present information that is not otherwise available in the adjacent text.") but that does not cover everything about decorative images.

**Comment by daniel-montalvo** [comment]
Resolution
https://www.w3.org/2022/05/17-wai-curricula-minutes.html#item02

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Thanks.

Closing per above discussion and work.
