### ISSUE TITLE
[Module 5: Data Tables] Not enough content about complex tables

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#526]
I don't think complex tables are sufficiently covered in the module. 

There is this learning outcome: "collaborate with designers and developers to present multi-column content using CSS styles instead of layout tables". And there is not much more. 

Perhaps we could include teaching ideas in the "Table Header Cells" to demonstrate how complex tables are rendered by assistive technologies, what is needed to associate data tables with multiple headers, and anything else that is useful.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I took a pass at [Module 5: Data Tables, Topic Table Headers](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/#topic-table-headers) and added:

* Learning outcome: "specify the scope for headers that span multiple rows or columns"
* Teaching idea: "Give students tables with headers that span multiple rows and columns. Help them brainstorm which of the cells should be the header cells and how many rows and columns the headers should span. Emphasize that content authors should provide this information through an accessible authoring tool or through annotations for designers and developers to implement these tables."
* I think the above is covered by existing idea to assess knowledge: "Practical &mdash; Give students a table without designated headers. Ask them to tell which cells should be the header cells and how many rows and/or columns the headers should span. Assess how students recognize the header cells as well as their scope."

I don't think we should include more details as to how multirow and multicolumn headers are coded. I think we are good saying that these need to be provided through an authoring tool or by the necessary annotations for designers/developers.

Would these additions address your points?

**Comment by carlosapaduarte** [comment]
Hi @daniel-montalvo 

Thanks for the changes. I'm happy with these.
