### ISSUE TITLE
[Module 3: Forms] Intro (ED)

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#528]
I find the flow of the sentence to be interrupted by a list within a dependent clause. How about breaking it up like this:

Courses based on this module should:
* consider form fields and their controls, including edit boxes, list boxes, buttons, and other form interactions
* demonstrate how people with disabilities rely on clear labels and instructions to understand and successfully interact with web pages and applications that include forms
* explain accessibility requirements for labels and instructions for form fields and controls

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

That is good point. That first list bullet gets overly complicated. 

I am not sure about the use of the verb "consider" in this context. This is to communicate in one or two sentences what we expect courses to teach based on the module contents.

"Courses based on this module should consider" is a bit vague to me. Explain and demonstrate are the verbs we use for these sections on the other content author modules and curricula parts.

I propose putting the bit on "including edit boxes, list boxes, buttons, and other form interactions" at the end of the second list item, where it does not interrupt the sentence flow.

It would read:

> Courses based on this module should:
>
> * demonstrate how people with disabilities rely on clear labels and instructions to understand and interact with web pages and applications that include forms
> * explain accessibility requirements for form fields and controls, including edit boxes, list boxes, buttons, and other form interactions

**Comment by daniel-montalvo** [comment]
Addressed in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/
