### ISSUE TITLE
[Module 3: Forms] learning outcomes (ED)

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#529]
A suggested edit pass to simply the language:

Students should be able to 
* demonstrate understanding of a variety of form fields and controls. These may include edit boxes, list boxes, buttons, and and other form interactions  
* explain why people with disabilities rely on clear labels and meaningful instructions to understand and successfully interact with web pages and applications
*  write labels for form fields and controls that clearly communicate the form purpose
* provide meaningful instructions that support successful interaction with forms    
* write clear guidance for a multi-step process, including instructions about the current step and orientation to the total number of steps
* collaborate with designers and developers to include:
* * instructions about expected input types and formats
* * error messages that identify the form field and type of error 
* * suggestions for correction when possible based on the selected input formats and the validation methods in use

Note that there are four uses of "and" in this sentence - should be streamlined or use two bullets
* identify related requirements for designers and developers to ensure visual and non-visual perception and operation of forms and controls

Suggested:
* identify related requirements for collaborators to ensure successful operation of forms and controls by all users, including those who don't see the forms

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Thanks for these edits.

See my replies below.

> * demonstrate understanding of a variety of form fields and controls. These may include edit boxes, list boxes, buttons, and and other form interactions

Not sure if we should include this. I recall a similar discussion for the designer modules "Forms Design. EOWG agreed that this was out of scope for an accessibility curricula.

> * explain why people with disabilities rely on clear labels and meaningful instructions to understand and successfully interact with web pages and applications

Will do.

> * write labels for form fields and controls that clearly communicate the form purpose

Will do.

> * provide meaningful instructions that support successful interaction with forms

Instructions themselves may or may not make for a successful interaction. Success or failure may depend on other factors that may even be out of control from the content author.

I would be more comfortable with "help users interact"

> * write clear guidance for a multi-step process, including instructions about the current step and orientation to the total number of steps

Will do.

> * collaborate with designers and developers to include:
>   * instructions about expected input types and formats
>   * error messages that identify the form field and type of error
>   * suggestions for correction when possible based on the selected input formats and the validation methods in use
> Note that there are four uses of "and" in this sentence - should be streamlined or use two bullets

I will streamline this

> * identify related requirements for designers and developers to ensure visual and non-visual perception and operation of forms and controls
> 
> Suggested:
> 
> * identify related requirements for collaborators to ensure successful operation of forms and controls by all users, including those who don't see the forms

I would leave this one as-is.

* Why should we focus on a specific group of users here?
* The word "collaborators" is not consistent with our way to refer to other team members, as we do specify their role (designers, developers, and content authors).

**Comment by daniel-montalvo** [comment]
Edits applied based on theese commeents and also other issues.
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#learning-outcomes-for-module
