### ISSUE TITLE
[Unit 1 & 2] (medium) Competences section

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#53]
Unit 1 [Competences section](https://deploy-preview-50--wai-curricula.netlify.com/curricula/1-1/#competences)

> Instructors should prepare to bring in people with disabilities.

This is not a competency.

**Comment by shawna-slh** [comment]
Unit 2:
> Instructors should prepare to present the diverse abilities, tools and barriers.

This is not a competency.

**Comment by daniel-montalvo** [comment]
A little bit of background on this.

For these two units, the first outline of this section was:

> ## Prerequisites for Learners
> [Basic] Basic understanding of computers and the Web.
>
> ## Prerequisites for instructors
> [Basic] Basic understanding of web accessibility.

According to some comments received in [Previous surveys](https://www.w3.org/2002/09/wbs/35532/wai-curricula-1-2-tr/results)
> The only concern I had was the description of the instructor - Advanced (the only one listed?). It may put off people are new - they may feel as if they cannot instruct. Ideally you would have a seasoned consultant or persons working in the field or lived experience as instructors, but if it's going to be a resource to help build knowledge within organizations, the description feels limiting. 

This evolved into:

> ##Competences
> Learners
> Basic — Basic understanding of computers and the Web.
> Instructors
>  Medium — Good understanding of accessibility and inclusion. Some preparation is advised to present the diverse abilities, tools and barriers.
> Advanced — In-depth knowledge of accessibility principles and inclusive design, and expertise in working with people with different types of disabilities.

Then some changes were suggested in  #39 and in the live preview it looks like:

> ##Competences
> The following is a list of skills required for this unit.
> Students
> Basic — Basic understanding of computers and the Web.
> Instructors
> Medium — Good understanding of the interdependencies of web accessibility components.
> Advanced — In-depth knowledge of how people with different types of disabilities use the Web, 

It is not a competency that instructors at the [Medium] level would have. On the contrary, it is a suggestion of what an instructor who does not have this competencies needs to do to teach these units. It has the intention of opening the possibilities for not advanced instructors on the topic. Do we agree that we should open this to non-advanced instructors? If so, this might not be the correct wording and might need further clarification.

**Comment by nitedog** [comment]
I do not agree that instructor with too little expertise in working with people with different disabilities does this type of training with people with disabilities. They may not be able to set up the training well, moderate the interaction, or help students draw the correct conclusions.

According to #75 the two competences will be merged into one anyway. The statement "should prepare" is indeed not a competence and needs to be placed elsewhere on the page (I think it is already elsewhere but please check).

**Comment by daniel-montalvo** [comment]
Already addressed:

> # Unit 1
>
> ## Competencies
>
> Skills required for this unit:
>
> Students
>
> * Basic understanding of computers and the Web.
>
> Instructors
>
> * Good understanding of digital accessibility and inclusion.
>* In-depth knowledge of accessibility principles and inclusive design.
> * Expertise in working with people with different disabilities.
   > 
>
>
> # Unit 2
> 
> ## Competencies
>
> Skills required for this unit.
>
> Students
>
> * Basic understanding of computers and the Web.
>
> Instructors
>
> * Good understanding of the interdependencies of web accessibility components.
> * In-depth knowledge of how people with disabilities use the Web (including assistive technologies and adaptive strategies) and of accessibility principles.  
   >
