### ISSUE TITLE
[Module 3: Forms] Teaching Ideas for Topic: Labels

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#530]
I added the first two bullets and tried to streamline the language in the other ones.

* Review and verify that students have clarity about terms - forms, form controls, labels, etc
* Demonstrate the native accessibility of standard HTML form elements, and remind students that WAI-ARIA properties may only be required when building highly customized form fields and controls. Warn against overuse of ARIA.
* Demonstrate assistive technology interaction with form fields and controls. Use voice commands, keystrokes, and gestures to navigate to and operate specific types of form fields and controls. Explain that several groups of users require labels that clearly describe the purpose of the controls. Show how successful form interaction becomes difficult or impossible without such labels.
* Reflect with students about commonly used labels for form fields and controls. Typical examples might be “name”, “surname”, “address”, “phone”, “email”, and such. Explain that the label should be a unique, clear, and descriptive text that communicates the meaning, purpose, and intent of the form field or control.
* Explain how imagery can help users who do process text easily. They may rely on icons and symbols to more readily understand these labels. Emphasize that when content authors collaborate with designers and developers to complement text labels with imagery they will help these users process form fields and controls more effectively.
* Introduce accessible authoring tools that programmatically associate labels to the form field and control. Explain that some tools may refer to labels as “names” or similar terminology. Emphasize that content authors should provide these labels and the tool should associate the label to the corresponding form field and control.

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Thanks for bringing this up.

I applied your suggested edits to the existing bullets. I have questions around the two new bullets you proposed to add at the top. See below for questions.

> 
> * Review and verify that students have clarity about terms - forms, form controls, labels, etc

I am not sure that this is aligned with other similar teaching ideas that we have throughout. I would be more comfortable with having guidance for instructors on how they could review and verify that students have clarity on these terms. Maybe something like "explain the meaning of forms and for controls" or "introduce the terms form and form controls" would do better here.

> * Demonstrate the native accessibility of standard HTML form elements, and remind students that WAI-ARIA properties may only be required when building highly customized form fields and controls. Warn against overuse of ARIA.

I think this focuses too much on ARIA, as if this was oriented to teaching developers. What we had in the previous iterations seems more focused on content authors. I will apply your suggestion but will reorient this a little bit.

**Comment by daniel-montalvo** [comment]
Closing as I think this is resolved.

Feel free to reopen this is needed.
