### ISSUE TITLE
[Module 1: Clear Content] Titles and Link Text Learning Outcomes consistency

### ISSUE THREAD

**Issue by beltonTPG** [w3c/wai-curricula#531]
For the sake of consistency, I think we should update the following in the Titles and Link text Learning Outcomes:

- include relevant information about the link destination in the link text where possible, for example:
  - the target resource title
  - if the link will open a new window
  - the file type and format (when linking to a file)

To:

- include relevant information about the link destination in the link text where possible, for example:
  - the target resource title
  - that the link will open a new window (if appropriate)
  - the file type and format (when linking to a file)

**Comment by daniel-montalvo** [comment]
Thanks @beltonTPG 
Updated

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-titles-and-link-text
