### ISSUE TITLE
[Module 1: Clear Content] "terminology"

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-curricula#532]
I would suggest to avoid the word "terminology" under "Topics to teach" and maybe use "complex terms" which is also used as a bullet point.

**Comment by daniel-montalvo** [comment]
That's good suggestion. I will change accordingly.

 

 

 

--

 

Daniel Montalvo

 

Accessibility Education and Training Specialist

W3C/WAI

 

From: eoncins ***@***.***> 
Sent: Monday, May 9, 2022 6:17 PM
To: w3c/wai-curricula ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [w3c/wai-curricula] [Module 1: Clear Content] "terminology" (Issue #532)

 

I would suggest to avoid the word "terminology" under "Topics to teach" and maybe use "complex terms" which is also used as a bullet point.

**Comment by daniel-montalvo** [comment]
Updated at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-complex-terms
