### ISSUE TITLE
[Module 1: Clear Content] - Missplaced learning outcome?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#534]
It lists the following as a learning outcome but perhaps this was meant to be deleted?

> "write text alternatives that clearly describe the purpose and communicate the content of images and other graphics"

Seems this would go with "Images" and also isn't represented in the detailed course text.

**Comment by daniel-montalvo** [comment]
Thanks @MicheleAWilliams-A11y 

That's now removed from the current live draft at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#learning-outcomes-for-module
