### ISSUE TITLE
[Module 4: Images] - Missing "or" in Learning Outcomes for Informative Images

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#535]
The opening text for "Informative images" correctly states "They require a short, clear description provided in the image text alternative or through the adjacent text."

However, in the Learning Outcome bullet points, the following text needs an "or" added to ensure we're not saying do both of these:

provide quality text alternatives that convey the information in the images using:
- clear and descriptive text alternatives associated to the images
- adjacent text that conveys the same information as the image

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

Thanks for bringing this up.

Will read:

> * provide quality text alternatives that convey the information in the images using one of the following:
>   * clear and descriptive text alternatives associated to the images
>   * adjacent text that conveys the same information as the image
