### ISSUE TITLE
[Module 2: Structure] [Topic:  Paragraphs and Lists] Should definition lists be mentioned

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#537]
Pros:

- have now broader scope according to HTML Living Standard
- easy to implement in HTML / Markdown

Cons:

- not all major authoring tools support them
- they are neither widely used nor sufficiently understood by users

**Comment by beltonTPG** [comment]
I also believe that screen reader support is not there. I think JAWS flattens them to an unordered list.

BTW, the current terminology is "description list" - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl 
(I think it has changed 3 times)

**Comment by daniel-montalvo** [comment]
> I also believe that screen reader support is not there. I think JAWS flattens them to an unordered list.
> 
> BTW, the current terminology is "description list" - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl (I think it has changed 3 times)

Thanks for reminding me of this,  @beltonTPG 
We have "description lists" in our developer modules. So by the time we published them they had already made that change.

https://www.w3.org/WAI/curricula/developer-modules/page-structure/#topic-sections-of-content

If we add something in the ocntent author modules, we will definitely stick to that.

**Comment by bakkenb** [comment]
+1 to add.

**Comment by daniel-montalvo** [comment]
This is now added in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/#topic-paragraphs-and-lists
