### ISSUE TITLE
[Module 6: Multimedia] Interactive Transcripts

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-curricula#539]
I thought everything looked good. The only item I thought might be added was to perhaps have students view a site with interactive transcripts and captioning to see the benefits of captioning and transcripts for numerous audiences. For example both Harvard and MIT have such video libraries: see https://www.hsph.harvard.edu/voices/events/helen-clark-prime-minister-of-new-zealand-1999-2008-2/ as an example.

**Comment by shawna-slh** [comment]
For example, WAI videos have interactive transcripts, and captions :-)

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh  and @hkramer 

See updated topic at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-transcripts

Interactive transcripts are now in LOs and teaching ideas.

Creating an assessment around interactive transcripts would be out of scope for the content authors, as the functionality is provided by the media player.
