### ISSUE TITLE
[Module 1: Clear Content] Should we clarify "Easy to read" terminology?

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#540]
Thanks to @eoncins for bringing this to our attention.

Ref:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/

"Easy to read" in Europe is becoming more and more associated to the Easy-to-read Logo, which requires a validation by end-users. For context, see
https://www.inclusion-europe.eu/wp-content/uploads/2021/02/How-to-use-ETR-logo..pdf

The group has explored how to reword "easy to read" throughout the module, examples include:

- Introduction:
  - "demonstrate how people with disabilities rely on clear, easy to understand, and easy to read content to process information" -> "demonstrate how people with disabilities rely on clear and easy to understand content to process information"
  - "explain the accessibility benefits of providing clear, easy to understand, and easy to read content" -> "explain the accessibility benefits of providing clear and easy to understand content"
- Learning outcomes for module: "ensure sufficient contrast ratio as well as easy to read fonts to favor content readability" -> "ensure sufficient contrast ratio as well as fonts that favor readability to favor content readability"

However, the suggestions above feel awkward and possibly inaccurate, as "easy to read" and "easy to understand" are two different things.

Should we add a side comment that we are referring to "easy to read" as just the words, with no implication  to the easy-to-read logo?

**Comment by jade-mc** [comment]
What about changing it to readable?
I'd say in this context, easy to read and easy to understand are more or less the same thing...

**Comment by daniel-montalvo** [comment]
Closing. We will leave this as-is for now.
