### ISSUE TITLE
[Content Author Module 1: Clear Content]User Agent clarity? 

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-curricula#542]
Do we use the term "user agents" to refer to both browsers and email clients?  I know that user agents is the proper term, but after reading about simple language and use of jargon, I can't help but wonder if we can say something clearer like "...as much information as possible on the screen’s link text to maximize compatibility with web browsers, email clients, and assistive technologies."  Again, just to lessen the jargon.  Trying to take the clear content piece to heart. 

Just a thought - up for your discression.

**Comment by eoncins** [comment]
I agree that "user agents" might not be a term content authors are familiarized with and can be considered as a jargon.

**Comment by daniel-montalvo** [comment]
Hey @kakinney  @eoncins 
This is now changed to "browsers" where appropriate.
Topic Titles and Link Text, Teaching Ideas, Second and fifth bullet "user Agents" -> "Browsers" for clarity.
