### ISSUE TITLE
[Content Author Module 1: Clear Content] Missing learning objective: "utilize icons and symbols to complement text content"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#543]
This learning objective about icons and symbols appears in the list for Module 1 (Clear Content) but isn't part of the curriculum. Not sure where it was meant to appear (within this module or if it was meant to be part of the "Images" module) but the comments are missing and seem to be an important one to discuss where appropriate.

**Comment by eoncins** [comment]
I think that this learning outcome is more related to the use of images next to the text to help people understand what the text is about, which is part of the recommendations on Easy to Read/Easy to Understand language. An example would be: 1. Summary (Easy to Understand Language)" https://www.w3.org/TR/coga-usable/". 
Maybe some mention can be added on the Images module under "Topic: Functional Images".

**Comment by daniel-montalvo** [comment]
As agreed in [TF meeting 12 July](https://www.w3.org/2022/07/12-wai-curricula-minutes.html#item02), we will expand in topic "Easy to understand language".
