### ISSUE TITLE
[Content Author Module 1: Clear Content] "Page titles: topic better suited for "Structure" module

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#544]
The topic of page titles seems to be fit better under "Structure" than "Clear Content". That is, it seems to better line up with topics such as headings, paragraphs, lists, and tables of contents, rather than topics such as not using jargon and spelling out abbreviations. Module 2 also explicitly mentions "navigation" for which page titles are just as vital as any other feature.

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

The TF has revisited this topic in the  [5 July meeting](https://www.w3.org/2022/07/05-wai-curricula-minutes.html#t06).

Technically it is true that these two belong to structure in terms of development and design. But in this particular curricula which is devoted to teaching content authors, the TF feels we need to emphasize that one thing is the structural part and another thing is the content that is provided by authors.

In addition, titles and link text would only contribute to better navigation and orientation if their content is accessible. There could be technically correct markup but, if the content of the title is not meaningful, it still won't let users determine what the page is about.

To reinforce this, in the developer part, however, links and titles are discussed in [1: Page Structure](https://www.w3.org/WAI/curricula/developer-modules/page-structure/). And there we have a specific learning outcome to cross reference the content author moddules:

> describe related requirements for content authors to write meaningful link texts and page titles

We are proposing to keep this topic where it is now, for the reasons explained above.

Would you be comfortable with this proposal?

**Comment by MicheleAWilliams-A11y** [comment]
Hi there, I don't have capacity to review this again so please go forward with what the committee decides - this wasn't a blocker issue. Thanks for the consideration!

**Comment by daniel-montalvo** [comment]
Thanks @MicheleAWilliams-A11y 
Will close as explained above.
