### ISSUE TITLE
[Content Author Module 1: Clear Content] Emphasize color as part of this section

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#545]
Color contrast doesn't seem to fit into the overall focus of this "Clear Content" module, but particularly when the emphasis is "clear, easy to understand, and easy to read". Perhaps instead of saying "content" this can say "language and visual presentation" as in, "demonstrate how people with disabilities rely on clear, easy to understand, and easy to read language and visual presentation to process information". Or maybe instead of "language" say "wording"? Just some suggestions to make it more clear that this will talk about color contrast and not just wording.

**Comment by daniel-montalvo** [comment]
Thanks @MicheleAWilliams-A11y 
That's now addressed.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/
