### ISSUE TITLE
[Unit 1] (medium) Teaching Ideas not clear

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#55]
In [Teaching Ideas](https://deploy-preview-50--wai-curricula.netlify.com/curricula/1-1/#teaching-ideas) section:

> Relate the experiences of how people with disabilities browse the Web to design accessibility features, barriers, and the functionality of assistive technologies and adaptive strategies. 

I don't understand what this is trying to say.

**Comment by daniel-montalvo** [comment]
Changed to:

> * Relate accessibility features and barriers to the performance of assistive technologies and adaptive strategies. For an introduction to certain assistive tools and adaptive strategies, refer to the resource [Tools and Techniques](https://www.w3.org/WAI/people-use-web/tools-techniques/).

**Comment by shawna-slh** [comment]
Sorry. This is still not clear to me: "Relate accessibility features and barriers to the performance of assistive technologies and adaptive strategies."

**Comment by nitedog** [comment]
Maybe something like "explain how different accessibility features and barriers impact use of the content with assistive technologies and adaptive strategies"?

**Comment by daniel-montalvo** [comment]
Now changed to:

> * Explain how different accessibility features and barriers affect use of the content with assistive technologies and adaptive strategies. For an introduction to certain assistive tools and adaptive strategies, refer to [Tools and Techniques](https://www.w3.org/WAI/people-use-web/tools-techniques/).

Following @nitedog 's suggestions.

@slhenry  is it clearer now?

**Comment by daniel-montalvo** [comment]
Closing, since no further comments have been received.
