### ISSUE TITLE
[Content Author Module 6: Multimedia] Unclear learning outcome within Planning Audio and Video

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#550]
I'm unclear what this means: "provide rationale for not including one or more alternatives to multimedia content"

Is this a typo? If not, does this mean explain why certain alternatives don't make sense for certain populations? I'm not certain what it's trying to convey but right now it seems to say that there's sometimes situations where you don't need to provide alternatives.

[Update] Okay, later as I read the examples I see that this is something like telling people there are no alternatives. Is this, for instance, like telling people a video has no sound? Overall it's not clear from the way these are explained what I would do with this as an instructor.

> Present examples of inaccessible audio and video content. Discuss with students which alternatives they would include to make them accessible. Explain that it is best practice to provide rationale for when not including a specific alternative. This helps users save time and avoid frustrations.

**Comment by shawna-slh** [comment]
I also stumbled with:
> provide rationale for not including one or more alternatives to multimedia content
> Explain that it is best practice to provide rationale for when not including a specific alternative.

I appreciate @MicheleAWilliams-A11y idea for rewording -- and I think we need to go even further with the explanation.
> Explain that it is best practice to provide rationale for when not including a specific alternative. 

I'm afraid most readers/instructors/learners will think they're not providing it because users don't need it (and they just don't understand users needs), or because it's not required by their policies. That "rationale" is just annoying!

And that's not what you're saying here. I now understand you're getting at this: https://www.w3.org/WAI/media/av/planning/#none

You need to say that more clearly, and probably good to include that link.

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh and @MicheleAWilliams-A11y

To clarify meaning and to align more with resource [Inform users when not needed](https://www.w3.org/WAI/media/av/planning/#none), I propose:

Learning outcome:

* "explain why non-substantive audio and video content does not need alternatives"

Teaching idea:

* "Present examples of inaccessible audio and video content. Discuss with students which alternatives they would include to make them accessible. Explain that it is best practice to explain why non-substantive audio and video content does not need alternatives. This helps users save time and avoid frustrations. For details, see [Inform users when not needed](https://www.w3.org/WAI/media/av/planning/#none)."

Assessment:
* "Practical &mdash; Give students a piece of audio and video content. Ask them to determine which alternatives to include and which not to include, as well as to explain why they decided not to include a specific alternative. Assess how students determine the required alternatives to audio and video content as well as how they explain why they decided not to include a specific alternative."

See live preview at:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-planning-audio-and-video

Would that address your concerns?

**Comment by shawna-slh** [comment]
> Would that address your concerns?

Sure, thanks.

**Comment by MicheleAWilliams-A11y** [comment]
Same here, thanks!
