### ISSUE TITLE
[Content Author Module 6: Multimedia] Clarifying caption creation differences

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#551]
Under Learning Outcomes for Captions, it states:

> ensure availability of accurate captions by using one of the following:
> - a caption file
> - automatically generated captions that have been checked for quality and accuracy

Simply saying "a caption file" doesn't convey a difference in how they would relate to accuracy. I think perhaps you mean a "human-generated" caption file or perhaps one created from a script?

**Comment by daniel-montalvo** [comment]
Resolves #567

**Comment by daniel-montalvo** [comment]
Hey @MicheleAWilliams-A11y 

According to #567 
It is not much about different ways of creating captions but about the fact that automatically-generated captions are not sufficient.

I have updated the draft accordingly at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-captionssubtitles

Closing as per #567
