### ISSUE TITLE
[Content Author Module 2: Structure] left align content

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-curricula#553]
For consideration, most easy to read/understand guidelines recommend to "left align" content. This is something missing in this section and could be added as a learning outcome and/or as under Topic: Orientation and Navigation

**Comment by daniel-montalvo** [comment]
Hey @eoncins 

That's now in

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-visual-appearance

It's true it could be also in Orientation and Navigation, but I think heere it fits better.

Is this OK with you?

**Comment by eoncins** [comment]
Hello @daniel-montalvo thanks for addressing the issue.
