### ISSUE TITLE
[Content Author Module 5: Data Tables] Avoid merging cells

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-curricula#554]
For editor's discretion: maybe adding a mention: avoid merge cells under Teaching ideas > Table Data Cells could be useful.

**Comment by daniel-montalvo** [comment]
Hey @eoncins 

Thanks for this suggestion.

I'd say we currently have this already, but I think you are raising this because it may not be sufficiently clear.

I propose:

> * Explain that data cells contain information of a specific type of data. Emphasize that it is good practice to keep tables as simple as possible, providing one specific type of data in one column or row. Explain that merged cells are problematic for some people that have difficulty to understand the cells scope.

->

> Explain that data cells contain information of a specific type of data. Demonstrate good practices to create accessible tables. These include making tables as simple as possible as well as avoiding merged cells where possible.

Would this address your concern?

**Comment by eoncins** [comment]
Hey @daniel-montalvo yes it does. Thanks for the update.
