### ISSUE TITLE
[Content Author Module 6: Multimedia] [low] Audio Content and Video Content guidance missing from summary and overall outcomes?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#556]
The guidance in Audio Content and Video Content <https://www.w3.org/WAI/media/av/av-content/> seems included under “Topic: Planning Audio and Video” – however,
1. It doesn’t seem clearly covered in the Summary at the top, nor in the overall Learning Outcomes for Module
2. I’m not sure “Planning” is sufficient to cover that? But maybe it’s fine!

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

Thanks for bringing this to my attention.

It seems the only place in the learning outcomes for module where some of this is mentioned is in

<blockquote>

* explain the following best practices for accessible audio and video content:
  * use clear and easy to understand speech
  * ensure sufficient contrast ratios for video text
  * minimize background audio and overall distractions where possible
  * integrate description in video scripts to minimize the need for separate description at a later phase
  * provide redundancy for different sensory characteristics to help different groups of users understand the content

</blockquote>

Some in the TF were hesitant to go beyond this in the learning outcomes for module. Not all content authors would be involved in planning audio and video content. Even if they are, most of it will be out of their direct control.

We do, however, provide a specific topic dealing with this for instructors to teach these contents  to students who do plan for audio and video content regularly.

Does this explanation address your concerns?

**Comment by shawna-slh** [comment]
Sure, thanks!
