### ISSUE TITLE
[Content Author Module 6: Multimedia] split up complex sentence

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#557]
> * demonstrate how people with disabilities rely on alternatives to multimedia content, including transcripts, description of visual information (also known as audio description, video description, or described video), captions (also known as subtitles), and sign language(s), to understand information contained in audio and video content

->
* demonstrate how people with disabilities rely on alternatives to multimedia content to understand information contained in audio and video content
* cover transcripts, description of visual information (also called audio description, video description, or described video), captions (also known as subtitles), and sign languages

rationale-- I totally got lost in the long, complicated list of "including..." and thought ", to understand information contained in audio and video content" was still part of that list

**Comment by daniel-montalvo** [comment]
Done in 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#introduction
