### ISSUE TITLE
[Content Author Module 6: Multimedia] unclear wording "match the video and audio information when possible ..."

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#558]
“match the video and audio information when possible to help different groups of users understand the content”
- not really clear what this means

**Comment by daniel-montalvo** [comment]
> “match the video and audio information when possible to help different groups of users understand the content”
> 
> * not really clear what this means

This is to cover
https://www.w3.org/WAI/media/av/av-content/#sensory

"Provide redundancy for sensory characteristics" was not sufficiently understood in TF. So we tried to substitute it with "match the video and audio information when possible"

Is this now clearer? What other suggestions do you have?

**Comment by carlosapaduarte** [comment]
It was also not clear for me. I needed to assume that you were describing redundancy but was not sure until I saw your comment, Daniel. I would support improving it. What about

> Provide equivalent information in both audio and video when possible to help different groups of users understand the content.

**Comment by shawna-slh** [comment]
I appreciate trying to simply wording; however, I don't think that covers it. If the video visually shows the red end and the audio says "the red end", that still is not accessible to some who cannot distinguish red and green ('colorblind').

It seems that instructors *should* know Success Criterion 1.3.3: Sensory Characteristics !

Is there a reason not to use that wording from WCAG and link to https://www.w3.org/WAI/media/av/av-content/#sensory &/or https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html ?

**Comment by daniel-montalvo** [comment]
thanks @shawna-slh

We previously had something along these lines, but the TF was struggling with the term "sensory characteristics" as it is very WCAG specific. 

Some possibilities may include:

> * provide instructions that rely on several sensory characteristics, including auditory and visual

Similar to what we have before and is in the media resource, but not liked by some people because it's jargon.

> * provide additional instructions when possible for people who cannot see the video or cannot hear the audio

More to the point of including information that can be understood without hearing or seeing the content, but without tall those passives.

**Comment by shawna-slh** [comment]
I appreciate that ‘sensory characteristics’ is WCAG-jargony. However, I feel pretty strongly that all instructors should know that terminology and all students should learn it.

WCAG is the backbone of this WAI curricula, yes? It is the short-name of a Level A success criteria “1.3.3: Sensory Characteristics”.

I think the alternative wording options are less clear and/or not accurate.

**Comment by daniel-montalvo** [comment]
Proposal. Change to:

> provide redundancy for different sensory characteristics to help different groups of users understand the content

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#learning-outcomes-for-module
