### ISSUE TITLE
[Content Author Module 6: Multimedia] all disabilities

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#559]
> “identify related requirements for designers and developers to support visual and non-visual perception and operation of:”

shouldn’t this cover more than ‘visual and non-visual’? what about hearing, low vision, etc?

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh 

"visual and non-visual perception and operation" is a short-hand for "perceived and operated visually and non-visually", which was flagged for being lengthy. 

With this we mean to include all of what you mentioned above.

Do you think if we say just "perception and operation" instead of "visual and non-visual perception and operation" this will be sufficiently understood?

**Comment by shawna-slh** [comment]
With more context:

> Students should be able to:
> ...
> * identify related requirements for designers and developers to support visual and non-visual perception and operation of:
>   * alternatives to multimedia content
>   * media player controls

Even more than I said before, that doesn't clearly cover visual non-mouse users, which is important for media player controls.

/me plays with wording:

> identify related requirements for designers and developers to support perception and operation of:

humm, no, still passive. how about:

> identify related requirements for designers and developers to make accessible:

That is much simpler. Do you think perception and operation is important here? Is so, maybe:

> identify related requirements for designers and developers to make perceivable and operable:

(I know a little jargony, yet again, since those are core WCAG concepts, I think Ok.)

**Comment by daniel-montalvo** [comment]
Changed to:

> * identify related requirements for designers and developers to make accessible:
>   * alternatives to multimedia content 
>   * media player controls

I think we can assume that for details on how to make them accessible instructors would need to get to the other parts.

- [x] Look at similar occurrences of "perception and operation" in other modules and update them according to this.
