### ISSUE TITLE
[Unit 1] (low) Tip on tone for future topics.

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#56]
In context - paragraph above [Homework Ideas](https://deploy-preview-50--wai-curricula.netlify.com/curricula/1-1/#homework-ideas-1)

> Tip: This topic sets the tone for future topics on the components of web accessibility, its business case, the applicable standards, and some planning and managing strategies. To prepare students for this further knowledge, emphasize that accessibility focuses primarily on the usability for people with disabilities and describe how accessibility characteristics benefit all users, e.g., mobile device users or users not fluent in the language.

I'm not sure why this is a tip? Why is it important? Won't instructors figure that out when looking at the rest of the module?

If you do think it's important, in my pull request, I suggested changing the first sentence to:
> Note: This topic sets the tone for future topics on the components of web accessibility, the business case, standards, and planning and managing strategies. 

The rest of it seems unnecessary and somewhat redundant with what's above:
> To prepare students for later topics, emphasize that accessibility focuses on usability for people with disabilities and describe how accessibility characteristics benefit all users, e.g., mobile device users and users not fluent in the language.

I suggest just making sure that's well covered in the main sections and not having it in this Tip/Note.

**Comment by daniel-montalvo** [comment]
Two things:
1. this paragraph wanted to outline future topics of this module and make teachers aware of them. Ideally this is done in the introductory page for the module. I see this as a nice reminder of what is to come, especially for people who may land in this particular page without the general context. 
2. The paragraph also tries to emphasize that "accessibility is about usability for people with disabilities".

If we all agree that these two aspects are well covered in the rest of the topics/units/module, we could happily remove it.

**Comment by shawna-slh** [comment]
a few more thoughts:

> I see this as a nice reminder of what is to come, especially for people who may land in this particular page without the general context.

For many resources we do need to consider that people will land on specific pages without being aware of the information on the related pages. For this resource, I think it is less of an issue. Anyone really using the sub-pages of this resource should be aware of the rest of this resource.

> The paragraph also tries to emphasize that "accessibility is about usability for people with disabilities".

Which I strongly support! It should be clear throughout the sections. :-)

**Comment by daniel-montalvo** [comment]
> > The paragraph also tries to emphasize that "accessibility is about usability for people with disabilities".
> 
> Which I strongly support! It should be clear throughout the sections. :-)

I think [Topic Scope of Web Accessibility](https://w3c.github.io/wai-curricula/curricula/1-1/#topic-scope-of-web-accessibility) is in charge of this among other things. Note that this link takes you to the preview on master, which still has not the other changes in the live preview.


In the teaching ideas for this topic we have:

> * Define usability as the discipline in charge of designing products to be effective, efficient, and satisfying. Describe some overlaps in usability
and accessibility. Explain that accessibility is needed to cover those aspects from the perspective of people with disabilities.

The last sentence there, IMO, condenses this idea.

I guess the main point here is we should remove this paragraph if it does not add very much to what we have already.
