### ISSUE TITLE
[Content Author Module 6: Multimedia] links to media resource

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#561]
1.
> “Introduce different user needs for audio and video content.”

Should this include a pointer to Understand the User Needs and Experiences of People with Disabilities <https://www.w3.org/WAI/media/av/users-orgs/#understand-the-user-needs-and-experiences-of-people-with-disabilities> ?

2.
> “Discuss best practices for audio and video content, including clear audio and speech, sufficient contrast ratios, and speaker visibility. For details, see Planning Audio and Video < https://wai-curricula.netlify.app/media/av/planning/>.”

I think the pointer you want here is Audio Content and Video Content <https://www.w3.org/WAI/media/av/av-content/> (not Planning).

3.
> Teaching Ideas for Topic
> Demonstrate accessibility best practices for creating audio and video content. These include clear speech, language, and audio, sufficient contrast ratio for videos, and speakers visibility.

Add link to Audio Content and Video Content  https://www.w3.org/WAI/media/av/av-content/

**Comment by daniel-montalvo** [comment]
Done in 

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-planning-audio-and-video
