### ISSUE TITLE
[Content Author Module 6: Multimedia] not limited by regulations and policies

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#564]
> Research — Ask students to research governmental regulations that may apply in their region for audio and video content. Then ask students to specify the accessibility requirements for different types of audio and video content. Assess how students determine the accessibility requirements for different types of audio and video content based on governmental regulations and other policy requirements.

I think we want to strongly encourage meeting use needs beyond regulations and policy requirements. Therefore, maybe delete this – or, better yet, have students explain users needs beyond a chosen regulation?

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh 

Changed to:

> Research &mdash; Ask students to research government regulations that may apply in their region for audio and video content. Then ask students to explain which user needs for audio and video content are covered and which are not covered in a specific government regulation or policy. Assess how students specify the user needs that specific government regulations and other policy requirements may not cover.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-planning-audio-and-video
 
1. Find government regulations and policies that apply
2. Specify which user needs are and are not cover in these policies (which implies explaining user needs overall)

Is this clear now?
