### ISSUE TITLE
[Content Author Module 6: Multimedia] Descriptive transcripts needed to meet user needs

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#565]
> Topic: Transcripts

In our media resource, we say: “Descriptive transcripts are required to provide video content to people who are both Deaf and blind.” and “Descriptive transcripts for videos: are needed for most videos to be accessible to people who are “Deaf-blind” and “Ideally you provide a descriptive transcript, and then you do not need a separate basic transcript.”

I’d like a re-write of the Topic: Transcripts section to reflect that &mdash; that is, yeah, you need to know the difference between basic and descriptive -- then you need to know to provide descriptive all the time 'cause it's needed to meet user needs and it's not that much work.

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh 

Will do.

Other comments seem to go in this direction too.

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

Updated topic is at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-transcripts
Intro, second paragraph:

> People who are both Deaf and blind require descriptive transcripts to understand the information in video content. Emphasize that creating descriptive transcripts is easier when starting with existing captions and description. For details, see [Transcripts](https://www.w3.org/WAI/media/av/transcripts/).

**Comment by shawna-slh** [comment]
ok!
