### ISSUE TITLE
[Content Author Module 6: Multimedia] [high] automatic captions

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#567]
> “automatically generated captions that have been checked for quality and accuracy”

No. See https://www.w3.org/WAI/media/av/captions/#automatic-captions-are-not-sufficient which says: “Automatically-generated captions do not meet user needs or accessibility requirements, unless they are confirmed to be fully accurate. Usually they need significant editing.”
The learning outcome should be that students understand that automatically-generated captions are *not* sufficient!

> If relying on automatically-generated captions, content authors must ensure these captions are accurate and convey all the relevant information.”

-> “If starting with automatically-generated captions, content authors must carefully edit them to be accurate with appropriate punctuation, etc.”

**Comment by daniel-montalvo** [comment]
Resolvees #551

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

Addressed.

Updated draft is at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-captionssubtitles

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 


Based on previous discussions, /me Thinks this is done.

Closing, feel free to reopen if needed.
