### ISSUE TITLE
[all] (low) [Wordsmith] aims -> goals

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#57]
> The aims of this unit are to:

To me "goals" would be stronger than "aims".

> The goals of this unit are to:

I think others have better idea what is common in academia, formal instructional design, etc.
and I'm happy to go with their expertise.

**Comment by shawna-slh** [comment]
@eoncins & @hkramer , your thoughts?

**Comment by daniel-montalvo** [comment]
A little bit of background on this.

I took the decision to stop using "objectives" in the introduction after reading this passage from "A [Learning outcomes book"](https://cora.ucc.ie/bitstream/handle/10468/1613/A%20Learning%20Outcomes%20Book%20D%20Kennedy.pdf?sequence=1), from D Kenedy, that @eoncins pointed me to very nicely.

> What is the difference between aims, objectives and learning outcomes? 
> The aim of a module or programme is a broad general statement of the teaching intention, i.e. it indicates what the teacher intends to cover in a block of learning. Aims are usually written from the teacher’s point of view to indicate the general content and direction of the module. For example, the aim of a module could be “to introduce students to the basic principles of atomic structure” or “to provide a general introduction to the history of Ireland in the twentieth century”. 
> The objective of a module or programme is usually a specific statement of teaching intention, i.e. it indicates one of the specific areas that the teacher intends to cover in a block of learning. For example, one of the objectives of a module could be that “students would understand the impacts and effects of behaviours and lifestyles on both the local and global environments”. (In some contexts, objectives are also referred to as goals.) 
> Thus, the aim of a module gives the broad purpose or general teaching intention of the module whilst the objective gives more specific information about what the teaching of the module hopes to achieve. 
> One of the problems caused by the use of objectives is that sometimes they are written in terms of teaching intention and other times they are written in terms of expected learning, i.e. there is confusion in the literature in terms of whether objectives belong to the teacher-centred approach or the outcome-based approach. The situation is nicely summarised by Moon ( 00 ) as follows: 

> > Basically the term ‘objective’ tends to complicate the situation, because objectives may be written in the terms of teaching intention or expected learning… This means that some descriptions are of the teaching in the module and some are of the learning… This general lack of agreement as to the format of objectives is a complication, and justifies the abandonment of the use of the term ‘objective’ in the description of modules or programmes. 
(Moon J., 00 ) 

> Most teachers who have worked on the development of objectives for modules or programmes would have encountered the above problem. One of the great advantages of learning outcomes is that they are clear statements of what the 
student is expected to achieve and how he or she is expected to demonstrate that achievement. Thus, learning outcomes are more precise, easier to compose and far clearer than objectives. From one perspective, learning outcomes can be considered as a sort of “common currency” that assist modules and programmes to be more transparent at both local level and at an international level. 

We have decided here to have a more teacher centered introductory paragraph (aims) and then the learning outcomes approach, so we should abandon the term objective. As goals seems tied to objectives
> In some contexts, "objectives" are also referred as "goals". 

So I thought goals would be a conflicting word in this context.
Open to more thoughts on this, though.

**Comment by yatil** [comment]
+1 for aims for broad outcomes, goals are more concrete for me.

**Comment by yatil** [comment]
After discussing in our teleconference meeting, I suggested to simplify the sentences to neither include goal(s) or aim(s).

**Comment by daniel-montalvo** [comment]
Changed to:

> This unit:
> • raises awareness of how people with disabilities use websites and applications
> • introduces core concepts of digital accessibility
> • explains related terms such as usability, user experience, and inclusive design

Expecting to follow a similar pattern for the rest of the units.
