### ISSUE TITLE
[Content Author Modules] footers & acks

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#571]
Update the footers.

* [ ] Check if Shadi wants to be listed as editor on these modules
* [ ] Update https://wai-curricula.netlify.app/curricula/acknowledgements/ <br> e.g., maybe under “Contributing EOWG Participants” add [Kevin White](https://github.com/w3c/wai-curricula/issues?q=author%3Aiadawn+)? Michele Williams? others?

**Comment by daniel-montalvo** [comment]
Thanks for raising this @shawna-slh . 

I will label this as To do before publishing.

**Comment by remibetin** [comment]
@shawna-slh @daniel-montalvo Seems done? See for example:
- https://www.w3.org/WAI/curricula/acknowledgements/
- footer in https://www.w3.org/WAI/curricula/foundation-modules/what-is-web-accessibility/

**Comment by remibetin** [comment]
As agreed with @daniel-montalvo, I am closing this issue.
