### ISSUE TITLE
[Content Author Module 6: Multimedia] LO in Topic Transcripts and Descriptions

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#574]
One of the LO in the Transcripts topic reads
> ensure inclusion of transcripts for audio and video content when required

For me it's not clear how is this a LO. The student is expected to learn to "ensure inclusion of transcripts when required"? Shouldn't the student, instead, be expected to learn to "identify when transcripts are required"?

**Comment by carlosapaduarte** [comment]
I found another similar instance in the Description of Visual Information topic

> ensure description of visual information is available when required

I don't understand how "ensuring a description is available" is a LO. This seems management related. Shouldn't the student learn to "describe visual information when required"?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

There are actually several instances of this "ensure [...] is available" so I'd say this affects the whole module.

Will change the title accordingly and work on a proposal based on your comments above.

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

Changed to:

For transcripts

> * identify audio and video content that requires transcripts

For descriptions

> * identify video content that requires description of visual information

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/
