### ISSUE TITLE
[Content Author Module 5: Data Tables] LO about layout tables

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#575]
There is a LO for this Module that reads 

> collaborate with designers and developers to present multi-column content using CSS styles instead of layout tables

I find this is somewhat out-of-scope for a module on data tables focusing on content authors. Do we really want to require the student to understand how designers and developers use CSS for layout purposes? Wouldn't it be preferable to require the student to "identify situations where tables are being, incorrectly, used for layout purposes", if we wish to address this at all in this module?

**Comment by carlosapaduarte** [comment]
Furthermore, none of the topics in the module address this LO, so I'm suggesting to remove it.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

That's now removed.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/#learning-outcomes-for-module

**Comment by daniel-montalvo** [comment]
Revisiting as per Dónal Fitzpatrick comment in [survey](https://www.w3.org/2002/09/wbs/35532/curriculaContentAuthorsMonkeReview/results#xq9).

> In the 'Learning Outcomes for module' it states:
> "collaborate with designers and developers to present multi-column content using CSS styles instead of layout tables".
> This is an excellent addition, however I submit that it is not just CSS styles which are utilised in the multi-column layout proposed. Inclusion
> of appropriate semantics also facilitates presentation of content in this fashion. I suggest consideration be given to explicit reference to
> markup required in conjunction with CSS to achieve this.

The TF felt this was getting too much into specifics for developers and designers, so decided to remove this. For background, see
https://github.com/w3c/wai-curricula/issues/575

Would you object to this removal?

> I wonder whether it might be useful to consider inclusion of material in this module which outlines the differences between a data table and
> a layout-table. I note, for example, that no explicit definition of a data table is provided, so for some content authors it may be challenging
> to know when a table contains data, and when it constitutes a table used solely (or partly) for layout purposes.

Included instead learning outcomes saying:

> explain the accessibility considerations of using layout tables and avoid using layout tables when possible

Which focuses more on the issues that layout tables can create and on a stronger message for students to learn that layout tables should be avoided.

Background
https://www.w3.org/2022/08/23-wai-curricula-minutes.html#t04
