### ISSUE TITLE
[Content Author Module 1: Clear Content] Suggestion for easier reading

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#580]
The second sentence in the introduction of the "Titles and Link text" topic reads

> Explain that it is best practice to put information that is specific to the page first in titles and link text to favor efficiency.

My suggestion for easier reading is

> Explain that it is best practice to put first in titles and link text the information that is specific to the page to favor efficiency.

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

> Explain that it is best practice to put first in titles and link text the information that is specific to the page to favor efficiency.

If I had to translate this sentence into Spanish, that's how I would do that. I guess in Portuguese it reads better like this as well. Not so sure if that sounds as goodin English. Maybe @shawna-slh  has input on this.

**Comment by daniel-montalvo** [comment]
Closing. On-going work is now in #616
