### ISSUE TITLE
[Content Author Module 1: Clear Content] Reference to possible inaccessibility of authoring tools

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#581]
Where: Topic Titles and Link Text. 2nd teaching idea. Last sentence.

> Explain that some tools may produce accessible content but may not be accessible themselves and vice versa.

While this is true I was surprised to find this in the scope of this teaching idea. It is not mentioned in other places where authoring tools are mentioned, from what I could find. Wouldn't it be better to move this to the overview page?

**Comment by daniel-montalvo** [comment]
Thanks @carlosapaduarte 

This is a mistake. I took it away from the rest of the places where it appeared, but not from this one.

This reference is now in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/ 

> These modules focus on accessible content creation. Authoring tools selection is out of scope for these modules. The modules are primarily designed for teaching:
  ...

I am not really sure that this is how we want to address it. We could now argue that we could get rid of this warning as we are now linking to [Authoring Tool Accessibility Guidelines (ATAG) Overview](https://www.w3.org/WAI/standards-guidelines/atag/) and we are recommending this to be an instructor competency.

We have tried this notes or warnings in the past and they have not worked well.

**Comment by daniel-montalvo** [comment]
[TF meeting 12 July discussion](https://www.w3.org/2022/07/12-wai-curricula-minutes.html#item05)

**Comment by daniel-montalvo** [comment]
In [Topic Titles and Link Text, 2nd teaching idea](https://wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-titles-and-link-text), last sentence, we had:

> Explain that some tools may produce accessible content but may not be accessible themselves and vice versa.

But that applies throughout, not just in there.

How should we refer to authoring tools accessibility in content author modules, if at all?

**Proposal**

TF leans towards having a reference in the overview page that authoring tools are out of scope for this module but it is the responsibility of the instructor to select the appropriate authoring tool type and version based on course setup.

See  [updated draft](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/#introduction), last paragraph.

> These modules do not cover specifics on authoring tools accessibility. Instructors should take the responsibility to choose the appropriate authoring tool type and version based on the specific course setup. For more details, see [Accessible authoring tools](https://www.w3.org/WAI/standards-guidelines/atag/).

Throughout, 'accessible authoring tools' is one of the instructors competencies, and is linked to [ATAG Overview](https://www.w3.org/WAI/standards-guidelines/atag/)

For example, [Instructor Competencies for Clear Content](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#instructors)

**Comment by shawna-slh** [comment]
[29 July 2022 EOWG minutes](https://www.w3.org/2022/07/29-eo-minutes#item07)

**Comment by daniel-montalvo** [comment]
Closing based on [29 July 2022 EOWG minutes](https://www.w3.org/2022/07/29-eo-minutes#item07)
