### ISSUE TITLE
[Content Author Module 2: Structure] Page Not Found error

### ISSUE THREAD

**Issue by kheitm** [w3c/wai-curricula#584]
Page not found error when clicking on link for:

 Teaching Resources "How People with Disabilities use the Web"
https://wai-curricula.netlify.app/people-use-web/

**Comment by daniel-montalvo** [comment]
> Page not found error when clicking on link for:
> 
> Teaching Resources "How People with Disabilities use the Web" https://wai-curricula.netlify.app/people-use-web/

Thanks @kheitm 

This is due to how the relative urls are built in the WAI-website.

We are aware of this issue and are working on a fix for this.
