### ISSUE TITLE
[Content Author Module 2: Structure] Page Not Found error

### ISSUE THREAD

**Issue by kheitm** [w3c/wai-curricula#585]
Page not found error when clicking on link for:

Teaching Resources "Understandable Content (Web Accessibility Perspective)
https://wai-curricula.netlify.app/perspective-videos/understandable/

**Comment by daniel-montalvo** [comment]
> Page not found error when clicking on link for:
> 
> Teaching Resources "Understandable Content (Web Accessibility Perspective) https://wai-curricula.netlify.app/perspective-videos/understandable/

Thanks @kheitm 

This is due to how the relative urls are built in the WAI-website.

We are aware of this issue and are working on a fix for this.

**Comment by kheitm** [comment]
Thanks, @daniel-montalvo I figured as much after I realised its on all the pages
