### ISSUE TITLE
[Content Author Module 2: Forms]  Add Teaching Resource

### ISSUE THREAD

**Issue by kheitm** [w3c/wai-curricula#586]
Add resource "Forms Tutorial"

https://www.w3.org/WAI/tutorials/forms/

**Comment by daniel-montalvo** [comment]
Thanks @kheitm 

Relevant tutorials have been added to

- [2: Structure](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/)
- 3: [Forms](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/)
- 5: [Data Tables](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/)

We did have tutorials in "images", so I think with this we are now more consistent.

We don't have a perfect fit for [1: Clear Content](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/)

And for [6: Multimedia](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/) we have the [Making Audio and Video Media Accessible](https://www.w3.org/WAI/media/av/) resource.
