### ISSUE TITLE
[Content Author Module 1: Clear Content] [low] Abbreviations learning outcome

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#588]
The learning outcome for abbreviations and acronyms is:

> provide the extended form for abbreviations and acronyms

However, there are different ways to do this that isn't necessarily clearly articulated in this outcome. Perhaps something like:

> understand the different methods used to explain abbreviations and acronyms

Something more about what the goal is rather than just what the activity is, if that makes any sense!

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

I propose:

> describe methods to provide the extended form for abbreviations and acronyms

As "understand" is not an unambiguous verb according to Bloom's taxonomy.

**Comment by iadawn** [comment]
That is fine. I couldn't remember the name of the taxonomy that you were using but I figured you would adjust accordingly :)
