### ISSUE TITLE
[Content Author Module 1: Clear Content] [low] 'Error' in title

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#591]
One use of title that is often not used is to indicate that there are errors in a form submission. Might it be useful to includes this in the first list item in the teaching ideas for the Titles and Link Text topic?

**Comment by daniel-montalvo** [comment]
Hey @iadawn 
Thanks for your suggestion.

I propose:

> Discuss different pieces of information that page titles can contain. For example, specific information about the page, current step of a process, form errors, and overall information about the site. [...]
