### ISSUE TITLE
[Content Author Module 1: Clear Content] [medium] Authoring tools knowledge

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#592]
This may be for a subsequent iteration as I think it is quite a bit of work.

The competencies indicates that instructors are required to have in-depth knowledge of accessible authoring tools. There is no link for this however, and this is quite an involved topic that might benefit from additional primer information.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for bringing this to our attention.

Some ideas for discussion.

- Remove this completely for the current iteration as it seems it is not sufficiently addressed throughout
- Keep this reference and include a pointer to
  - [ATAG overview](https://www.w3.org/WAI/standards-guidelines/atag/)
  - [Selecting and Using Authoring Tools for Web Accessibility](https://www.w3.org/WAI/impl/software)
  - Any other WAI resource?

**Comment by iadawn** [comment]
My ideal would probably be to drop it as I think authoring tool choices aren't necessarily made by content authors.

However, removing it might be tricky as authoring tool choice is mentioned throughout. On that basis I think linking to ATAG overview would be a reasonable starting point for the current iteration. The Selecting and Using Authoring Tools for Web Accessibility resource is linked to from the ATAG overview and looks like it is in need of an update so linking to that directly may cause more work.

**Comment by daniel-montalvo** [comment]
Let's then do that.

I will link this to the [ATAG Overview page](https://www.w3.org/WAI/standards-guidelines/atag/).
