### ISSUE TITLE
[Content Author Module 2: Structure] [medium] Meaningful content sequence?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#596]
In the Orientation and Navigation topic it talks about 'meaningful content sequences'. I am not sure it is clear enough what this is.

**Comment by daniel-montalvo** [comment]
Hey @iadawn

I have now taken a pass at this at

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/#topic-orientation-and-navigation

I changed "meaningful content sequences" to "content that follows a meaningful sequence".

I was trying to cross reference to the designer and developer parts, similarly to how I did in the learning outcomes for module. But maybe these don't come across very well and are confusing. I will discuss with the TF if we should remove this or better qualify these references.

**Comment by iadawn** [comment]
Thanks @daniel-montalvo,

I think the phrase 'meaningful content sequences' might be where I am tripping up. It is also used in the Learning Outcomes and I think it could be more clearly expressed. For example, instead of:

> ensure meaningful content sequences for different screen sizes, user configurations, and assistive technologies in use

use something like:

> ensure the order in which content is presented makes sense for different screen sizes, user configurations, and assistive technologies in use

I wonder if the other points where the phrase is used could be unpacked a bit as well?

**Comment by shawna-slh** [comment]
How about use the [WCAG 1.3.2 terminology](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html) exactly, and also explain:

> ensure meaningful sequence, that is, the reading order makes sense for different screen sizes, user configurations, and assistive technologies

... Daniel notes headings important, too - so maybe:

> ensure meaningful sequence, for example, the reading order makes sense for different screen sizes, user configurations, and assistive technologies


_(also deleted "in use" at the end)_

**Comment by daniel-montalvo** [comment]
Hey @iadawn  and @shawna-slh 

I changed the following:

LOs for module:

> collaborate with designers and developers to ensure meaningful sequence, for example, the reading order, makes sense for different screen sizes, user configurations, and assistive technologies

There we introduce the term "meaningful sequence" and provide one example.

---

Topic Orientation and Navigation

Intro:

> Introduce navigation and orientation methods that enable people with disabilities to orient themselves and navigate content. These include a correct reading order, a table of contents, footnotes, and methods for users to move back and forth through long passages of content.

Learning outcomes for topic:

> explain how people with disabilities rely on a correct reading order, a table of contents, and other orientation and navigation methods to orient themselves and navigate content

We use "reading order" based on the example provided in the learning outcomes for module.

---

I think this is clearer now. Will mark it as "done" unless there is additional comments.
