### ISSUE TITLE
[Content Author Module 5: Data Tables]  Table Header Cells

### ISSUE THREAD

**Issue by kheitm** [w3c/wai-curricula#597]
Under Teaching Ideas for Topic, bullet 3 it says "Some authoring tools let specify the scope of header cells" which maybe has a word missing or is structured awkwardly.

**Comment by daniel-montalvo** [comment]
Hey @kheitm 

Thanks for pointing this out.

Following #609, I will change from "let specify ..." to "let content authors specify ..."


There is an omitted subject there which is not good English grammar.
