### ISSUE TITLE
[Content Author Module 4: Images] [low] Requirements for image types in parenthesis?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#599]
In the learning outcomes for the module, the requirements for each image type is included in parenthesis after the type name. I wonder if it would be better to be included after an mdash and just remove the brackets? It seems that it is important information to be relegated to a parenthetical aside.

**Comment by daniel-montalvo** [comment]
Done in 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/images
