### ISSUE TITLE
[Content Author Module 4: Images] [low] Empty alternative text

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#600]
In the Informative Images section there is the paragraph:

> Decorative images do not convey information. They require an empty alternative text.

Decorative images require an empty alt attribute or they require empty alternative text. I think the presence of the 'an' is confusing. I favour the latter as the former starts to talk code - albeit a really, really small bit of code.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Done in 
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/images/#topic-informative-images
