### ISSUE TITLE
[Content Author Module 4: Images] [medium] Missing marking decorative images

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#602]
In the learning outcome for Informative Images, the list of requirements for authoring tools could include:

* identify and produce appropriate markup for decorative images

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

I tried this in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/images/#topic-informative-images

When I see this in context, I am not convinced that we should use "identify". Maybe we should just have:

> produce appropriate markup for decorative images

I am afraid "Identify" can be read as if the authoring tool itself should tell the author when an image is decorative and when it is not. And I don't think we should take that risk..
