### ISSUE TITLE
[Content Author Module 4: Images] [high] Envelop not for print

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#603]
I would never associate an envelope icon for print functionality. An envelope would have much more of an association with email. For print I would think of a wee printer icon.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

More up-to-date work is in #604 

There, I am proposing:

> Functional images convey functionality. For example, a magnifying glass for search, an envelope for mail, and a printer for print functionality. [...]

This includes your changes above and moving from plural to singular as you suggest in #604
