### ISSUE TITLE
[Content Author Module 5: Data Tables] [medium] What is contained in a data cell

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#607]
The Table Data Cells topic starts with:

> Table data cells contain information about a specific type of data in a row or column

I think this is a bit convoluted and possibly misleading. It doesn't really contain information about a specific type of data, it contains a specific piece of data. Maybe something like:

> Table data cells contain the individual pieces of data that make up the content of the table

Alternative, it might be better to drop the sentence entirely. If it is not clear what a table data cell is, then perhaps it is the topic title that is incorrect?

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 

The TF discussed this in our [12 July meeting](https://www.w3.org/2022/07/12-wai-curricula-minutes.html#item03).

We will implement your suggestion to make the definition clearer and will take a pass at that topic to update it accordingly.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Updated topic is in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/#topic-table-data-cells


I think this addresses your concerns. Will mark as resolved. Feel free to comment if you think otherwise.
