### ISSUE TITLE
[Content Author Module 5: Data Tables] [low] Table summary

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#608]
Should the table summary not include a high level summary of what the data in the table is saying as well? I think there is a bit of inconsistency between the start of the topic, which has:

> Table summaries identify the table purpose

And content in the teaching ideas, which has:

> Explain that summaries provide information about what the table is about

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

I have changed these two.

Ref:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/#topic-table-summaries-and-descriptions

* Intro paragraph.

  > Table summaries identify the table purpose and explain what the table is about. Table descriptions explain how the table is organized, especially for complex tables. Both summaries and descriptions help people with disabilities distinguish tables from one another on a page.

* Teaching idea, second bullet

  > Show examples of table summaries. Explain that summaries identify the table purpose and provide information about what the table is about. 

I think these two are more consistent now.
