### ISSUE TITLE
[Content Author Module 6: Multimedia] [low] Multimedia types seem unclear

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#611]
In the learning outcomes for planning, there is the bullet point:

> multimedia types, such as live and prerecorded

I am not sure these are types of multimedia. An alternative may be:

> delivery schedule, such as live or prerecorded

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

The phrase "multimedia types" in LOs is removed in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-planning-audio-and-video

> * determine the required alternatives to multimedia content, including transcripts, description, captions, and sign language, based on:
>   * audio and/or video
>   * live or prerecorded
>   * ...

I think this addresses your concern.
