### ISSUE TITLE
[Content Author Module 6: Multimedia] [medium] What 'description' is

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#612]
The opening sentence to the Description of Visual Information seems peculiar:

> Description explains visual information needed to understand the content for people who cannot see the video

I appreciate the challenge with this since 'audio description' isn't the only option. Perhaps something like:

> Descriptions of visual information may be needed for people who cannot see the video to understand the content.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 


We could probably do even more direct.

> people who cannot see the video need description of visual information to understand the content.

This does not align strictly to the other topics intro paragraphs. But I feel "transcripts" and "captions" do require further explanations of what they are, whereas the word "description" is easier to understand by itself.

Just an idea for the moment, I'll play with the others and see what fits better where.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 
Addressed in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information
