### ISSUE TITLE
[Content Author Module 1: Clear Content] Put info first to favor efficiency

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#616]
### Topic: Titles and Link Text

Titles and link text are essential for some people with disabilities to understand the page purpose and to know where links go to. Explain that it is best practice to put information that is specific to the page first in titles and link text to favor efficiency.

Suggestion:
Titles and link text are essential for some people with disabilities to understand the purpose of a page and to know where links land. Explain that it is best practice to put information that is specific to a page in the page title and also in the link text so as to favor efficiency.

**Comment by daniel-montalvo** [comment]
Closes: #580

**Comment by daniel-montalvo** [comment]
Hey @vmmiller 

> Titles and link text are essential for some people with disabilities to understand the purpose of a page and to know where links land. 

Thanks. I will change.

> Explain that it is best practice to put information that is specific to a page in the page title and also in the link text so as to favor efficiency.

"Information that is specific to a page" would be already covered in [WCAG 2 2.4.9 Link Purpose (Link Only)](https://www.w3.org/WAI/WCAG21/quickref/#link-purpose-link-only).

If we implement this, we would be dropping the "first" and I feel it's nice to have it in here.

I would say the best practice here really is to put unique, specific information first to favor efficiency.

What about

> Explain that it is best practice to front-up information that is specific to a page in the page title and also in the link text so as to favor efficiency.

or

> Explain that it is best practice to front information that is specific to a page in the page title and also in the link text so as to favor efficiency.

Do "front" and "front-up" work the same in this context?

**Comment by vmmiller** [comment]
Hi @daniel-montalvo - Concerning the text
"Explain that it is best practice to put information that is specific to the page first in titles and link text to favor efficiency."
and your two suggestions.  I prefer to revert to your original text for the greater part.  The interesting phrase for me to address is "to favor efficiency".  I know what you mean but I'm not sure we are putting the message across clearly. So, some brainstorming... 

Here is a revised suggestion based on your original text.

"Explain that it is best practice to put information that is specific to a page, first, upfront in the title and next, in the link text. 
 This provides the user with a clear understanding of the page and the intent of the links contained therein.

**Comment by daniel-montalvo** [comment]
Hey @vmmiller

I had a closer look at [Provide Informative, Unique Page Titles](https://www.w3.org/WAI/tips/writing/#provide-informative-unique-page-titles). 
There we only advice to "put unique and most relevant information first" for page titles. Probably we should do for links as well, but we don't.

So I adapted our wording accordingly in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-titles-and-link-text

And also added a pointer to that section of the Tips for Getting Started resource.
I think this clarifies scope, as I was trying to go beyond what we ourselves recommend in the Tips for Getting Started resource.
