### ISSUE TITLE
[Content Author Module 2: Structure] "tables of contents" -> "table of contents"

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#618]
### Learning Outcomes for Module

Fourth bullet point:

- collaborate with designers and developers to:
     - include methods to move back and forth through long pieces of content, including tables of contents and “back to top” links

Suggestion: "tables of contents" > singlular
Change to "tables of content"

**Comment by shawna-slh** [comment]
+1 to singular table of contents

could make link singular, too:
> include methods to move back and forth through long pieces of content, including a table of contents and a “back to top” link

**Comment by shawna-slh** [comment]
_side rant you can ignore:_ Technically what we have on a web page is not a table. It's a list. Yet, "table of contents" is an old term people know and it's in WCAG Techniques so I'll try to let it go. :-)

**Comment by daniel-montalvo** [comment]
Changed.
