### ISSUE TITLE
[Content Author Module 2: Structure]

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#619]
### Teaching Ideas for Topic

3rd bullet point:

- Explain other uses of heading text. These include providing a headline for a piece of news and summarizing the content the heading precedes.

Second part of the sentence is a little puzzling at first glance.  Suggestion for change:

- Explain other uses of heading text. These include providing a headline for a piece of news which effectively summarizes the content which follows.

**Comment by daniel-montalvo** [comment]
Thanks @vmmiller 
Changed to:

> Explain other uses of heading text. These include providing a headline for a piece of news which effectively summarizes the content that follows.

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/#topic-headings
