### ISSUE TITLE
[Content Author Module 2: Structure] Expand sentence

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#620]
### Topic: Paragraphs and Lists

First sentence could be expanded for clarity.  
Paragraphs and lists group related content. 

Paragraphs and lists can be used to group related content.

**Comment by daniel-montalvo** [comment]
Thanks @vmmiller 

I think the current is shorter and more direct.

What's the benefit of having "can be used" there?

**Comment by daniel-montalvo** [comment]
Hey @vmmiller 

I've taken another pass at this. In addition to the above, it has a passive "can be used" that I think we should avoid.

I think I should leave this sentence as it was, so I will be closing this.

Feel free to reopen if needed.
