### ISSUE TITLE
[Content Author Module 2: Structure] Add "where are situated within the content"

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#621]
### Teaching Ideas for Topic

1st bullet point:

- Demonstrate the use of assistive technologies to navigate through long passages of text. Explain that several groups of users rely on orientation and navigation methods to understand where they are in the content and to move back and forth through different content sections.

Very minor suggestion in the second sentence to emphasize the orientation and navigation:

Explain that several groups of users rely on orientation and navigation methods to understand where they are situated within the content and how they can move back and forth through different content sections.

**Comment by daniel-montalvo** [comment]
Thanks @vmmiller 

I am not sure if the word "situated" is sufficiently understood. I get that "where they are" may be a little bit unclear, I will give this a thought and come back with a proposal.

**Comment by daniel-montalvo** [comment]
Thanks @vmmiller 
Changed to:

> Demonstrate the use of assistive technologies to navigate through long passages of text. Explain that several groups of users rely on orientation and navigation methods to understand the overall content structure and to move back and forth through different content sections.

I think it is clearer if we focus on understanding the overall content structure, rather than on understanding where someone is located or situated within the content.

See
https://content-author-modules--wai-curricula.netlify.app/curricula/structure/#topic-orientation-and-navigation
