### ISSUE TITLE
[Content Author Module 2: Structure] Minor edits

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#622]

**Comment by vmmiller** [comment]
### Topic: Orientation and Navigation

First paragraph:
Introduce navigation and orientation methods that help people with disabilities orient themselves and navigate content. These include meaningful content sequences, tables of contents, footnotes, and methods for users to move back and forth through long passages of content.

Minor edits (editor's discretion)
Introduce navigation and orientation methods that help people with disabilities to orient themselves and navigate through content. These include meaningful content sequences, inserting a table of contents, adding footnotes and including methods for users to move back and forth through long passages of text.

BTW, I do have a problem with "tables of contents" (plural all round). It just seems very odd in plural and - at least for me - much easier to read in the singular, i.e., "table of contents".  Could we not have it in singular given that we would normally have a single table of contents for a page?
So, I have made some suggestions as follows putting "tables of contents" into singular:

### Learning Outcomes for Topic

- explain how people with disabilities rely on meaningful content sequences, table of contents, and other orientation and navigation methods to orient themselves and navigate through content
(so toc is in singular and I added "through" between "navigate" and "content")

- utilize a table of contents to:
(here put into singular)

- ensure availability of methods for users to move back and forth through long passages of content, for example using:
   - a table of contents

**Comment by shawna-slh** [comment]
+1 to singular table of contents

make the first thing singular, too, and it's smooth:
> explain how people with disabilities rely on meaningful content sequence, table of contents, and other orientation and navigation methods...

**Comment by daniel-montalvo** [comment]
Thanks @vmmiller and @shawna-slh 

Changed throughout in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/structure/#topic-orientation-and-navigation.
