### ISSUE TITLE
[Content Author Module 2: Structure] "tables of contents" -> "table of contents"

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#624]
### Topic: Orientation and Navigation
Sub-heading: Teaching Ideas for Topic

2nd bullet point:
(my favorite plural "tables of contents"... screech to the ear).

Current:
Show examples of tables of contents. Explain that they provide a summary of the overall structure of the whole piece of content. They also enable users to get to the specific sections they are interested in.

Suggestion (for editor's discretion):
Show examples of how a table of contents provides a summary of the overall structure of the whole piece of content. The table of contents also enables users to efficiently jump to specific sections of interest.

**Comment by shawna-slh** [comment]
+1 to singular.

another brainstorm is:
> Show examples of tables of contents.

->

> Show web pages with a table of contents.

**Comment by daniel-montalvo** [comment]
changed to:

> Show web pages with a table of contents.
