### ISSUE TITLE
[Unit 2] (medium) unclear Learning Outcome

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#63]
In [Learning Outcomes](https://deploy-preview-50--wai-curricula.netlify.com/curricula/1-2/#learning-outcomes-1)
> * Differentiate the interdependencies between digital accessibility, content technologies, and tools

I don't understand this.

**Comment by daniel-montalvo** [comment]
Changed to:

> * Describe the impact that some content technologies have on digital accessibility

I try to pick up here the influence that some of the content technologies have in digital accessibility. For instance, if somebody is writing a word document it might have a subset of the HTML markup available: headings, links, lists... If you take them into account in the original document and follow the instructions in that platform, accessibility is highly benefited. If these content technologies do not support an accessibility feature, that accessibility feature would be much more difficult to implement in the future.

**Comment by shawna-slh** [comment]
much clearer.
