### ISSUE TITLE
[Content Author Module 5: Data Tables]

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#632]
### Teaching Ideas for Topic

Current:
"Some authoring tools let specify the scope of header cells."

As in a previous example, I think "content authors" is missing.

Proposal:
"Some authoring tools let content authors specify the scope of header cells."

**Comment by daniel-montalvo** [comment]
Addressed in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables
