### ISSUE TITLE
[Content Author Module 6: Multimedia]

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-curricula#633]
### Topic: Planning Audio and Video

First sentence:
Introduce different user needs for audio and video content. For example, for people who don’t see the video and for people who don’t hear the audio.

(The "For example" sentence).
Proposal:
Introduce different user needs for audio and video content, for example, people who cannot see the video and for people who cannot hear the audio.

**Comment by daniel-montalvo** [comment]
Thanks for this, @vmmiller 
We are going to leave this as-is for now and will discuss this with @shawna-slh  in case we want to reopen that '"For example," OK as own sentence' [style issue](https://www.w3.org/WAI/EO/wiki/Style#Punctuation)

**Comment by shawna-slh** [comment]
We probably should revisit this style issue; however, I don't have the time right now.

Daniel, sometimes you can tweak the wording to make the For example better standalone. For example (ha,ha):

> Introduce different user needs for audio and video content. For example, explain the needs of people who don’t see the video and people who don’t hear the audio.

While that is a few more words, I think it's worth it to improve understanding and to flow better. Feel free to disagree.

I updated the Style Guide with this suggestion. We can change it as warranted.

**Comment by daniel-montalvo** [comment]
I took another pass.

Changed to:

> Introduce different user needs for audio and video content, including for people who don't see the video and for people who don't hear the audio. For details, see [Understand the User Needs and Experiences of People with Disabilities ](https://www.w3.org/WAI/media/av/users-orgs/#understand-the-user-needs-and-experiences-of-people-with-disabilities).

Closing, I think it resolves the main issue of 
for example" as own sentence.
