### ISSUE TITLE
[all] Collapse prerequisites section by default in overview pages

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#634]
@kakinney says:

> Any way to consolidate or collapse the prerequisite information? by this module, that list is getting long and I worry we may lose people there before they even get to the structure of the current module. Not a strong feeling either way - just wondering if anyone feels/felt the same?

**Comment by daniel-montalvo** [comment]
See how this looks like in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/

**Comment by shawna-slh** [comment]
We could also improve the list item spacing in several places, which would help the page overall.
UPDATE: List spacing seems to be messed up in my configuration and not in another I checked. So, ignore this for now.
