### ISSUE TITLE
Content Author - Forms - visible label wording change

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-curricula#639]
Recently updated suggestion for Topic Labels, teaching ideas, first bullet:
"Explain that several groups of users require labels that are persistently visible on the page. Content authors should avoid the use of placeholder text that disappears when the user gets to the form field or control."

Suggested update:
"Explain that several groups of users require labels that are persistently visible on the page. Content authors should avoid the use of placeholder text that disappears when the user starts to enter text into the form field or control."

Reasoning:
Placeholder text does not disappear when simply focusing on a text field. It disappears when a user starts typing in the field.

**Comment by daniel-montalvo** [comment]
Thanks @brianelton 

Done

https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/#topic-labels
