### ISSUE TITLE
[Content Author Module 1: Clear Content] [ED-high] Different groups

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#656]
The rewording for the 'Titles and Link Text' introduction is:

> The page title is essential for some groups of people with disabilities to know the purpose of the page. The link text is crucial for those groups to know where the link lands.

I am not sure that the groups that require titles are the same as the groups that require good link text. There is certainly overlap but the introduction suggests a complete overlap.

Perhaps something like:

> The page title is essential for some people with disabilities to know the purpose of the page. The link text is crucial for some people to know where the link lands.

I have removed 'groups' as I am not sure of the value of that but if it is more consistent to leave this in then that is fine.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 
That's now done per above commit.

**Comment by remibetin** [comment]
@daniel-montalvo Can we close this issue?

cc @shawna-slh

**Comment by remibetin** [comment]
As agreed with @daniel-montalvo, I am closing this issue.
