### ISSUE TITLE
[Content Author Module 2: Structure] [ED-med] Unclear rewrite

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#657]
In the 'Headings' topic a learning outcome has been changed to:

> describe the accessibility considerations when changing the default visual appearance of headings, including the potential inaccessibility of:
> * the selected custom visual appearance
> * the generated markup

I am not sure what this means. I am guessing the first part is "if you change the styling, make it accessible" and the second part might be "use heading elements". It seems a bit vague though. Particularly the latter point, if I am guessing correctly, could be much clearer.

**Comment by daniel-montalvo** [comment]
Thanks @iadawn 

That's precisely what all of this is about.

But you are right that this is getting too much into detail probably.

What about

> describe the characteristics of accessible headings, including text, visual appearance, and markup

Which reinforces the idea that accessible headings are not just about visual appearance, but also about good markup

**Comment by iadawn** [comment]
Happy with that suggested change.

**Comment by remibetin** [comment]
@daniel-montalvo Can we close the issue that seems resolved?

cc @shawna-slh

**Comment by remibetin** [comment]
As agreed with @daniel-montalvo, I am closing this issue.
