### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by tilensA11Y** [w3c/wai-curricula#669]
Link [How People with Disabilities Use the Web](https://www.w3.org/people-use-web)](https://www.w3.org/People-use-web) on the page [Curricula on Web Accessibility](https://www.w3.org/WAI/curricula/) is not working, should probably point to https://www.w3.org/WAI/people-use-web/ ?

**Comment by daniel-montalvo** [comment]
Hi @tilensA11Y 
This is now resolved. Closing.
