### ISSUE TITLE
Start, Stop, and continue exercise might need more refinement

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#70]
@lakeen says:

> I did not know what Stop, Start,
Continue exercise meant I had to google it.

In context -- Unit 5 Topic Planning and Managing Accessibility:

> • Engage students in a Start, Stop, Continue exercise to identify processes, tasks, and strategies within their organization for which accessibility implementation
may need to be revised.

Does it need further refinement?

**Comment by nitedog** [comment]
I also do not know what you mean with Start, Stop. Continue exercises.

**Comment by lakeen** [comment]
@daniel-montalvo  it may need more clarification, maybe a link to a good definition or something similar.  I think it would be a good question for the group.

**Comment by daniel-montalvo** [comment]
Thanks @nitedog and @lakeen for the reply.

Pointing to a well-vetted, external, vendor neutral resource could be a difficult (and time consuming) task. 

what we are asking here is that students research into processes within their organization and reflect on whether they need improvement, so I have taken a different approach, stepping back from the concrete exercise and coming into a more general approach. If a particular instructor wants to do a Start, Stop, and Continue exercise, that's fine, but there might be instructors who prefer to do this exercise differently.

I edited this homework. Now it is:

> * Ask students to identify accessibility related processes within their organization. Based on what they have learned, invite them to research on which of these processes require updates to better integrate accessibility.


Is it now clearer?

**Comment by lakeen** [comment]
@daniel-montalvo that's better for me. Thanks!

**Comment by nitedog** [comment]
Principally agree with this but disagree with "their organization" -- don't think we should assume that students work for an organization (or an organization that is of relevant size for this task). I think this assumption is repeated in several places throughout the entire module.

**Comment by daniel-montalvo** [comment]
Ideas to Assess Knowledge is the new title for the former Ideas for Assessment. All these ideas have been reformulated and now the Start, Stop and Continue exercise does not appear in here.  Changed to:

> * Reflective Journal &mdash; Students identify accessibility related processes based on what they have learned, and research how to update them to better integrate accessibility. Assess students' capacity to identify strengths and weaknesses in an overall accessibility strategy.

Closing.
