### ISSUE TITLE
[all Units] clarify objective/scope section

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#74]
All units start with "This unit: ...". However, this should rather be something like "Courses based on this unit: ..." or such (it is actually the courses that deliver the content rather than the curriculum).

**Comment by shawna-slh** [comment]
I don't like (what was in Unit 4 when I reviewed it):
> Courses based on this unit are expected to:

Maybe:
> Courses based on this unit should:

I think this is just fine:
> Courses based on this unit:

**Comment by daniel-montalvo** [comment]
Courses will come after the curricula, that is, future courses will be developed from these curricula, so I guess it is not accurate to say "courses based on this unit do this and that", they **will** do, or they **should** do. I do think we need to emphasize that end.

**Comment by nitedog** [comment]
I'm happy with @slhenry's suggestions

**Comment by daniel-montalvo** [comment]
Addressed. Feel free to reopen if necessary.
