### ISSUE TITLE
[High] [all Units] ideas for assessment read like learning objectives

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-curricula#76]
Seems like this section is rephrasing existing learning outcomes rather than to provide ideas on how to assess that students have these learning outcomes.

**Comment by shawna-slh** [comment]
+1 (I noted that in my review of Unit 4 just now)

**Comment by daniel-montalvo** [comment]
Addressed with work on "Ideas to Assess Knowledge" sections.
