### ISSUE TITLE
[Unit 4] Clarify Learning Outcome bullet #1?

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#86]
[Medium]
First bullet of the Unit 4 Learning Outcomes... 

> Define the terms “Perceivable”, “Operable”, “Understandable”, and “Robust” (POUR)

Do we need to be more clear about the usage of these terms so they are defined within that usage, or will that by implied strongly enough because this is an accessibility resource? In other words, should this be switched to... 
> Define the terms “Perceivable”, “Operable”, “Understandable”, and “Robust” (POUR) as related to web accessibility guidelines.

**Comment by daniel-montalvo** [comment]
It is always good to make sure the message is understood.

Good suggestion, I'm just adding this to the live draft and this issue will close when merged into master.
