### ISSUE TITLE
[Unit 4] Use of the term "requirements"

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#87]
There are a couple of places where the term "requirements" is used in this unit. One place is in the Learning Outcomes of the topic "Principles of Accessible Design," the other is in the Ideas for Assessment section. I am assuming that this term is used to refer to the Success Criteria themselves. If we are going to use the term requirements, I think it should be defined that these would be the success criteria statements.

An example of where this is done in another resource of our is in the WCAG Overview page under the topic of [WCAG 2.0 and 2.1](https://www.w3.org/WAI/standards-guidelines/wcag/#versions).

Usually the term requirements is not used in the actual standards pages except where one needs to "allow WCAG 2.0 to be used where requirements and conformance testing are necessary..." (reference [Layers of Guidance](https://www.w3.org/TR/WCAG20/#intro-layers-guidance))

**Comment by daniel-montalvo** [comment]
I have added the following in the introductory paragraph of the unit:
> * relate the standards' requirements <ins>(success criteria)</ins> to preliminary accessibility checks. 

For the rest of the times the term "requirements" appears, hopefully this clarification will be understood.

Is this what you were thinking about?

**Comment by bakkenb** [comment]
Thanks Daniel. I think this is okay. Would like @slhenry and @yatil to weigh in on this from team contact perspective, as well as other EOWG participants.

**Comment by shawna-slh** [comment]
+1 for not using the word "requirements" at all if we can easily avoid it. ("requirements" has a specific meaning in W3C)

In https://github.com/w3c/wai-curricula/issues/89#issuecomment-525987287 I suggest:
> I think the Standards Topic should introduce "success criteria" and then use that terminology.

Actually, hopefully instructors already know the term "success criteria" for WCAG!

<hr>

The word "requirements" is not used at all in this idea for revisions:
* [Preview 96](https://deploy-preview-96--wai-curricula.netlify.com/curricula/1-4/)
* [diff](https://github.com/w3c/wai-curricula/pull/96/files)
so probably it's easily do-able. :)

**Comment by daniel-montalvo** [comment]
This has been addressed in the [Live draft](https://deploy-preview-72--wai-curricula.netlify.com/curricula/1-4/)

Feel free to reopen if necessary.
