### ISSUE TITLE
[Unit 4] Order of topics Principles and Standards  vs Standards and Principles

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#89]
This was a last minute change that I made this summer. There have been several questions about this in the survey: 

@Eoncins says:

> I am not sure if it would be better to first introduce the topic "Standards and Guidelines" and then the topic "Principles of Accessible Design"

KrisAnne says:

> When we're talking about standards - are we talking about the broad standards of WCAG, ATAG, and UAAG? Not the success criteria that are under each of the principles that we talked about earlier section. If we're talking broad scope - should the Standards and Guidelines section go first before we drill into the principles of accessible design? Thinking of the flow of the learning here. 

As I see it, the principles are present through all standards (with the exception of WAI-ARIA, where the outline is different. The other three build on top of such principles and then develop their own requirements depending on the specific component they address. This is why I thought it would be good to first introduce these foundations and then dive into particular standards. Please take a look at the [Live draft](https://deploy-preview-72--wai-curricula.netlify.com/curricula/1-4/) to see the changes and reply if you still don't agree with this approach.

**Comment by shawna-slh** [comment]
+1 to Daniel.

Looking at the overall flow of Module 1, I strongly support teaching the Principles before the standards/guidelines. Principles are broader and conceptually they are at a higher level than the Standards.
* Unit 1 – intro
* Unit 2 – how people use the web, tools, and strategies
* Unit 4 – principles, *then* standards

To make this work well, I also strongly think that the topics need to be tweaked to clearly distinguish the difference:
* Principles are **broadly introducing concepts**. Avoid the word "requirements" in the Principles Topic, and avoid or limit mentioning specific standards.
* Standards are **specifically defining requirements** (called "success criteria"), that fall under the broad Principles. I think the Standards Topic should introduce "success criteria" and then use that terminology.

Ideas for doing this are in:
* [Preview 96](https://deploy-preview-96--wai-curricula.netlify.com/curricula/1-4/)
* [diff](https://github.com/w3c/wai-curricula/pull/96/files)

**Comment by shawna-slh** [comment]
More support for broad principles before specific standard/guidelines:
https://www.w3.org/2019/08/30-eo-minutes.html#item01
