### ISSUE TITLE
[Unit 4] Unit and topics' titles

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#90]

**Comment by daniel-montalvo** [comment]
For the topic 'Standards and Guidelines" KrisAnne says:

> Should this Topic have a different name than the Unit name? Would that potentially cause confusion?

**Comment by nitedog** [comment]
Maybe "W3C Accessibility Standards"?

**Comment by daniel-montalvo** [comment]
We went through titles in [last week's call](https://www.w3.org/2019/09/06-eo-minutes.html#item02) and this seems sorted out now. Feel free to reopen if necessary
