### ISSUE TITLE
[overall] list capitalization & terminal punctuation

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#98]
For lists, decide capitalization and terminal punctuation for each section, and make sure it's consistent across the resource. The WAI Style Guide gives some suggestions and also allows for flexibility: https://www.w3.org/WAI/EO/wiki/Style#Lists

I think maybe:
   - Intro: lower case, no terminal punctuation
   - Learning Outcomes: capitalized, with terminal punctuation
   - Teaching Ideas: capitalized, with terminal punctuation
   - Homework Ideas: capitalized, with terminal punctuation
   - Ideas for Assessment: capitalized, with terminal punctuation
   - Teaching Resources: capitalized, with terminal punctuation

I don't feel strongly which – just that it's consistent. :-)

**Comment by daniel-montalvo** [comment]
I would agree on this, so this would mean basically that the only place in which we would not be capitalizing is in the introductory section.

I definitely need to clean this up. Will discuss with @nitedog  as well.

**Comment by nitedog** [comment]
I also have no preference apart from consistency. This suggestion looks good to me.

**Comment by daniel-montalvo** [comment]
Addressed. Closing this.

**Comment by nitedog** [comment]
Re-reading the units, I have a mild preference for all capitalized the same way (that is, intro should not be different from the other sections).

**Comment by daniel-montalvo** [comment]
Reopenning it, since I need to go through all the units to change intros.

**Comment by daniel-montalvo** [comment]
We finally go for capitalizing first letters and adding terminal punctuation as well. Hope there are no more inconsistencies onw, feel free to ping if you find any.

**Comment by daniel-montalvo** [comment]
Reopening this as we have comments from @lakeen, at #177  @nitedog, and @slhenry 
Since some of these comments were put on issues dealing with other topics, I will be closing those as I addressed the other topics but reopen this to keep the discussion organized.

**Comment by shawna-slh** [comment]
Thanks, Daniel. I had noticed this elsewhere, and hadn't gotten around to commenting in GitHub.

strong -1 for periods at the end of list items that are Topics, SCs, etc -- e.g., https://5ef34a4fd612ce00078e8256--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#competencies

**Comment by lakeen** [comment]
I don't have a strong preference on capitalization as long as it's consistent.  I do have a strong preference for no terminal punctuation for sentence fragments.

**Comment by daniel-montalvo** [comment]
Hello all,

This has now been updated for the curriculum [Developing Accessible Content](https://wai-curricula.netlify.app/curricula/developing-accessible-content). The previously published curricula [Introduction to Web Accessibility](https://www.w3.org/WAI/curricula/) has not been updated yet.

@lakeen , @slhenry  I think this update addresses your points, so I am closing this for now. Feel free to reopen this if you think it does not.
