### ISSUE TITLE
[Unit 4][minor] capitalization and quotes for the principles

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#99]
Technically I think these should not be capitalized:

>Courses based on this unit:
> * introduce the accessibility principles Perceivable, Operable, Understandable, and Robust

However, I'm OK with capitalizing them if others want to.

> Students should be able to:
> * Explain the concepts of “Perceivable”, “Operable”, “Understandable”, and “Robust” as principles of web accessibility

Some places you have them in quotes and some note. Maybe they "should" be in quotes - maybe not. I'd have to get my Editor hat on to decide, but it's hard to get to at the moment ;-)

I think simpler not in quotes, and probably fine. Either way, should be consistent and/or technically correct.

**Comment by nitedog** [comment]
I agree with no quotes. I like capitalizing to indicate keywords. Otherwise maybe emphasis?
